import { jsPDF } from "jspdf"
import type {
    RegionalModuleResponse,
    RegionalModuleZone,
} from "../types/regional-modules"
import type { DataTableExportMetadata } from "@/features/reports/core/components/DataTable.types"
import { formatPdfValue } from "@/features/data-table/utils/pdf-export"

type ExportRegionalCompliancePdfInput = {
    data: RegionalModuleResponse
    filename: string
    metadata: DataTableExportMetadata
}

const MARGIN = 12
const HEADER_HEIGHT = 28
const FOOTER_HEIGHT = 12
const LINE_HEIGHT = 4.5
const MONTH_PATTERN = /^(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|january|february|march|april|june|july|august|september|october|november|december)/i

function formatLabel(value: string) {
    return value
        .replace(/_/g, " ")
        .replace(/\b\w/g, (char) => char.toUpperCase())
}

function addHeader(doc: jsPDF, metadata: DataTableExportMetadata) {
    const pageWidth = doc.internal.pageSize.getWidth()

    doc.setFillColor(248, 250, 252)
    doc.rect(0, 0, pageWidth, HEADER_HEIGHT, "F")
    doc.setFont("helvetica", "bold")
    doc.setFontSize(15)
    doc.setTextColor(15, 23, 42)
    doc.text(metadata.title ?? "Regional Compliance Report", MARGIN, 12)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(8.5)
    doc.setTextColor(71, 85, 105)
    doc.text(
        [
            `Region: ${formatPdfValue(metadata.region) || "Regional"}`,
            `Generated by: ${formatPdfValue(metadata.generatedBy) || "System"}`,
            `Generated: ${formatPdfValue(metadata.generatedAt ?? new Date())}`,
        ].join("   |   "),
        MARGIN,
        20
    )

    doc.setDrawColor(226, 232, 240)
    doc.line(MARGIN, HEADER_HEIGHT - 2, pageWidth - MARGIN, HEADER_HEIGHT - 2)
}

function addFooters(doc: jsPDF) {
    const pageCount = doc.getNumberOfPages()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()

    for (let page = 1; page <= pageCount; page += 1) {
        doc.setPage(page)
        doc.setDrawColor(226, 232, 240)
        doc.line(MARGIN, pageHeight - FOOTER_HEIGHT, pageWidth - MARGIN, pageHeight - FOOTER_HEIGHT)
        doc.setFont("helvetica", "normal")
        doc.setFontSize(8)
        doc.setTextColor(100, 116, 139)
        doc.text("CFI Regional Compliance", MARGIN, pageHeight - 5)
        doc.text(`Page ${page} of ${pageCount}`, pageWidth - MARGIN, pageHeight - 5, {
            align: "right",
        })
    }
}

function ensureSpace(
    doc: jsPDF,
    y: number,
    requiredHeight: number,
    metadata: DataTableExportMetadata
) {
    const pageHeight = doc.internal.pageSize.getHeight()

    if (y + requiredHeight <= pageHeight - FOOTER_HEIGHT - 4) {
        return y
    }

    doc.addPage()
    addHeader(doc, metadata)

    return HEADER_HEIGHT + 6
}

function addSectionTitle(
    doc: jsPDF,
    y: number,
    title: string,
    metadata: DataTableExportMetadata
) {
    y = ensureSpace(doc, y, 12, metadata)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.setTextColor(15, 23, 42)
    doc.text(title, MARGIN, y)

    return y + 6
}

function addKeyValueGrid(
    doc: jsPDF,
    y: number,
    values: Record<string, unknown> | undefined,
    metadata: DataTableExportMetadata
) {
    const entries = Object.entries(values ?? {}).slice(0, 12)
    if (!entries.length) return y

    y = ensureSpace(doc, y, 12, metadata)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(8.5)
    doc.setTextColor(51, 65, 85)

    const pageWidth = doc.internal.pageSize.getWidth()
    const colWidth = (pageWidth - MARGIN * 2) / 3

    entries.forEach(([key, value], index) => {
        const col = index % 3
        const row = Math.floor(index / 3)
        const x = MARGIN + col * colWidth
        const itemY = y + row * 7
        doc.setFont("helvetica", "bold")
        doc.text(`${formatLabel(key)}:`, x, itemY)
        doc.setFont("helvetica", "normal")
        doc.text(formatPdfValue(value), x + 28, itemY, {
            maxWidth: colWidth - 30,
        })
    })

    return y + Math.ceil(entries.length / 3) * 7 + 3
}

function getMonthlyKeys(row: Record<string, unknown>) {
    const keys = Object.keys(row).filter((key) => MONTH_PATTERN.test(key))

    if (keys.length) return keys

    const monthly = row.monthly ?? row.months ?? row.compliance
    if (monthly && typeof monthly === "object" && !Array.isArray(monthly)) {
        return Object.keys(monthly as Record<string, unknown>)
    }

    return []
}

function getMonthlyValue(row: Record<string, unknown>, key: string) {
    if (key in row) return row[key]

    const monthly = row.monthly ?? row.months ?? row.compliance
    if (monthly && typeof monthly === "object" && !Array.isArray(monthly)) {
        return (monthly as Record<string, unknown>)[key]
    }

    return undefined
}

function getExceptionText(row: Record<string, unknown>) {
    const values = [
        row.missing_reports,
        row.exceptions,
        row.skipped,
        row.skipped_sections,
        row.skip_reason,
        row.status,
    ].filter((value) => value != null && value !== "" && value !== 0)

    return values.map(formatPdfValue).join("; ")
}

function addAssemblyTable(
    doc: jsPDF,
    y: number,
    zone: RegionalModuleZone,
    metadata: DataTableExportMetadata
) {
    const assemblies: Array<Record<string, unknown> & { name: string; country?: string }> =
        (zone.countries ?? []).flatMap((country) =>
        (country.assemblies ?? []).map((assembly) => ({
            ...assembly,
            country: assembly.country ?? country.name,
        }))
    )

    if (!assemblies.length) {
        return y
    }

    const monthKeys = Array.from(
        new Set(assemblies.flatMap((assembly) => getMonthlyKeys(assembly)))
    ).slice(0, 12)

    const columns = [
        "Assembly",
        "Country",
        ...monthKeys.map(formatLabel),
        "Compliance",
        "Exceptions",
    ]
    const pageWidth = doc.internal.pageSize.getWidth()
    const tableWidth = pageWidth - MARGIN * 2
    const assemblyWidth = 38
    const countryWidth = 24
    const exceptionWidth = 42
    const complianceWidth = 20
    const monthWidth = Math.max(
        12,
        (tableWidth - assemblyWidth - countryWidth - exceptionWidth - complianceWidth) /
            Math.max(monthKeys.length, 1)
    )
    const widths = [
        assemblyWidth,
        countryWidth,
        ...monthKeys.map(() => monthWidth),
        complianceWidth,
        exceptionWidth,
    ]

    y = ensureSpace(doc, y, 14, metadata)
    doc.setFillColor(241, 245, 249)
    doc.rect(MARGIN, y, tableWidth, 8, "F")
    doc.setFont("helvetica", "bold")
    doc.setFontSize(7.5)
    doc.setTextColor(51, 65, 85)

    let x = MARGIN
    columns.forEach((column, index) => {
        doc.text(column, x + 1.5, y + 5, { maxWidth: widths[index] - 3 })
        x += widths[index]
    })
    y += 8

    doc.setFont("helvetica", "normal")
    doc.setFontSize(7)
    doc.setTextColor(30, 41, 59)

    assemblies.forEach((assembly) => {
        const values = [
            formatPdfValue(assembly.name),
            formatPdfValue(assembly.country),
            ...monthKeys.map((key) => formatPdfValue(getMonthlyValue(assembly, key))),
            formatPdfValue(
                assembly["compliance_percentage"] ??
                    assembly["compliance_rate"] ??
                    assembly["coverage"] ??
                    assembly["progress"] ??
                    ""
            ),
            getExceptionText(assembly),
        ]
        const lineSets = values.map((value, index) =>
            doc.splitTextToSize(value, widths[index] - 3)
        )
        const rowHeight = Math.max(
            8,
            ...lineSets.map((lines) => lines.length * LINE_HEIGHT + 3)
        )

        y = ensureSpace(doc, y, rowHeight + 2, metadata)
        x = MARGIN

        lineSets.forEach((lines, index) => {
            doc.setDrawColor(226, 232, 240)
            doc.rect(x, y, widths[index], rowHeight)
            doc.text(lines, x + 1.5, y + 4.5, { maxWidth: widths[index] - 3 })
            x += widths[index]
        })

        y += rowHeight
    })

    return y + 4
}

export function exportRegionalCompliancePdf({
    data,
    filename,
    metadata,
}: ExportRegionalCompliancePdfInput) {
    const doc = new jsPDF({ orientation: "l", unit: "mm", format: "a4" })
    addHeader(doc, metadata)

    let y = HEADER_HEIGHT + 6
    y = addSectionTitle(doc, y, "Regional Summary", metadata)
    y = addKeyValueGrid(doc, y, data.summary, metadata)

    for (const zone of data.zones ?? []) {
        y = addSectionTitle(doc, y + 2, zone.name, metadata)
        y = addKeyValueGrid(doc, y, zone.summary, metadata)
        y = addAssemblyTable(doc, y, zone, metadata)
    }

    if (!data.zones?.length) {
        doc.setFont("helvetica", "normal")
        doc.setFontSize(10)
        doc.setTextColor(100, 116, 139)
        doc.text("No compliance zones are available.", MARGIN, y + 8)
    }

    addFooters(doc)
    doc.save(`${filename}.pdf`)
}
