import {
    AbacusIcon,
    AdmissionTicketsIcon,
    AlarmClockIcon,
    AnchorIcon,
    BabyBottleIcon,
    BackpackIcon,
    BagelIcon,
    BalanceScaleIcon,
    BellIcon,
    BellWithSlashIcon,
    BlueberriesIcon,
    BooksIcon,
    BriefcaseIcon,
    BubblesIcon,
    BullseyeIcon,
    ButterflyIcon,
    CalendarIcon,
    CampingIcon,
    CardFileBoxIcon,
    CardIndexDividersIcon,
    CardIndexIcon,
    CarrotIcon,
    ChartDecreasingIcon,
    ChartIncreasingIcon,
    ChequeredFlagIcon,
    CherryBlossomIcon,
    ChocolateBarIcon,
    ClipboardIcon,
    ClockwiseVerticalArrowsIcon,
    ClosedMailboxWithRaisedFlagIcon,
    ClutchBagIcon,
    ConstructionIcon,
    CreditCard1Icon,
    CrownIcon,
    InboxTrayIcon,
    MemoIcon,
    MilitaryMedalIcon,
    OpenBook1Icon,
    SafetyVestIcon,
    RosetteIcon,
    RocketIcon,
    RingBuoyIcon,
    RescueWorkersHelmetIcon,
    RedPaperLanternIcon,
    PushpinIcon,
    PurseIcon,
    PenguinIcon,
    PersonBowingIcon,
    PersonCurlyHairIcon,
    PlacardIcon,
    PoliceCarLightIcon,
    PottedPlantIcon,
    PrinterIcon,
    PenIcon,
    PeaPodIcon,
    PartyPopperIcon,
    PaperclipIcon,
} from "./index"

const icons = [
    { name: "AbacusIcon", Icon: AbacusIcon },
    { name: "AdmissionTicketsIcon", Icon: AdmissionTicketsIcon },
    { name: "AlarmClockIcon", Icon: AlarmClockIcon },
    { name: "AnchorIcon", Icon: AnchorIcon },
    { name: "BabyBottleIcon", Icon: BabyBottleIcon },
    { name: "BackpackIcon", Icon: BackpackIcon },
    { name: "BagelIcon", Icon: BagelIcon },
    { name: "BalanceScaleIcon", Icon: BalanceScaleIcon },
    { name: "BellIcon", Icon: BellIcon },
    { name: "BellWithSlashIcon", Icon: BellWithSlashIcon },
    { name: "BlueberriesIcon", Icon: BlueberriesIcon },
    { name: "BooksIcon", Icon: BooksIcon },
    { name: "BriefcaseIcon", Icon: BriefcaseIcon },
    { name: "BubblesIcon", Icon: BubblesIcon },
    { name: "BullseyeIcon", Icon: BullseyeIcon },
    { name: "ButterflyIcon", Icon: ButterflyIcon },
    { name: "CalendarIcon", Icon: CalendarIcon },
    { name: "CampingIcon", Icon: CampingIcon },
    { name: "CardFileBoxIcon", Icon: CardFileBoxIcon },
    { name: "CardIndexDividersIcon", Icon: CardIndexDividersIcon },
    { name: "CardIndexIcon", Icon: CardIndexIcon },
    { name: "CarrotIcon", Icon: CarrotIcon },
    { name: "ChartDecreasingIcon", Icon: ChartDecreasingIcon },
    { name: "ChartIncreasingIcon", Icon: ChartIncreasingIcon },
    { name: "ChequeredFlagIcon", Icon: ChequeredFlagIcon },
    { name: "CherryBlossomIcon", Icon: CherryBlossomIcon },
    { name: "ChocolateBarIcon", Icon: ChocolateBarIcon },
    { name: "ClipboardIcon", Icon: ClipboardIcon },
    { name: "ClockwiseVerticalArrowsIcon", Icon: ClockwiseVerticalArrowsIcon },
    { name: "ClosedMailboxWithRaisedFlagIcon", Icon: ClosedMailboxWithRaisedFlagIcon },
    { name: "ClutchBagIcon", Icon: ClutchBagIcon },
    { name: "ConstructionIcon", Icon: ConstructionIcon },
    { name: "CreditCard1Icon", Icon: CreditCard1Icon },
    { name: "CrownIcon", Icon: CrownIcon },
    { name: "InboxTrayIcon", Icon: InboxTrayIcon },
    { name: "MemoIcon", Icon: MemoIcon },
    { name: "MilitaryMedalIcon", Icon: MilitaryMedalIcon },
    { name: "OpenBook1Icon", Icon: OpenBook1Icon },
    { name: "SafetyVestIcon", Icon: SafetyVestIcon },
    { name: "RosetteIcon", Icon: RosetteIcon },
    { name: "RocketIcon", Icon: RocketIcon },
    { name: "RingBuoyIcon", Icon: RingBuoyIcon },
    { name: "RescueWorkersHelmetIcon", Icon: RescueWorkersHelmetIcon },
    { name: "RedPaperLanternIcon", Icon: RedPaperLanternIcon },
    { name: "PushpinIcon", Icon: PushpinIcon },
    { name: "PurseIcon", Icon: PurseIcon },
    { name: "PenguinIcon", Icon: PenguinIcon },
    { name: "PersonBowingIcon", Icon: PersonBowingIcon },
    { name: "PersonCurlyHairIcon", Icon: PersonCurlyHairIcon },
    { name: "PlacardIcon", Icon: PlacardIcon },
    { name: "PoliceCarLightIcon", Icon: PoliceCarLightIcon },
    { name: "PottedPlantIcon", Icon: PottedPlantIcon },
    { name: "PrinterIcon", Icon: PrinterIcon },
    { name: "PenIcon", Icon: PenIcon },
    { name: "PeaPodIcon", Icon: PeaPodIcon },
    { name: "PartyPopperIcon", Icon: PartyPopperIcon },
    { name: "PaperclipIcon", Icon: PaperclipIcon },
]

export function IconGallery() {
    return (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
            {icons.map(({ name, Icon }) => (
                <div
                    key={name}
                    className="flex min-h-28 flex-col items-center justify-center gap-3 rounded-lg border p-4 text-center"
                >
                    <Icon className="size-8 fill-current" aria-hidden="true" />
                    <span className="break-all text-xs text-muted-foreground">{name}</span>
                </div>
            ))}
        </div>
    )
}
