/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const AssetsListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const assetsListResponseResultsItemAssemblyCountryCodeMax = 3;

export const assetsListResponseResultsItemAssemblyLanguageMax = 12;

export const assetsListResponseResultsItemAssemblyCurrencyMax = 12;

export const assetsListResponseResultsItemItemCodeMax = 255;

export const assetsListResponseResultsItemItemNameMax = 255;

export const assetsListResponseResultsItemDescriptionMax = 2000;

export const assetsListResponseResultsItemAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsListResponseResultsItemResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsListResponseResultsItemVendorMax = 255;



export const AssetsListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "assembly": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(assetsListResponseResultsItemAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(assetsListResponseResultsItemAssemblyLanguageMax).optional(),
  "currency": zod.string().max(assetsListResponseResultsItemAssemblyCurrencyMax).optional()
}),
  "item_code": zod.string().max(assetsListResponseResultsItemItemCodeMax).optional(),
  "item_name": zod.string().max(assetsListResponseResultsItemItemNameMax),
  "description": zod.string().max(assetsListResponseResultsItemDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number(),
  "acquisition_date": zod.iso.date(),
  "acquisition_cost": zod.stringFormat('decimal', assetsListResponseResultsItemAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsListResponseResultsItemResidualRegExp).optional(),
  "vendor": zod.string().max(assetsListResponseResultsItemVendorMax).optional(),
  "asset_images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "asset": zod.number()
})),
  "created_by": zod.number().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})).optional()
})

export const assetsCreateBodyItemCodeMax = 255;

export const assetsCreateBodyItemNameMax = 255;

export const assetsCreateBodyDescriptionMax = 2000;

export const assetsCreateBodyAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsCreateBodyResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsCreateBodyVendorMax = 255;



export const AssetsCreateBody = zod.object({
  "assembly": zod.number(),
  "item_code": zod.string().max(assetsCreateBodyItemCodeMax).optional(),
  "item_name": zod.string().max(assetsCreateBodyItemNameMax),
  "description": zod.string().max(assetsCreateBodyDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number(),
  "acquisition_date": zod.iso.date(),
  "acquisition_cost": zod.stringFormat('decimal', assetsCreateBodyAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsCreateBodyResidualRegExp).optional(),
  "vendor": zod.string().max(assetsCreateBodyVendorMax).optional(),
  "asset_images": zod.array(zod.string()),
  "created_by": zod.number().nullish()
})

export const AssetsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Asset.')
})

export const assetsRetrieveResponseAssemblyCountryCodeMax = 3;

export const assetsRetrieveResponseAssemblyLanguageMax = 12;

export const assetsRetrieveResponseAssemblyCurrencyMax = 12;

export const assetsRetrieveResponseItemCodeMax = 255;

export const assetsRetrieveResponseItemNameMax = 255;

export const assetsRetrieveResponseDescriptionMax = 2000;

export const assetsRetrieveResponseAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsRetrieveResponseResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsRetrieveResponseVendorMax = 255;



export const AssetsRetrieveResponse = zod.object({
  "id": zod.number(),
  "assembly": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(assetsRetrieveResponseAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(assetsRetrieveResponseAssemblyLanguageMax).optional(),
  "currency": zod.string().max(assetsRetrieveResponseAssemblyCurrencyMax).optional()
}),
  "item_code": zod.string().max(assetsRetrieveResponseItemCodeMax).optional(),
  "item_name": zod.string().max(assetsRetrieveResponseItemNameMax),
  "description": zod.string().max(assetsRetrieveResponseDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number(),
  "acquisition_date": zod.iso.date(),
  "acquisition_cost": zod.stringFormat('decimal', assetsRetrieveResponseAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsRetrieveResponseResidualRegExp).optional(),
  "vendor": zod.string().max(assetsRetrieveResponseVendorMax).optional(),
  "asset_images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "asset": zod.number()
})),
  "created_by": zod.number().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const AssetsUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Asset.')
})

export const assetsUpdateBodyAssemblyCountryCodeMax = 3;

export const assetsUpdateBodyAssemblyLanguageMax = 12;

export const assetsUpdateBodyAssemblyCurrencyMax = 12;

export const assetsUpdateBodyItemCodeMax = 255;

export const assetsUpdateBodyItemNameMax = 255;

export const assetsUpdateBodyDescriptionMax = 2000;

export const assetsUpdateBodyAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsUpdateBodyResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsUpdateBodyVendorMax = 255;



export const AssetsUpdateBody = zod.object({
  "assembly": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(assetsUpdateBodyAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(assetsUpdateBodyAssemblyLanguageMax).optional(),
  "currency": zod.string().max(assetsUpdateBodyAssemblyCurrencyMax).optional()
}),
  "item_code": zod.string().max(assetsUpdateBodyItemCodeMax).optional(),
  "item_name": zod.string().max(assetsUpdateBodyItemNameMax),
  "description": zod.string().max(assetsUpdateBodyDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number(),
  "acquisition_date": zod.iso.date(),
  "acquisition_cost": zod.stringFormat('decimal', assetsUpdateBodyAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsUpdateBodyResidualRegExp).optional(),
  "vendor": zod.string().max(assetsUpdateBodyVendorMax).optional(),
  "created_by": zod.number().nullish()
})

export const assetsUpdateResponseAssemblyCountryCodeMax = 3;

export const assetsUpdateResponseAssemblyLanguageMax = 12;

export const assetsUpdateResponseAssemblyCurrencyMax = 12;

export const assetsUpdateResponseItemCodeMax = 255;

export const assetsUpdateResponseItemNameMax = 255;

export const assetsUpdateResponseDescriptionMax = 2000;

export const assetsUpdateResponseAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsUpdateResponseResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsUpdateResponseVendorMax = 255;



export const AssetsUpdateResponse = zod.object({
  "id": zod.number(),
  "assembly": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(assetsUpdateResponseAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(assetsUpdateResponseAssemblyLanguageMax).optional(),
  "currency": zod.string().max(assetsUpdateResponseAssemblyCurrencyMax).optional()
}),
  "item_code": zod.string().max(assetsUpdateResponseItemCodeMax).optional(),
  "item_name": zod.string().max(assetsUpdateResponseItemNameMax),
  "description": zod.string().max(assetsUpdateResponseDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number(),
  "acquisition_date": zod.iso.date(),
  "acquisition_cost": zod.stringFormat('decimal', assetsUpdateResponseAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsUpdateResponseResidualRegExp).optional(),
  "vendor": zod.string().max(assetsUpdateResponseVendorMax).optional(),
  "asset_images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "asset": zod.number()
})),
  "created_by": zod.number().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const AssetsPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Asset.')
})

export const assetsPartialUpdateBodyAssemblyCountryCodeMax = 3;

export const assetsPartialUpdateBodyAssemblyLanguageMax = 12;

export const assetsPartialUpdateBodyAssemblyCurrencyMax = 12;

export const assetsPartialUpdateBodyItemCodeMax = 255;

export const assetsPartialUpdateBodyItemNameMax = 255;

export const assetsPartialUpdateBodyDescriptionMax = 2000;

export const assetsPartialUpdateBodyAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsPartialUpdateBodyResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsPartialUpdateBodyVendorMax = 255;



export const AssetsPartialUpdateBody = zod.object({
  "assembly": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(assetsPartialUpdateBodyAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(assetsPartialUpdateBodyAssemblyLanguageMax).optional(),
  "currency": zod.string().max(assetsPartialUpdateBodyAssemblyCurrencyMax).optional()
}).optional(),
  "item_code": zod.string().max(assetsPartialUpdateBodyItemCodeMax).optional(),
  "item_name": zod.string().max(assetsPartialUpdateBodyItemNameMax).optional(),
  "description": zod.string().max(assetsPartialUpdateBodyDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).optional().describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).optional().describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number().optional(),
  "acquisition_date": zod.iso.date().optional(),
  "acquisition_cost": zod.stringFormat('decimal', assetsPartialUpdateBodyAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsPartialUpdateBodyResidualRegExp).optional(),
  "vendor": zod.string().max(assetsPartialUpdateBodyVendorMax).optional(),
  "created_by": zod.number().nullish()
})

export const assetsPartialUpdateResponseAssemblyCountryCodeMax = 3;

export const assetsPartialUpdateResponseAssemblyLanguageMax = 12;

export const assetsPartialUpdateResponseAssemblyCurrencyMax = 12;

export const assetsPartialUpdateResponseItemCodeMax = 255;

export const assetsPartialUpdateResponseItemNameMax = 255;

export const assetsPartialUpdateResponseDescriptionMax = 2000;

export const assetsPartialUpdateResponseAcquisitionCostRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsPartialUpdateResponseResidualRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const assetsPartialUpdateResponseVendorMax = 255;



export const AssetsPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "assembly": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(assetsPartialUpdateResponseAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(assetsPartialUpdateResponseAssemblyLanguageMax).optional(),
  "currency": zod.string().max(assetsPartialUpdateResponseAssemblyCurrencyMax).optional()
}),
  "item_code": zod.string().max(assetsPartialUpdateResponseItemCodeMax).optional(),
  "item_name": zod.string().max(assetsPartialUpdateResponseItemNameMax),
  "description": zod.string().max(assetsPartialUpdateResponseDescriptionMax).optional(),
  "condition": zod.enum(['New', 'Good', 'Fair', 'Old', 'Not Working']).describe('\* `New` - New\n\* `Good` - Good\n\* `Fair` - Fair\n\* `Old` - Old\n\* `Not Working` - Not Working'),
  "asset_type": zod.enum(['Building', 'Instrument', 'Vehicle', 'Furniture', 'Electronics', 'Machinery', 'Software', 'Land', 'Other']).describe('\* `Building` - Building\n\* `Instrument` - Instrument\n\* `Vehicle` - Vehicle\n\* `Furniture` - Furniture\n\* `Electronics` - Electronics\n\* `Machinery` - Machinery\n\* `Software` - Software\n\* `Land` - Land\n\* `Other` - Other'),
  "units": zod.number(),
  "acquisition_date": zod.iso.date(),
  "acquisition_cost": zod.stringFormat('decimal', assetsPartialUpdateResponseAcquisitionCostRegExp).optional(),
  "residual": zod.stringFormat('decimal', assetsPartialUpdateResponseResidualRegExp).optional(),
  "vendor": zod.string().max(assetsPartialUpdateResponseVendorMax).optional(),
  "asset_images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "asset": zod.number()
})),
  "created_by": zod.number().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const AssetsDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Asset.')
})

