/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const attendanceListResponseSpecialEventNameMax = 255;

export const attendanceListResponsePreacherMax = 255;



export const AttendanceListResponseItem = zod.object({
  "id": zod.number(),
  "headcount": zod.number(),
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendanceListResponseSpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendanceListResponsePreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "total_adults": zod.number().optional(),
  "total_visitors": zod.number().optional(),
  "total_new_converts": zod.number().optional(),
  "total_altar_call": zod.number().optional(),
  "total_baptisms": zod.number().optional(),
  "legacy": zod.object({
    "adults": zod.number().optional(),
    "guest_attendance": zod.number().optional(),
    "new_converts": zod.number().optional(),
    "altar_call": zod.number().optional(),
    "baptisms": zod.number().optional(),
  }).optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullable(),
  "homecell": zod.number().nullish()
})
export const AttendanceListResponse = zod.array(AttendanceListResponseItem)

export const attendanceCreateBodySpecialEventNameMax = 255;

export const attendanceCreateBodyPreacherMax = 255;



export const AttendanceCreateBody = zod.object({
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendanceCreateBodySpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendanceCreateBodyPreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "men": zod.number().optional(),
  "women": zod.number().optional(),
  "visitor_men": zod.number().optional(),
  "visitor_women": zod.number().optional(),
  "new_convert_men": zod.number().optional(),
  "new_convert_women": zod.number().optional(),
  "altar_call_men": zod.number().optional(),
  "altar_call_women": zod.number().optional(),
  "baptism_men": zod.number().optional(),
  "baptism_women": zod.number().optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date(),
  "homecell": zod.number().nullish()
})

export const AttendanceRetrieveParams = zod.object({
  "id": zod.string()
})

export const attendanceRetrieveResponseSpecialEventNameMax = 255;

export const attendanceRetrieveResponsePreacherMax = 255;



export const AttendanceRetrieveResponse = zod.object({
  "id": zod.number(),
  "headcount": zod.number(),
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendanceRetrieveResponseSpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendanceRetrieveResponsePreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "total_adults": zod.number().optional(),
  "total_visitors": zod.number().optional(),
  "total_new_converts": zod.number().optional(),
  "total_altar_call": zod.number().optional(),
  "total_baptisms": zod.number().optional(),
  "legacy": zod.object({
    "adults": zod.number().optional(),
    "guest_attendance": zod.number().optional(),
    "new_converts": zod.number().optional(),
    "altar_call": zod.number().optional(),
    "baptisms": zod.number().optional(),
  }).optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullable(),
  "homecell": zod.number().nullish()
})

export const AttendanceUpdateParams = zod.object({
  "id": zod.string()
})

export const attendanceUpdateBodySpecialEventNameMax = 255;

export const attendanceUpdateBodyPreacherMax = 255;



export const AttendanceUpdateBody = zod.object({
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendanceUpdateBodySpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendanceUpdateBodyPreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "men": zod.number().optional(),
  "women": zod.number().optional(),
  "visitor_men": zod.number().optional(),
  "visitor_women": zod.number().optional(),
  "new_convert_men": zod.number().optional(),
  "new_convert_women": zod.number().optional(),
  "altar_call_men": zod.number().optional(),
  "altar_call_women": zod.number().optional(),
  "baptism_men": zod.number().optional(),
  "baptism_women": zod.number().optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date(),
  "homecell": zod.number().nullish()
})

export const attendanceUpdateResponseSpecialEventNameMax = 255;

export const attendanceUpdateResponsePreacherMax = 255;



export const AttendanceUpdateResponse = zod.object({
  "id": zod.number(),
  "headcount": zod.number(),
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendanceUpdateResponseSpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendanceUpdateResponsePreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "total_adults": zod.number().optional(),
  "total_visitors": zod.number().optional(),
  "total_new_converts": zod.number().optional(),
  "total_altar_call": zod.number().optional(),
  "total_baptisms": zod.number().optional(),
  "legacy": zod.object({
    "adults": zod.number().optional(),
    "guest_attendance": zod.number().optional(),
    "new_converts": zod.number().optional(),
    "altar_call": zod.number().optional(),
    "baptisms": zod.number().optional(),
  }).optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullable(),
  "homecell": zod.number().nullish()
})

export const AttendancePartialUpdateParams = zod.object({
  "id": zod.string()
})

export const attendancePartialUpdateBodySpecialEventNameMax = 255;

export const attendancePartialUpdateBodyPreacherMax = 255;



export const AttendancePartialUpdateBody = zod.object({
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendancePartialUpdateBodySpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendancePartialUpdateBodyPreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "men": zod.number().optional(),
  "women": zod.number().optional(),
  "visitor_men": zod.number().optional(),
  "visitor_women": zod.number().optional(),
  "new_convert_men": zod.number().optional(),
  "new_convert_women": zod.number().optional(),
  "altar_call_men": zod.number().optional(),
  "altar_call_women": zod.number().optional(),
  "baptism_men": zod.number().optional(),
  "baptism_women": zod.number().optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date().optional(),
  "homecell": zod.number().nullish()
})

export const attendancePartialUpdateResponseSpecialEventNameMax = 255;

export const attendancePartialUpdateResponsePreacherMax = 255;



export const AttendancePartialUpdateResponse = zod.object({
  "id": zod.number(),
  "headcount": zod.number(),
  "service_type": zod.enum(['friday', 'homecell', 'outreach', 'other', 'sunday']).optional().describe('\* `friday` - Friday\n\* `homecell` - Homecell\n\* `outreach` - Outreach\n\* `other` - Other\n\* `sunday` - Sunday'),
  "is_special_event": zod.boolean().optional(),
  "special_event_name": zod.string().max(attendancePartialUpdateResponseSpecialEventNameMax).optional(),
  "weather": zod.union([zod.enum(['sunny', 'partly_cloudy', 'cloudy', 'windy', 'light_rain', 'heavy_rain', 'storm', 'very_hot', 'cold', 'extreme']).describe('\* `sunny` - Sunny\n\* `partly_cloudy` - Partly Cloudy\n\* `cloudy` - Cloudy\n\* `windy` - Windy\n\* `light_rain` - Light Rain\n\* `heavy_rain` - Heavy Rain\n\* `storm` - Storm\n\* `very_hot` - Very Hot\n\* `cold` - Cold\n\* `extreme` - Extreme Weather'),zod.enum(['']),zod.literal(null)]).nullish(),
  "preacher": zod.string().max(attendancePartialUpdateResponsePreacherMax).optional(),
  "sermon": zod.string().optional(),
  "scriptures": zod.string().optional(),
  "notes": zod.string().optional(),
  "total_adults": zod.number().optional(),
  "total_visitors": zod.number().optional(),
  "total_new_converts": zod.number().optional(),
  "total_altar_call": zod.number().optional(),
  "total_baptisms": zod.number().optional(),
  "legacy": zod.object({
    "adults": zod.number().optional(),
    "guest_attendance": zod.number().optional(),
    "new_converts": zod.number().optional(),
    "altar_call": zod.number().optional(),
    "baptisms": zod.number().optional(),
  }).optional(),
  "online_viewers": zod.number().optional(),
  "volunteers_on_duty": zod.number().optional(),
  "total_leaders_present": zod.number().optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullable(),
  "homecell": zod.number().nullish()
})

export const AttendanceDestroyParams = zod.object({
  "id": zod.string()
})
