/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const AuditLogsListQueryParams = zod.object({
  "action": zod.enum(['CREATE', 'DELETE', 'UPDATE']).optional().describe('\* `CREATE` - Create\n\* `UPDATE` - Update\n\* `DELETE` - Delete'),
  "content_type": zod.number().optional(),
  "ordering": zod.string().optional().describe('Which field to use when ordering the results.'),
  "search": zod.string().optional().describe('A search term.'),
  "user": zod.number().optional()
})

export const AuditLogsListResponseItem = zod.object({
  "id": zod.number(),
  "user": zod.number().nullable(),
  "user_name": zod.string(),
  "user_email": zod.email(),
  "model": zod.string(),
  "object_id": zod.number(),
  "action": zod.enum(['CREATE', 'UPDATE', 'DELETE']).describe('\* `CREATE` - Create\n\* `UPDATE` - Update\n\* `DELETE` - Delete'),
  "old_data": zod.unknown().nullable(),
  "new_data": zod.unknown().nullable(),
  "timestamp": zod.iso.datetime({})
})
export const AuditLogsListResponse = zod.array(AuditLogsListResponseItem)

export const AuditLogsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this audit log.')
})

export const AuditLogsRetrieveResponse = zod.object({
  "id": zod.number(),
  "user": zod.number().nullable(),
  "user_name": zod.string(),
  "user_email": zod.email(),
  "model": zod.string(),
  "object_id": zod.number(),
  "action": zod.enum(['CREATE', 'UPDATE', 'DELETE']).describe('\* `CREATE` - Create\n\* `UPDATE` - Update\n\* `DELETE` - Delete'),
  "old_data": zod.unknown().nullable(),
  "new_data": zod.unknown().nullable(),
  "timestamp": zod.iso.datetime({})
})

