/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const changelogListResponseAuthorFirstNameMax = 255;

export const changelogListResponseAuthorLastNameMax = 255;

export const changelogListResponseTitleMax = 255;

export const changelogListResponseSlugMax = 255;


export const changelogListResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogListResponseItem = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(changelogListResponseAuthorFirstNameMax),
  "last_name": zod.string().max(changelogListResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional()
}),
  "title": zod.string().max(changelogListResponseTitleMax),
  "description": zod.string(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogListResponseSlugMax).regex(changelogListResponseSlugRegExp).optional(),
  "is_draft": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const ChangelogListResponse = zod.array(ChangelogListResponseItem)

export const changelogCreateBodyTitleMax = 255;

export const changelogCreateBodySlugMax = 255;


export const changelogCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogCreateBody = zod.object({
  "title": zod.string().max(changelogCreateBodyTitleMax),
  "description": zod.string(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogCreateBodySlugMax).regex(changelogCreateBodySlugRegExp).optional(),
  "is_draft": zod.boolean().optional(),
  "author": zod.number(),
  "read_by": zod.array(zod.number()).optional()
})

export const ChangelogRetrieveParams = zod.object({
  "slug": zod.string()
})

export const changelogRetrieveResponseAuthorFirstNameMax = 255;

export const changelogRetrieveResponseAuthorLastNameMax = 255;

export const changelogRetrieveResponseTitleMax = 255;

export const changelogRetrieveResponseSlugMax = 255;


export const changelogRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogRetrieveResponse = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(changelogRetrieveResponseAuthorFirstNameMax),
  "last_name": zod.string().max(changelogRetrieveResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional()
}),
  "title": zod.string().max(changelogRetrieveResponseTitleMax),
  "description": zod.string(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogRetrieveResponseSlugMax).regex(changelogRetrieveResponseSlugRegExp).optional(),
  "is_draft": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const ChangelogUpdateParams = zod.object({
  "slug": zod.string()
})

export const changelogUpdateBodyAuthorFirstNameMax = 255;

export const changelogUpdateBodyAuthorLastNameMax = 255;

export const changelogUpdateBodyTitleMax = 255;

export const changelogUpdateBodySlugMax = 255;


export const changelogUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogUpdateBody = zod.object({
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(changelogUpdateBodyAuthorFirstNameMax),
  "last_name": zod.string().max(changelogUpdateBodyAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional()
}),
  "title": zod.string().max(changelogUpdateBodyTitleMax),
  "description": zod.string(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogUpdateBodySlugMax).regex(changelogUpdateBodySlugRegExp).optional(),
  "is_draft": zod.boolean().optional()
})

export const changelogUpdateResponseAuthorFirstNameMax = 255;

export const changelogUpdateResponseAuthorLastNameMax = 255;

export const changelogUpdateResponseTitleMax = 255;

export const changelogUpdateResponseSlugMax = 255;


export const changelogUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogUpdateResponse = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(changelogUpdateResponseAuthorFirstNameMax),
  "last_name": zod.string().max(changelogUpdateResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional()
}),
  "title": zod.string().max(changelogUpdateResponseTitleMax),
  "description": zod.string(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogUpdateResponseSlugMax).regex(changelogUpdateResponseSlugRegExp).optional(),
  "is_draft": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const ChangelogPartialUpdateParams = zod.object({
  "slug": zod.string()
})

export const changelogPartialUpdateBodyAuthorFirstNameMax = 255;

export const changelogPartialUpdateBodyAuthorLastNameMax = 255;

export const changelogPartialUpdateBodyTitleMax = 255;

export const changelogPartialUpdateBodySlugMax = 255;


export const changelogPartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogPartialUpdateBody = zod.object({
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(changelogPartialUpdateBodyAuthorFirstNameMax),
  "last_name": zod.string().max(changelogPartialUpdateBodyAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional()
}).optional(),
  "title": zod.string().max(changelogPartialUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogPartialUpdateBodySlugMax).regex(changelogPartialUpdateBodySlugRegExp).optional(),
  "is_draft": zod.boolean().optional()
})

export const changelogPartialUpdateResponseAuthorFirstNameMax = 255;

export const changelogPartialUpdateResponseAuthorLastNameMax = 255;

export const changelogPartialUpdateResponseTitleMax = 255;

export const changelogPartialUpdateResponseSlugMax = 255;


export const changelogPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const ChangelogPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(changelogPartialUpdateResponseAuthorFirstNameMax),
  "last_name": zod.string().max(changelogPartialUpdateResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional()
}),
  "title": zod.string().max(changelogPartialUpdateResponseTitleMax),
  "description": zod.string(),
  "category": zod.enum(['Attendance', 'Authentication', 'Changelog', 'Demographics', 'Finance', 'General', 'Strategy', 'Templates', 'Updates']).optional().describe('\* `Attendance` - Attendance\n\* `Authentication` - Authentication\n\* `Changelog` - Changelog\n\* `Demographics` - Demographics\n\* `Finance` - Finance\n\* `General` - General\n\* `Strategy` - Strategy\n\* `Templates` - Templates\n\* `Updates` - Updates'),
  "image": zod.url().nullish(),
  "views": zod.number().optional(),
  "slug": zod.string().max(changelogPartialUpdateResponseSlugMax).regex(changelogPartialUpdateResponseSlugRegExp).optional(),
  "is_draft": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const ChangelogDestroyParams = zod.object({
  "slug": zod.string()
})

