/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const ChurchStrategyRetrieve2Params = zod.object({
  "id": zod.number().describe('A unique integer value identifying this strategy.')
})

export const ChurchStrategyUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this strategy.')
})

export const ChurchStrategyPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this strategy.')
})

export const ChurchStrategyDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this strategy.')
})

