/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const DocumentsListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const documentsListResponseResultsItemTitleMax = 255;

export const documentsListResponseResultsItemSlugMax = 255;


export const documentsListResponseResultsItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsListResponseResultsItemDocumentThumbnailFallbackMax = 255;



export const DocumentsListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentsListResponseResultsItemTitleMax),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsListResponseResultsItemSlugMax).regex(documentsListResponseResultsItemSlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsListResponseResultsItemDocumentThumbnailFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})).optional()
})

export const documentsCreateBodyTitleMax = 255;

export const documentsCreateBodySlugMax = 255;


export const documentsCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsCreateBodyDocumentThumbnailFallbackMax = 255;



export const DocumentsCreateBody = zod.object({
  "title": zod.string().max(documentsCreateBodyTitleMax),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsCreateBodySlugMax).regex(documentsCreateBodySlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsCreateBodyDocumentThumbnailFallbackMax).optional(),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})

export const DocumentsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Circular.')
})

export const documentsRetrieveResponseTitleMax = 255;

export const documentsRetrieveResponseSlugMax = 255;


export const documentsRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsRetrieveResponseDocumentThumbnailFallbackMax = 255;



export const DocumentsRetrieveResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentsRetrieveResponseTitleMax),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsRetrieveResponseSlugMax).regex(documentsRetrieveResponseSlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsRetrieveResponseDocumentThumbnailFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})

export const DocumentsUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Circular.')
})

export const documentsUpdateBodyTitleMax = 255;

export const documentsUpdateBodySlugMax = 255;


export const documentsUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsUpdateBodyDocumentThumbnailFallbackMax = 255;



export const DocumentsUpdateBody = zod.object({
  "title": zod.string().max(documentsUpdateBodyTitleMax),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsUpdateBodySlugMax).regex(documentsUpdateBodySlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsUpdateBodyDocumentThumbnailFallbackMax).optional(),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})

export const documentsUpdateResponseTitleMax = 255;

export const documentsUpdateResponseSlugMax = 255;


export const documentsUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsUpdateResponseDocumentThumbnailFallbackMax = 255;



export const DocumentsUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentsUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsUpdateResponseSlugMax).regex(documentsUpdateResponseSlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsUpdateResponseDocumentThumbnailFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})

export const DocumentsPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Circular.')
})

export const documentsPartialUpdateBodyTitleMax = 255;

export const documentsPartialUpdateBodySlugMax = 255;


export const documentsPartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsPartialUpdateBodyDocumentThumbnailFallbackMax = 255;



export const DocumentsPartialUpdateBody = zod.object({
  "title": zod.string().max(documentsPartialUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsPartialUpdateBodySlugMax).regex(documentsPartialUpdateBodySlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsPartialUpdateBodyDocumentThumbnailFallbackMax).optional(),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})

export const documentsPartialUpdateResponseTitleMax = 255;

export const documentsPartialUpdateResponseSlugMax = 255;


export const documentsPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const documentsPartialUpdateResponseDocumentThumbnailFallbackMax = 255;



export const DocumentsPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentsPartialUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "slug": zod.string().max(documentsPartialUpdateResponseSlugMax).regex(documentsPartialUpdateResponseSlugRegExp).optional(),
  "document_thumbnail_fallback": zod.string().max(documentsPartialUpdateResponseDocumentThumbnailFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "uploaded_document": zod.url().nullish(),
  "category": zod.union([zod.enum(['president', 'general', 'national', 'secretary']).describe('\* `president` - President Circular\n\* `general` - General Overseer Circular\n\* `national` - National Overseer Circular\n\* `secretary` - Secretary General Circular'),zod.enum([''])]).optional(),
  "created_by": zod.number().nullish()
})

export const DocumentsDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Circular.')
})

