/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const documentationListResponseTitleMax = 255;



export const DocumentationListResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentationListResponseTitleMax),
  "body": zod.string(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived'),
  "author": zod.number(),
  "author_name": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const DocumentationListResponse = zod.array(DocumentationListResponseItem)

export const documentationCreateBodyTitleMax = 255;



export const DocumentationCreateBody = zod.object({
  "title": zod.string().max(documentationCreateBodyTitleMax),
  "body": zod.string(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived')
})

export const DocumentationRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Documentation.')
})

export const documentationRetrieveResponseTitleMax = 255;



export const DocumentationRetrieveResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentationRetrieveResponseTitleMax),
  "body": zod.string(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived'),
  "author": zod.number(),
  "author_name": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const DocumentationUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Documentation.')
})

export const documentationUpdateBodyTitleMax = 255;



export const DocumentationUpdateBody = zod.object({
  "title": zod.string().max(documentationUpdateBodyTitleMax),
  "body": zod.string(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived')
})

export const documentationUpdateResponseTitleMax = 255;



export const DocumentationUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentationUpdateResponseTitleMax),
  "body": zod.string(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived'),
  "author": zod.number(),
  "author_name": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const DocumentationPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Documentation.')
})

export const documentationPartialUpdateBodyTitleMax = 255;



export const DocumentationPartialUpdateBody = zod.object({
  "title": zod.string().max(documentationPartialUpdateBodyTitleMax).optional(),
  "body": zod.string().optional(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived')
})

export const documentationPartialUpdateResponseTitleMax = 255;



export const DocumentationPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(documentationPartialUpdateResponseTitleMax),
  "body": zod.string(),
  "category": zod.enum(['General', 'API', 'User Guide', 'Technical']).optional().describe('\* `General` - General\n\* `API` - API\n\* `User Guide` - User Guide\n\* `Technical` - Technical'),
  "status": zod.enum(['draft', 'published', 'archived']).optional().describe('\* `draft` - Draft\n\* `published` - Published\n\* `archived` - Archived'),
  "author": zod.number(),
  "author_name": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const DocumentationDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Documentation.')
})

