/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const ExpenditureListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const expenditureListResponseResultsItemInvoiceNumberMax = 255;

export const expenditureListResponseResultsItemNameMax = 255;

export const expenditureListResponseResultsItemSupplierMax = 255;

export const expenditureListResponseResultsItemPriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const expenditureListResponseResultsItemTotalRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditureListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "invoice_number": zod.string().max(expenditureListResponseResultsItemInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date(),
  "name": zod.string().max(expenditureListResponseResultsItemNameMax),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditureListResponseResultsItemSupplierMax).optional(),
  "quantity": zod.number(),
  "price": zod.stringFormat('decimal', expenditureListResponseResultsItemPriceRegExp),
  "total": zod.stringFormat('decimal', expenditureListResponseResultsItemTotalRegExp),
  "receipt": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})).optional()
})

export const expenditureCreateBodyInvoiceNumberMax = 255;

export const expenditureCreateBodyNameMax = 255;

export const expenditureCreateBodySupplierMax = 255;

export const expenditureCreateBodyPriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditureCreateBody = zod.object({
  "invoice_number": zod.string().max(expenditureCreateBodyInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date(),
  "name": zod.string().max(expenditureCreateBodyNameMax),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditureCreateBodySupplierMax).optional(),
  "quantity": zod.number(),
  "price": zod.stringFormat('decimal', expenditureCreateBodyPriceRegExp),
  "receipt": zod.url().nullish(),
  "assembly": zod.number(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const ExpenditureRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Expenditure.')
})

export const expenditureRetrieveResponseInvoiceNumberMax = 255;

export const expenditureRetrieveResponseNameMax = 255;

export const expenditureRetrieveResponseSupplierMax = 255;

export const expenditureRetrieveResponsePriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const expenditureRetrieveResponseTotalRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditureRetrieveResponse = zod.object({
  "id": zod.number(),
  "invoice_number": zod.string().max(expenditureRetrieveResponseInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date(),
  "name": zod.string().max(expenditureRetrieveResponseNameMax),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditureRetrieveResponseSupplierMax).optional(),
  "quantity": zod.number(),
  "price": zod.stringFormat('decimal', expenditureRetrieveResponsePriceRegExp),
  "total": zod.stringFormat('decimal', expenditureRetrieveResponseTotalRegExp),
  "receipt": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const ExpenditureUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Expenditure.')
})

export const expenditureUpdateBodyInvoiceNumberMax = 255;

export const expenditureUpdateBodyNameMax = 255;

export const expenditureUpdateBodySupplierMax = 255;

export const expenditureUpdateBodyPriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditureUpdateBody = zod.object({
  "invoice_number": zod.string().max(expenditureUpdateBodyInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date(),
  "name": zod.string().max(expenditureUpdateBodyNameMax),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditureUpdateBodySupplierMax).optional(),
  "quantity": zod.number(),
  "price": zod.stringFormat('decimal', expenditureUpdateBodyPriceRegExp),
  "receipt": zod.url().nullish(),
  "assembly": zod.number(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const expenditureUpdateResponseInvoiceNumberMax = 255;

export const expenditureUpdateResponseNameMax = 255;

export const expenditureUpdateResponseSupplierMax = 255;

export const expenditureUpdateResponsePriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const expenditureUpdateResponseTotalRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditureUpdateResponse = zod.object({
  "id": zod.number(),
  "invoice_number": zod.string().max(expenditureUpdateResponseInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date(),
  "name": zod.string().max(expenditureUpdateResponseNameMax),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditureUpdateResponseSupplierMax).optional(),
  "quantity": zod.number(),
  "price": zod.stringFormat('decimal', expenditureUpdateResponsePriceRegExp),
  "total": zod.stringFormat('decimal', expenditureUpdateResponseTotalRegExp),
  "receipt": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const ExpenditurePartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Expenditure.')
})

export const expenditurePartialUpdateBodyInvoiceNumberMax = 255;

export const expenditurePartialUpdateBodyNameMax = 255;

export const expenditurePartialUpdateBodySupplierMax = 255;

export const expenditurePartialUpdateBodyPriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditurePartialUpdateBody = zod.object({
  "invoice_number": zod.string().max(expenditurePartialUpdateBodyInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date().optional(),
  "name": zod.string().max(expenditurePartialUpdateBodyNameMax).optional(),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).optional().describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditurePartialUpdateBodySupplierMax).optional(),
  "quantity": zod.number().optional(),
  "price": zod.stringFormat('decimal', expenditurePartialUpdateBodyPriceRegExp).optional(),
  "receipt": zod.url().nullish(),
  "assembly": zod.number().optional(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const expenditurePartialUpdateResponseInvoiceNumberMax = 255;

export const expenditurePartialUpdateResponseNameMax = 255;

export const expenditurePartialUpdateResponseSupplierMax = 255;

export const expenditurePartialUpdateResponsePriceRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const expenditurePartialUpdateResponseTotalRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const ExpenditurePartialUpdateResponse = zod.object({
  "id": zod.number(),
  "invoice_number": zod.string().max(expenditurePartialUpdateResponseInvoiceNumberMax).optional(),
  "invoice_date": zod.iso.date(),
  "name": zod.string().max(expenditurePartialUpdateResponseNameMax),
  "description": zod.string().optional(),
  "category": zod.enum(['amenities', 'conference', 'decor', 'fellowship', 'hotel bookings', 'humanitarian', 'office', 'other', 'outreach', 'repair', 'travel', 'wages']).describe('\* `amenities` - Amenities\n\* `conference` - Conference\n\* `decor` - Decor\n\* `fellowship` - Fellowship\n\* `hotel bookings` - Hotel Bookings\n\* `humanitarian` - Humanitarian\n\* `office` - Office\n\* `other` - Other\n\* `outreach` - Outreach\n\* `repair` - Repair\n\* `travel` - Travel\n\* `wages` - Wages'),
  "supplier": zod.string().max(expenditurePartialUpdateResponseSupplierMax).optional(),
  "quantity": zod.number(),
  "price": zod.stringFormat('decimal', expenditurePartialUpdateResponsePriceRegExp),
  "total": zod.stringFormat('decimal', expenditurePartialUpdateResponseTotalRegExp),
  "receipt": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "report": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const ExpenditureDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Expenditure.')
})

