/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const IncomeListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const incomeListResponseResultsItemChurchCountryCodeMax = 3;

export const incomeListResponseResultsItemChurchLanguageMax = 12;

export const incomeListResponseResultsItemChurchCurrencyMax = 12;

export const incomeListResponseResultsItemOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeListResponseResultsItemFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeListResponseResultsItemThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeListResponseResultsItemDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeListResponseResultsItemTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomeListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "church": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(incomeListResponseResultsItemChurchCountryCodeMax).optional(),
  "language": zod.string().max(incomeListResponseResultsItemChurchLanguageMax).optional(),
  "currency": zod.string().max(incomeListResponseResultsItemChurchCurrencyMax).optional()
}),
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomeListResponseResultsItemOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomeListResponseResultsItemFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomeListResponseResultsItemThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomeListResponseResultsItemDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomeListResponseResultsItemTotalIncomeRegExp).optional(),
  "statement": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})).optional()
})

export const incomeCreateBodyOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeCreateBodyFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeCreateBodyThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeCreateBodyDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeCreateBodyTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomeCreateBody = zod.object({
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomeCreateBodyOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomeCreateBodyFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomeCreateBodyThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomeCreateBodyDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomeCreateBodyTotalIncomeRegExp).optional(),
  "notes": zod.string().optional(),
  "statement": zod.url().nullish(),
  "church": zod.number(),
  "report": zod.number().nullish()
})

export const IncomeRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this income.')
})

export const incomeRetrieveResponseChurchCountryCodeMax = 3;

export const incomeRetrieveResponseChurchLanguageMax = 12;

export const incomeRetrieveResponseChurchCurrencyMax = 12;

export const incomeRetrieveResponseOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeRetrieveResponseFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeRetrieveResponseThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeRetrieveResponseDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeRetrieveResponseTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomeRetrieveResponse = zod.object({
  "id": zod.number(),
  "church": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(incomeRetrieveResponseChurchCountryCodeMax).optional(),
  "language": zod.string().max(incomeRetrieveResponseChurchLanguageMax).optional(),
  "currency": zod.string().max(incomeRetrieveResponseChurchCurrencyMax).optional()
}),
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomeRetrieveResponseOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomeRetrieveResponseFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomeRetrieveResponseThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomeRetrieveResponseDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomeRetrieveResponseTotalIncomeRegExp).optional(),
  "statement": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const IncomeUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this income.')
})

export const incomeUpdateBodyChurchCountryCodeMax = 3;

export const incomeUpdateBodyChurchLanguageMax = 12;

export const incomeUpdateBodyChurchCurrencyMax = 12;

export const incomeUpdateBodyOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateBodyFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateBodyThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateBodyDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateBodyTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomeUpdateBody = zod.object({
  "church": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(incomeUpdateBodyChurchCountryCodeMax).optional(),
  "language": zod.string().max(incomeUpdateBodyChurchLanguageMax).optional(),
  "currency": zod.string().max(incomeUpdateBodyChurchCurrencyMax).optional()
}),
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomeUpdateBodyOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomeUpdateBodyFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomeUpdateBodyThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomeUpdateBodyDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomeUpdateBodyTotalIncomeRegExp).optional(),
  "statement": zod.url().nullish()
})

export const incomeUpdateResponseChurchCountryCodeMax = 3;

export const incomeUpdateResponseChurchLanguageMax = 12;

export const incomeUpdateResponseChurchCurrencyMax = 12;

export const incomeUpdateResponseOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateResponseFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateResponseThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateResponseDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomeUpdateResponseTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomeUpdateResponse = zod.object({
  "id": zod.number(),
  "church": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(incomeUpdateResponseChurchCountryCodeMax).optional(),
  "language": zod.string().max(incomeUpdateResponseChurchLanguageMax).optional(),
  "currency": zod.string().max(incomeUpdateResponseChurchCurrencyMax).optional()
}),
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomeUpdateResponseOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomeUpdateResponseFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomeUpdateResponseThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomeUpdateResponseDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomeUpdateResponseTotalIncomeRegExp).optional(),
  "statement": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const IncomePartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this income.')
})

export const incomePartialUpdateBodyChurchCountryCodeMax = 3;

export const incomePartialUpdateBodyChurchLanguageMax = 12;

export const incomePartialUpdateBodyChurchCurrencyMax = 12;

export const incomePartialUpdateBodyOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateBodyFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateBodyThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateBodyDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateBodyTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomePartialUpdateBody = zod.object({
  "church": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(incomePartialUpdateBodyChurchCountryCodeMax).optional(),
  "language": zod.string().max(incomePartialUpdateBodyChurchLanguageMax).optional(),
  "currency": zod.string().max(incomePartialUpdateBodyChurchCurrencyMax).optional()
}).optional(),
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomePartialUpdateBodyOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomePartialUpdateBodyFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomePartialUpdateBodyThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomePartialUpdateBodyDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomePartialUpdateBodyTotalIncomeRegExp).optional(),
  "statement": zod.url().nullish()
})

export const incomePartialUpdateResponseChurchCountryCodeMax = 3;

export const incomePartialUpdateResponseChurchLanguageMax = 12;

export const incomePartialUpdateResponseChurchCurrencyMax = 12;

export const incomePartialUpdateResponseOfferingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateResponseFundraisingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateResponseThanksgivingRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateResponseDonationsRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');
export const incomePartialUpdateResponseTotalIncomeRegExp = new RegExp('^-?\\d{0,8}(?:\\.\\d{0,2})?$');


export const IncomePartialUpdateResponse = zod.object({
  "id": zod.number(),
  "church": zod.object({
  "id": zod.number(),
  "country_code": zod.string().max(incomePartialUpdateResponseChurchCountryCodeMax).optional(),
  "language": zod.string().max(incomePartialUpdateResponseChurchLanguageMax).optional(),
  "currency": zod.string().max(incomePartialUpdateResponseChurchCurrencyMax).optional()
}),
  "timestamp": zod.iso.date().nullish(),
  "offering": zod.stringFormat('decimal', incomePartialUpdateResponseOfferingRegExp).optional(),
  "fundraising": zod.stringFormat('decimal', incomePartialUpdateResponseFundraisingRegExp).optional(),
  "thanksgiving": zod.stringFormat('decimal', incomePartialUpdateResponseThanksgivingRegExp).optional(),
  "donations": zod.stringFormat('decimal', incomePartialUpdateResponseDonationsRegExp).optional(),
  "total_income": zod.stringFormat('decimal', incomePartialUpdateResponseTotalIncomeRegExp).optional(),
  "statement": zod.url().nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const IncomeDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this income.')
})

