/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const integrationsListResponseIntegrationIdMax = 32;

export const integrationsListResponseIntegrationProviderOneNameMax = 100;



export const IntegrationsListResponseItem = zod.object({
  "id": zod.number(),
  "integration_id": zod.string().max(integrationsListResponseIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider": zod.object({
  "id": zod.number(),
  "name": zod.string().max(integrationsListResponseIntegrationProviderOneNameMax).describe('Name of the external system (e.g. LMS, HR System)'),
  "description": zod.string().optional().describe('Optional description of the system'),
  "is_active": zod.boolean().optional().describe('Toggle to disable use of the system'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const IntegrationsListResponse = zod.array(IntegrationsListResponseItem)

export const integrationsCreateBodyIntegrationIdMax = 32;



export const IntegrationsCreateBody = zod.object({
  "integration_id": zod.string().max(integrationsCreateBodyIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider')
})

export const IntegrationsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Integration.')
})

export const integrationsRetrieveResponseIntegrationIdMax = 32;

export const integrationsRetrieveResponseIntegrationProviderOneNameMax = 100;



export const IntegrationsRetrieveResponse = zod.object({
  "id": zod.number(),
  "integration_id": zod.string().max(integrationsRetrieveResponseIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider": zod.object({
  "id": zod.number(),
  "name": zod.string().max(integrationsRetrieveResponseIntegrationProviderOneNameMax).describe('Name of the external system (e.g. LMS, HR System)'),
  "description": zod.string().optional().describe('Optional description of the system'),
  "is_active": zod.boolean().optional().describe('Toggle to disable use of the system'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const IntegrationsUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Integration.')
})

export const integrationsUpdateBodyIntegrationIdMax = 32;



export const IntegrationsUpdateBody = zod.object({
  "integration_id": zod.string().max(integrationsUpdateBodyIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider')
})

export const integrationsUpdateResponseIntegrationIdMax = 32;

export const integrationsUpdateResponseIntegrationProviderOneNameMax = 100;



export const IntegrationsUpdateResponse = zod.object({
  "id": zod.number(),
  "integration_id": zod.string().max(integrationsUpdateResponseIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider": zod.object({
  "id": zod.number(),
  "name": zod.string().max(integrationsUpdateResponseIntegrationProviderOneNameMax).describe('Name of the external system (e.g. LMS, HR System)'),
  "description": zod.string().optional().describe('Optional description of the system'),
  "is_active": zod.boolean().optional().describe('Toggle to disable use of the system'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const IntegrationsPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Integration.')
})

export const integrationsPartialUpdateBodyIntegrationIdMax = 32;



export const IntegrationsPartialUpdateBody = zod.object({
  "integration_id": zod.string().max(integrationsPartialUpdateBodyIntegrationIdMax).optional(),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider_id": zod.number().optional(),
  "user": zod.number().optional(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider')
})

export const integrationsPartialUpdateResponseIntegrationIdMax = 32;

export const integrationsPartialUpdateResponseIntegrationProviderOneNameMax = 100;



export const IntegrationsPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "integration_id": zod.string().max(integrationsPartialUpdateResponseIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider": zod.object({
  "id": zod.number(),
  "name": zod.string().max(integrationsPartialUpdateResponseIntegrationProviderOneNameMax).describe('Name of the external system (e.g. LMS, HR System)'),
  "description": zod.string().optional().describe('Optional description of the system'),
  "is_active": zod.boolean().optional().describe('Toggle to disable use of the system'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const IntegrationsDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Integration.')
})

export const integrationsConnectedAppsRetrieveResponseIntegrationIdMax = 32;

export const integrationsConnectedAppsRetrieveResponseIntegrationProviderOneNameMax = 100;



export const IntegrationsConnectedAppsRetrieveResponse = zod.object({
  "id": zod.number(),
  "integration_id": zod.string().max(integrationsConnectedAppsRetrieveResponseIntegrationIdMax),
  "integration_type": zod.enum(['student', 'staff', 'other']).optional().describe('\* `student` - Student\n\* `staff` - Staff\n\* `other` - Other'),
  "integration_provider": zod.object({
  "id": zod.number(),
  "name": zod.string().max(integrationsConnectedAppsRetrieveResponseIntegrationProviderOneNameMax).describe('Name of the external system (e.g. LMS, HR System)'),
  "description": zod.string().optional().describe('Optional description of the system'),
  "is_active": zod.boolean().optional().describe('Toggle to disable use of the system'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}),
  "integration_provider_id": zod.number(),
  "user": zod.number(),
  "meta_data": zod.unknown().optional().describe('Optional data from the integration provider'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

