/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const MeetingsListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const meetingsListResponseResultsItemTitleMax = 255;

export const meetingsListResponseResultsItemVenueMax = 255;

export const meetingsListResponseResultsItemMeetingThumbnailFallbackMax = 255;



export const MeetingsListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string().max(meetingsListResponseResultsItemTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsListResponseResultsItemVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsListResponseResultsItemMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})).optional()
})

export const meetingsCreateBodyTitleMax = 255;

export const meetingsCreateBodyVenueMax = 255;

export const meetingsCreateBodyMeetingThumbnailFallbackMax = 255;



export const MeetingsCreateBody = zod.object({
  "title": zod.string().max(meetingsCreateBodyTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsCreateBodyVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsCreateBodyMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const MeetingsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

export const meetingsRetrieveResponseTitleMax = 255;

export const meetingsRetrieveResponseVenueMax = 255;

export const meetingsRetrieveResponseMeetingThumbnailFallbackMax = 255;



export const MeetingsRetrieveResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(meetingsRetrieveResponseTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsRetrieveResponseVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsRetrieveResponseMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const MeetingsUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

export const meetingsUpdateBodyTitleMax = 255;

export const meetingsUpdateBodyVenueMax = 255;

export const meetingsUpdateBodyMeetingThumbnailFallbackMax = 255;



export const MeetingsUpdateBody = zod.object({
  "title": zod.string().max(meetingsUpdateBodyTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsUpdateBodyVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsUpdateBodyMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const meetingsUpdateResponseTitleMax = 255;

export const meetingsUpdateResponseVenueMax = 255;

export const meetingsUpdateResponseMeetingThumbnailFallbackMax = 255;



export const MeetingsUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(meetingsUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsUpdateResponseVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsUpdateResponseMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const MeetingsPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

export const meetingsPartialUpdateBodyTitleMax = 255;

export const meetingsPartialUpdateBodyVenueMax = 255;

export const meetingsPartialUpdateBodyMeetingThumbnailFallbackMax = 255;



export const MeetingsPartialUpdateBody = zod.object({
  "title": zod.string().max(meetingsPartialUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsPartialUpdateBodyVenueMax).optional(),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsPartialUpdateBodyMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}).optional(),
  "meeting_end_time": zod.iso.datetime({}).optional(),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const meetingsPartialUpdateResponseTitleMax = 255;

export const meetingsPartialUpdateResponseVenueMax = 255;

export const meetingsPartialUpdateResponseMeetingThumbnailFallbackMax = 255;



export const MeetingsPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(meetingsPartialUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(meetingsPartialUpdateResponseVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(meetingsPartialUpdateResponseMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const MeetingsDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

