/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const messagesListResponseTitleMax = 255;

export const messagesListResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessagesListResponseItem = zod.object({
  "reference_id": zod.string(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "created_by_name": zod.string(),
  "title": zod.string().max(messagesListResponseTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().regex(messagesListResponseSlugRegExp),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const MessagesListResponse = zod.array(MessagesListResponseItem)

export const messagesCreateBodyTitleMax = 255;



export const MessagesCreateBody = zod.object({
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "title": zod.string().max(messagesCreateBodyTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony')
})

export const MessagesRetrieveParams = zod.object({
  "umid": zod.string()
})

export const messagesRetrieveResponseTitleMax = 255;

export const messagesRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessagesRetrieveResponse = zod.object({
  "reference_id": zod.string(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "created_by_name": zod.string(),
  "title": zod.string().max(messagesRetrieveResponseTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().regex(messagesRetrieveResponseSlugRegExp),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const MessagesUpdateParams = zod.object({
  "umid": zod.string()
})

export const messagesUpdateBodyTitleMax = 255;



export const MessagesUpdateBody = zod.object({
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "title": zod.string().max(messagesUpdateBodyTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony')
})

export const messagesUpdateResponseTitleMax = 255;

export const messagesUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessagesUpdateResponse = zod.object({
  "reference_id": zod.string(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "created_by_name": zod.string(),
  "title": zod.string().max(messagesUpdateResponseTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().regex(messagesUpdateResponseSlugRegExp),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const MessagesPartialUpdateParams = zod.object({
  "umid": zod.string()
})

export const messagesPartialUpdateBodyTitleMax = 255;



export const MessagesPartialUpdateBody = zod.object({
  "assembly": zod.number().optional(),
  "created_by": zod.number().nullish(),
  "title": zod.string().max(messagesPartialUpdateBodyTitleMax).optional(),
  "body": zod.string().optional(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony')
})

export const messagesPartialUpdateResponseTitleMax = 255;

export const messagesPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessagesPartialUpdateResponse = zod.object({
  "reference_id": zod.string(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "created_by_name": zod.string(),
  "title": zod.string().max(messagesPartialUpdateResponseTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().regex(messagesPartialUpdateResponseSlugRegExp),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const MessagesDestroyParams = zod.object({
  "umid": zod.string()
})

