/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const messengerCreateBodyTitleMax = 255;

export const messengerCreateBodySlugMax = 255;


export const messengerCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessengerCreateBody = zod.object({
  "title": zod.string().max(messengerCreateBodyTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().max(messengerCreateBodySlugMax).regex(messengerCreateBodySlugRegExp).optional(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish()
})

export const MessengerUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Message.')
})

export const messengerUpdateBodyTitleMax = 255;

export const messengerUpdateBodySlugMax = 255;


export const messengerUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessengerUpdateBody = zod.object({
  "title": zod.string().max(messengerUpdateBodyTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().max(messengerUpdateBodySlugMax).regex(messengerUpdateBodySlugRegExp).optional(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish()
})

export const messengerUpdateResponseTitleMax = 255;

export const messengerUpdateResponseSlugMax = 255;


export const messengerUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessengerUpdateResponse = zod.object({
  "id": zod.number(),
  "reference_id": zod.string(),
  "title": zod.string().max(messengerUpdateResponseTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().max(messengerUpdateResponseSlugMax).regex(messengerUpdateResponseSlugRegExp).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish()
})

export const MessengerPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Message.')
})

export const messengerPartialUpdateBodyTitleMax = 255;

export const messengerPartialUpdateBodySlugMax = 255;


export const messengerPartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessengerPartialUpdateBody = zod.object({
  "title": zod.string().max(messengerPartialUpdateBodyTitleMax).optional(),
  "body": zod.string().optional(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().max(messengerPartialUpdateBodySlugMax).regex(messengerPartialUpdateBodySlugRegExp).optional(),
  "assembly": zod.number().optional(),
  "created_by": zod.number().nullish()
})

export const messengerPartialUpdateResponseTitleMax = 255;

export const messengerPartialUpdateResponseSlugMax = 255;


export const messengerPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const MessengerPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "reference_id": zod.string(),
  "title": zod.string().max(messengerPartialUpdateResponseTitleMax).optional(),
  "body": zod.string(),
  "priority": zod.enum(['low', 'medium', 'high', 'urgent']).optional().describe('\* `low` - Low\n\* `medium` - Medium\n\* `high` - High\n\* `urgent` - Urgent'),
  "category": zod.enum(['praise', 'request', 'suggestion', 'testimony']).optional().describe('\* `praise` - Praise\n\* `request` - Request\n\* `suggestion` - Suggestion\n\* `testimony` - Testimony'),
  "slug": zod.string().max(messengerPartialUpdateResponseSlugMax).regex(messengerPartialUpdateResponseSlugRegExp).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish()
})

