/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const MinutesListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const minutesListResponseResultsItemMeetingTitleMax = 255;

export const minutesListResponseResultsItemMeetingVenueMax = 255;

export const minutesListResponseResultsItemMeetingMeetingThumbnailFallbackMax = 255;



export const MinutesListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string().max(minutesListResponseResultsItemMeetingTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(minutesListResponseResultsItemMeetingVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(minutesListResponseResultsItemMeetingMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
}),
  "assembly": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})).optional()
})

export const MinutesCreateBody = zod.object({
  "uploaded_file": zod.url().nullish(),
  "assembly": zod.number(),
  "meeting": zod.number()
})

export const MinutesRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this minute.')
})

export const minutesRetrieveResponseMeetingTitleMax = 255;

export const minutesRetrieveResponseMeetingVenueMax = 255;

export const minutesRetrieveResponseMeetingMeetingThumbnailFallbackMax = 255;



export const MinutesRetrieveResponse = zod.object({
  "id": zod.number(),
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string().max(minutesRetrieveResponseMeetingTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(minutesRetrieveResponseMeetingVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(minutesRetrieveResponseMeetingMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
}),
  "assembly": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const MinutesUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this minute.')
})

export const minutesUpdateBodyMeetingTitleMax = 255;

export const minutesUpdateBodyMeetingVenueMax = 255;

export const minutesUpdateBodyMeetingMeetingThumbnailFallbackMax = 255;



export const MinutesUpdateBody = zod.object({
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string().max(minutesUpdateBodyMeetingTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(minutesUpdateBodyMeetingVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(minutesUpdateBodyMeetingMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
}),
  "assembly": zod.number()
})

export const minutesUpdateResponseMeetingTitleMax = 255;

export const minutesUpdateResponseMeetingVenueMax = 255;

export const minutesUpdateResponseMeetingMeetingThumbnailFallbackMax = 255;



export const MinutesUpdateResponse = zod.object({
  "id": zod.number(),
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string().max(minutesUpdateResponseMeetingTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(minutesUpdateResponseMeetingVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(minutesUpdateResponseMeetingMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
}),
  "assembly": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const MinutesPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this minute.')
})

export const minutesPartialUpdateBodyMeetingTitleMax = 255;

export const minutesPartialUpdateBodyMeetingVenueMax = 255;

export const minutesPartialUpdateBodyMeetingMeetingThumbnailFallbackMax = 255;



export const MinutesPartialUpdateBody = zod.object({
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string().max(minutesPartialUpdateBodyMeetingTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(minutesPartialUpdateBodyMeetingVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(minutesPartialUpdateBodyMeetingMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
}).optional(),
  "assembly": zod.number().optional()
})

export const minutesPartialUpdateResponseMeetingTitleMax = 255;

export const minutesPartialUpdateResponseMeetingVenueMax = 255;

export const minutesPartialUpdateResponseMeetingMeetingThumbnailFallbackMax = 255;



export const MinutesPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "meeting": zod.object({
  "id": zod.number(),
  "title": zod.string().max(minutesPartialUpdateResponseMeetingTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(minutesPartialUpdateResponseMeetingVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(minutesPartialUpdateResponseMeetingMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
}),
  "assembly": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const MinutesDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this minute.')
})

