/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const PeopleAttendanceRetrieve2Params = zod.object({
  "id": zod.string()
})

export const PeopleAttendanceUpdateParams = zod.object({
  "id": zod.string()
})

export const PeopleAttendancePartialUpdateParams = zod.object({
  "id": zod.string()
})

export const PeopleAttendanceDestroyParams = zod.object({
  "id": zod.string()
})

export const PeopleAttendanceRestoreCreateParams = zod.object({
  "id": zod.string()
})

export const PeopleBelongMemberRetrieveParams = zod.object({
  "member_key": zod.string()
})

export const peopleHomecellsListResponseGroupNameMax = 255;



export const PeopleHomecellsListResponseItem = zod.object({
  "id": zod.number(),
  "group_name": zod.string().max(peopleHomecellsListResponseGroupNameMax)
})
export const PeopleHomecellsListResponse = zod.array(PeopleHomecellsListResponseItem)

export const peopleHomecellsCreateBodyGroupNameMax = 255;



export const PeopleHomecellsCreateBody = zod.object({
  "group_name": zod.string().max(peopleHomecellsCreateBodyGroupNameMax),
  "description": zod.string().optional(),
  "leader_id": zod.number().optional(),
  "member_ids": zod.array(zod.number()).optional(),
  "non_church_members": zod.string().optional(),
  "is_archived": zod.boolean().optional()
})

export const PeopleHomecellsRetrieveParams = zod.object({
  "id": zod.string()
})

export const peopleHomecellsRetrieveResponseGroupNameMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneFirstNameMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOneMiddleNameMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOneMaidenNameMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOneLastNameMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOnePlaceOfBirthMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOnePhoneNumberMax = 17;


export const peopleHomecellsRetrieveResponseLeaderOnePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsRetrieveResponseLeaderOneSecondaryPhoneNumberMax = 17;


export const peopleHomecellsRetrieveResponseLeaderOneSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsRetrieveResponseLeaderOneEmailMax = 254;

export const peopleHomecellsRetrieveResponseLeaderOneAddressMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneAddressLine2Max = 255;

export const peopleHomecellsRetrieveResponseLeaderOneCityMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneProvinceMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOneCountryMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOnePreviousChurchMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneBaptizedWhereMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneOccupationMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneEmployerMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneSkillsMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneEmergencyContactNameMax = 255;

export const peopleHomecellsRetrieveResponseLeaderOneEmergencyContactRelationshipMax = 100;

export const peopleHomecellsRetrieveResponseLeaderOneEmergencyContactPhoneMax = 17;


export const peopleHomecellsRetrieveResponseLeaderOneEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsRetrieveResponseLeaderOneAvatarFallbackMax = 64;

export const peopleHomecellsRetrieveResponseLeaderOneAccessPinMax = 128;

export const peopleHomecellsRetrieveResponseMembersItemFirstNameMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemMiddleNameMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemMaidenNameMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemLastNameMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemPlaceOfBirthMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemPhoneNumberMax = 17;


export const peopleHomecellsRetrieveResponseMembersItemPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsRetrieveResponseMembersItemSecondaryPhoneNumberMax = 17;


export const peopleHomecellsRetrieveResponseMembersItemSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsRetrieveResponseMembersItemEmailMax = 254;

export const peopleHomecellsRetrieveResponseMembersItemAddressMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemAddressLine2Max = 255;

export const peopleHomecellsRetrieveResponseMembersItemCityMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemProvinceMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemCountryMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemPreviousChurchMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemBaptizedWhereMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemOccupationMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemEmployerMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemSkillsMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemEmergencyContactNameMax = 255;

export const peopleHomecellsRetrieveResponseMembersItemEmergencyContactRelationshipMax = 100;

export const peopleHomecellsRetrieveResponseMembersItemEmergencyContactPhoneMax = 17;


export const peopleHomecellsRetrieveResponseMembersItemEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsRetrieveResponseMembersItemAvatarFallbackMax = 64;

export const peopleHomecellsRetrieveResponseMembersItemAccessPinMax = 128;



export const PeopleHomecellsRetrieveResponse = zod.object({
  "id": zod.number(),
  "group_name": zod.string().max(peopleHomecellsRetrieveResponseGroupNameMax),
  "description": zod.string().optional(),
  "leader": zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneFirstNameMax),
  "middle_name": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleHomecellsRetrieveResponseLeaderOnePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleHomecellsRetrieveResponseLeaderOnePhoneNumberMax).regex(peopleHomecellsRetrieveResponseLeaderOnePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneSecondaryPhoneNumberMax).regex(peopleHomecellsRetrieveResponseLeaderOneSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleHomecellsRetrieveResponseLeaderOneEmailMax).optional(),
  "address": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneAddressMax).optional(),
  "address_line2": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneAddressLine2Max).optional(),
  "city": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneCityMax).optional(),
  "province": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneProvinceMax).optional(),
  "country": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleHomecellsRetrieveResponseLeaderOnePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneOccupationMax).optional(),
  "employer": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneEmergencyContactPhoneMax).regex(peopleHomecellsRetrieveResponseLeaderOneEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleHomecellsRetrieveResponseLeaderOneAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
}),
  "leader_id": zod.number().optional(),
  "members": zod.array(zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleHomecellsRetrieveResponseMembersItemFirstNameMax),
  "middle_name": zod.string().max(peopleHomecellsRetrieveResponseMembersItemMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleHomecellsRetrieveResponseMembersItemMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleHomecellsRetrieveResponseMembersItemLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleHomecellsRetrieveResponseMembersItemPlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleHomecellsRetrieveResponseMembersItemPhoneNumberMax).regex(peopleHomecellsRetrieveResponseMembersItemPhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleHomecellsRetrieveResponseMembersItemSecondaryPhoneNumberMax).regex(peopleHomecellsRetrieveResponseMembersItemSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleHomecellsRetrieveResponseMembersItemEmailMax).optional(),
  "address": zod.string().max(peopleHomecellsRetrieveResponseMembersItemAddressMax).optional(),
  "address_line2": zod.string().max(peopleHomecellsRetrieveResponseMembersItemAddressLine2Max).optional(),
  "city": zod.string().max(peopleHomecellsRetrieveResponseMembersItemCityMax).optional(),
  "province": zod.string().max(peopleHomecellsRetrieveResponseMembersItemProvinceMax).optional(),
  "country": zod.string().max(peopleHomecellsRetrieveResponseMembersItemCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleHomecellsRetrieveResponseMembersItemPreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleHomecellsRetrieveResponseMembersItemBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleHomecellsRetrieveResponseMembersItemOccupationMax).optional(),
  "employer": zod.string().max(peopleHomecellsRetrieveResponseMembersItemEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleHomecellsRetrieveResponseMembersItemSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleHomecellsRetrieveResponseMembersItemEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleHomecellsRetrieveResponseMembersItemEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleHomecellsRetrieveResponseMembersItemEmergencyContactPhoneMax).regex(peopleHomecellsRetrieveResponseMembersItemEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleHomecellsRetrieveResponseMembersItemAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleHomecellsRetrieveResponseMembersItemAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})),
  "member_ids": zod.array(zod.number()).optional(),
  "non_church_members": zod.string().optional(),
  "is_archived": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PeopleHomecellsUpdateParams = zod.object({
  "id": zod.string()
})

export const peopleHomecellsUpdateBodyGroupNameMax = 255;



export const PeopleHomecellsUpdateBody = zod.object({
  "group_name": zod.string().max(peopleHomecellsUpdateBodyGroupNameMax),
  "description": zod.string().optional(),
  "leader_id": zod.number().optional(),
  "member_ids": zod.array(zod.number()).optional(),
  "non_church_members": zod.string().optional(),
  "is_archived": zod.boolean().optional()
})

export const peopleHomecellsUpdateResponseGroupNameMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneFirstNameMax = 100;

export const peopleHomecellsUpdateResponseLeaderOneMiddleNameMax = 100;

export const peopleHomecellsUpdateResponseLeaderOneMaidenNameMax = 100;

export const peopleHomecellsUpdateResponseLeaderOneLastNameMax = 100;

export const peopleHomecellsUpdateResponseLeaderOnePlaceOfBirthMax = 100;

export const peopleHomecellsUpdateResponseLeaderOnePhoneNumberMax = 17;


export const peopleHomecellsUpdateResponseLeaderOnePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsUpdateResponseLeaderOneSecondaryPhoneNumberMax = 17;


export const peopleHomecellsUpdateResponseLeaderOneSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsUpdateResponseLeaderOneEmailMax = 254;

export const peopleHomecellsUpdateResponseLeaderOneAddressMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneAddressLine2Max = 255;

export const peopleHomecellsUpdateResponseLeaderOneCityMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneProvinceMax = 100;

export const peopleHomecellsUpdateResponseLeaderOneCountryMax = 255;

export const peopleHomecellsUpdateResponseLeaderOnePreviousChurchMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneBaptizedWhereMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneOccupationMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneEmployerMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneSkillsMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneEmergencyContactNameMax = 255;

export const peopleHomecellsUpdateResponseLeaderOneEmergencyContactRelationshipMax = 100;

export const peopleHomecellsUpdateResponseLeaderOneEmergencyContactPhoneMax = 17;


export const peopleHomecellsUpdateResponseLeaderOneEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsUpdateResponseLeaderOneAvatarFallbackMax = 64;

export const peopleHomecellsUpdateResponseLeaderOneAccessPinMax = 128;

export const peopleHomecellsUpdateResponseMembersItemFirstNameMax = 100;

export const peopleHomecellsUpdateResponseMembersItemMiddleNameMax = 100;

export const peopleHomecellsUpdateResponseMembersItemMaidenNameMax = 100;

export const peopleHomecellsUpdateResponseMembersItemLastNameMax = 100;

export const peopleHomecellsUpdateResponseMembersItemPlaceOfBirthMax = 100;

export const peopleHomecellsUpdateResponseMembersItemPhoneNumberMax = 17;


export const peopleHomecellsUpdateResponseMembersItemPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsUpdateResponseMembersItemSecondaryPhoneNumberMax = 17;


export const peopleHomecellsUpdateResponseMembersItemSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsUpdateResponseMembersItemEmailMax = 254;

export const peopleHomecellsUpdateResponseMembersItemAddressMax = 255;

export const peopleHomecellsUpdateResponseMembersItemAddressLine2Max = 255;

export const peopleHomecellsUpdateResponseMembersItemCityMax = 255;

export const peopleHomecellsUpdateResponseMembersItemProvinceMax = 100;

export const peopleHomecellsUpdateResponseMembersItemCountryMax = 255;

export const peopleHomecellsUpdateResponseMembersItemPreviousChurchMax = 255;

export const peopleHomecellsUpdateResponseMembersItemBaptizedWhereMax = 255;

export const peopleHomecellsUpdateResponseMembersItemOccupationMax = 255;

export const peopleHomecellsUpdateResponseMembersItemEmployerMax = 255;

export const peopleHomecellsUpdateResponseMembersItemSkillsMax = 255;

export const peopleHomecellsUpdateResponseMembersItemEmergencyContactNameMax = 255;

export const peopleHomecellsUpdateResponseMembersItemEmergencyContactRelationshipMax = 100;

export const peopleHomecellsUpdateResponseMembersItemEmergencyContactPhoneMax = 17;


export const peopleHomecellsUpdateResponseMembersItemEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsUpdateResponseMembersItemAvatarFallbackMax = 64;

export const peopleHomecellsUpdateResponseMembersItemAccessPinMax = 128;



export const PeopleHomecellsUpdateResponse = zod.object({
  "id": zod.number(),
  "group_name": zod.string().max(peopleHomecellsUpdateResponseGroupNameMax),
  "description": zod.string().optional(),
  "leader": zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleHomecellsUpdateResponseLeaderOneFirstNameMax),
  "middle_name": zod.string().max(peopleHomecellsUpdateResponseLeaderOneMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleHomecellsUpdateResponseLeaderOneMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleHomecellsUpdateResponseLeaderOneLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleHomecellsUpdateResponseLeaderOnePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleHomecellsUpdateResponseLeaderOnePhoneNumberMax).regex(peopleHomecellsUpdateResponseLeaderOnePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleHomecellsUpdateResponseLeaderOneSecondaryPhoneNumberMax).regex(peopleHomecellsUpdateResponseLeaderOneSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleHomecellsUpdateResponseLeaderOneEmailMax).optional(),
  "address": zod.string().max(peopleHomecellsUpdateResponseLeaderOneAddressMax).optional(),
  "address_line2": zod.string().max(peopleHomecellsUpdateResponseLeaderOneAddressLine2Max).optional(),
  "city": zod.string().max(peopleHomecellsUpdateResponseLeaderOneCityMax).optional(),
  "province": zod.string().max(peopleHomecellsUpdateResponseLeaderOneProvinceMax).optional(),
  "country": zod.string().max(peopleHomecellsUpdateResponseLeaderOneCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleHomecellsUpdateResponseLeaderOnePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleHomecellsUpdateResponseLeaderOneBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleHomecellsUpdateResponseLeaderOneOccupationMax).optional(),
  "employer": zod.string().max(peopleHomecellsUpdateResponseLeaderOneEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleHomecellsUpdateResponseLeaderOneSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleHomecellsUpdateResponseLeaderOneEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleHomecellsUpdateResponseLeaderOneEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleHomecellsUpdateResponseLeaderOneEmergencyContactPhoneMax).regex(peopleHomecellsUpdateResponseLeaderOneEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleHomecellsUpdateResponseLeaderOneAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleHomecellsUpdateResponseLeaderOneAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
}),
  "leader_id": zod.number().optional(),
  "members": zod.array(zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleHomecellsUpdateResponseMembersItemFirstNameMax),
  "middle_name": zod.string().max(peopleHomecellsUpdateResponseMembersItemMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleHomecellsUpdateResponseMembersItemMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleHomecellsUpdateResponseMembersItemLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleHomecellsUpdateResponseMembersItemPlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleHomecellsUpdateResponseMembersItemPhoneNumberMax).regex(peopleHomecellsUpdateResponseMembersItemPhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleHomecellsUpdateResponseMembersItemSecondaryPhoneNumberMax).regex(peopleHomecellsUpdateResponseMembersItemSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleHomecellsUpdateResponseMembersItemEmailMax).optional(),
  "address": zod.string().max(peopleHomecellsUpdateResponseMembersItemAddressMax).optional(),
  "address_line2": zod.string().max(peopleHomecellsUpdateResponseMembersItemAddressLine2Max).optional(),
  "city": zod.string().max(peopleHomecellsUpdateResponseMembersItemCityMax).optional(),
  "province": zod.string().max(peopleHomecellsUpdateResponseMembersItemProvinceMax).optional(),
  "country": zod.string().max(peopleHomecellsUpdateResponseMembersItemCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleHomecellsUpdateResponseMembersItemPreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleHomecellsUpdateResponseMembersItemBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleHomecellsUpdateResponseMembersItemOccupationMax).optional(),
  "employer": zod.string().max(peopleHomecellsUpdateResponseMembersItemEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleHomecellsUpdateResponseMembersItemSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleHomecellsUpdateResponseMembersItemEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleHomecellsUpdateResponseMembersItemEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleHomecellsUpdateResponseMembersItemEmergencyContactPhoneMax).regex(peopleHomecellsUpdateResponseMembersItemEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleHomecellsUpdateResponseMembersItemAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleHomecellsUpdateResponseMembersItemAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})),
  "member_ids": zod.array(zod.number()).optional(),
  "non_church_members": zod.string().optional(),
  "is_archived": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PeopleHomecellsPartialUpdateParams = zod.object({
  "id": zod.string()
})

export const peopleHomecellsPartialUpdateBodyGroupNameMax = 255;



export const PeopleHomecellsPartialUpdateBody = zod.object({
  "group_name": zod.string().max(peopleHomecellsPartialUpdateBodyGroupNameMax).optional(),
  "description": zod.string().optional(),
  "leader_id": zod.number().optional(),
  "member_ids": zod.array(zod.number()).optional(),
  "non_church_members": zod.string().optional(),
  "is_archived": zod.boolean().optional()
})

export const peopleHomecellsPartialUpdateResponseGroupNameMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneFirstNameMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOneMiddleNameMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOneMaidenNameMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOneLastNameMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOnePlaceOfBirthMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOnePhoneNumberMax = 17;


export const peopleHomecellsPartialUpdateResponseLeaderOnePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsPartialUpdateResponseLeaderOneSecondaryPhoneNumberMax = 17;


export const peopleHomecellsPartialUpdateResponseLeaderOneSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsPartialUpdateResponseLeaderOneEmailMax = 254;

export const peopleHomecellsPartialUpdateResponseLeaderOneAddressMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneAddressLine2Max = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneCityMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneProvinceMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOneCountryMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOnePreviousChurchMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneBaptizedWhereMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneOccupationMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneEmployerMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneSkillsMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactNameMax = 255;

export const peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactRelationshipMax = 100;

export const peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactPhoneMax = 17;


export const peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsPartialUpdateResponseLeaderOneAvatarFallbackMax = 64;

export const peopleHomecellsPartialUpdateResponseLeaderOneAccessPinMax = 128;

export const peopleHomecellsPartialUpdateResponseMembersItemFirstNameMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemMiddleNameMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemMaidenNameMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemLastNameMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemPlaceOfBirthMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemPhoneNumberMax = 17;


export const peopleHomecellsPartialUpdateResponseMembersItemPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsPartialUpdateResponseMembersItemSecondaryPhoneNumberMax = 17;


export const peopleHomecellsPartialUpdateResponseMembersItemSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsPartialUpdateResponseMembersItemEmailMax = 254;

export const peopleHomecellsPartialUpdateResponseMembersItemAddressMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemAddressLine2Max = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemCityMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemProvinceMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemCountryMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemPreviousChurchMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemBaptizedWhereMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemOccupationMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemEmployerMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemSkillsMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactNameMax = 255;

export const peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactRelationshipMax = 100;

export const peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactPhoneMax = 17;


export const peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleHomecellsPartialUpdateResponseMembersItemAvatarFallbackMax = 64;

export const peopleHomecellsPartialUpdateResponseMembersItemAccessPinMax = 128;



export const PeopleHomecellsPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "group_name": zod.string().max(peopleHomecellsPartialUpdateResponseGroupNameMax),
  "description": zod.string().optional(),
  "leader": zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneFirstNameMax),
  "middle_name": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOnePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOnePhoneNumberMax).regex(peopleHomecellsPartialUpdateResponseLeaderOnePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneSecondaryPhoneNumberMax).regex(peopleHomecellsPartialUpdateResponseLeaderOneSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleHomecellsPartialUpdateResponseLeaderOneEmailMax).optional(),
  "address": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneAddressMax).optional(),
  "address_line2": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneAddressLine2Max).optional(),
  "city": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneCityMax).optional(),
  "province": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneProvinceMax).optional(),
  "country": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOnePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneOccupationMax).optional(),
  "employer": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactPhoneMax).regex(peopleHomecellsPartialUpdateResponseLeaderOneEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleHomecellsPartialUpdateResponseLeaderOneAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
}),
  "leader_id": zod.number().optional(),
  "members": zod.array(zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemFirstNameMax),
  "middle_name": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemPlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemPhoneNumberMax).regex(peopleHomecellsPartialUpdateResponseMembersItemPhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemSecondaryPhoneNumberMax).regex(peopleHomecellsPartialUpdateResponseMembersItemSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleHomecellsPartialUpdateResponseMembersItemEmailMax).optional(),
  "address": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemAddressMax).optional(),
  "address_line2": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemAddressLine2Max).optional(),
  "city": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemCityMax).optional(),
  "province": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemProvinceMax).optional(),
  "country": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemPreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemOccupationMax).optional(),
  "employer": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactPhoneMax).regex(peopleHomecellsPartialUpdateResponseMembersItemEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleHomecellsPartialUpdateResponseMembersItemAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})),
  "member_ids": zod.array(zod.number()).optional(),
  "non_church_members": zod.string().optional(),
  "is_archived": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PeopleHomecellsDestroyParams = zod.object({
  "id": zod.string()
})

export const PeopleJuniorMembersRetrieve2Params = zod.object({
  "member_key": zod.uuid()
})

export const PeopleJuniorMembersUpdateParams = zod.object({
  "member_key": zod.uuid()
})

export const PeopleJuniorMembersPartialUpdateParams = zod.object({
  "member_key": zod.uuid()
})

export const PeopleJuniorMembersDestroyParams = zod.object({
  "member_key": zod.uuid()
})

export const PeopleMembersListQueryParams = zod.object({
  "first_name": zod.string().optional(),
  "fullname": zod.string().optional(),
  "last_name": zod.string().optional(),
  "member_key": zod.uuid().optional()
})

export const peopleMembersListResponseFirstNameMax = 100;

export const peopleMembersListResponseMiddleNameMax = 100;

export const peopleMembersListResponseMaidenNameMax = 100;

export const peopleMembersListResponseLastNameMax = 100;

export const peopleMembersListResponsePlaceOfBirthMax = 100;

export const peopleMembersListResponsePhoneNumberMax = 17;


export const peopleMembersListResponsePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersListResponseSecondaryPhoneNumberMax = 17;


export const peopleMembersListResponseSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersListResponseEmailMax = 254;

export const peopleMembersListResponseAddressMax = 255;

export const peopleMembersListResponseAddressLine2Max = 255;

export const peopleMembersListResponseCityMax = 255;

export const peopleMembersListResponseProvinceMax = 100;

export const peopleMembersListResponseCountryMax = 255;

export const peopleMembersListResponsePreviousChurchMax = 255;

export const peopleMembersListResponseBaptizedWhereMax = 255;

export const peopleMembersListResponseOccupationMax = 255;

export const peopleMembersListResponseEmployerMax = 255;

export const peopleMembersListResponseSkillsMax = 255;

export const peopleMembersListResponseEmergencyContactNameMax = 255;

export const peopleMembersListResponseEmergencyContactRelationshipMax = 100;

export const peopleMembersListResponseEmergencyContactPhoneMax = 17;


export const peopleMembersListResponseEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersListResponseAvatarFallbackMax = 64;

export const peopleMembersListResponseAccessPinMax = 128;



export const PeopleMembersListResponseItem = zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersListResponseFirstNameMax),
  "middle_name": zod.string().max(peopleMembersListResponseMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersListResponseMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersListResponseLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleMembersListResponsePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersListResponsePhoneNumberMax).regex(peopleMembersListResponsePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleMembersListResponseSecondaryPhoneNumberMax).regex(peopleMembersListResponseSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersListResponseEmailMax).optional(),
  "address": zod.string().max(peopleMembersListResponseAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersListResponseAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersListResponseCityMax).optional(),
  "province": zod.string().max(peopleMembersListResponseProvinceMax).optional(),
  "country": zod.string().max(peopleMembersListResponseCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersListResponsePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersListResponseBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersListResponseOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersListResponseEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersListResponseSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersListResponseEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersListResponseEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersListResponseEmergencyContactPhoneMax).regex(peopleMembersListResponseEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersListResponseAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersListResponseAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})
export const PeopleMembersListResponse = zod.array(PeopleMembersListResponseItem)

export const peopleMembersCreateBodyFirstNameMax = 100;

export const peopleMembersCreateBodyMiddleNameMax = 100;

export const peopleMembersCreateBodyMaidenNameMax = 100;

export const peopleMembersCreateBodyLastNameMax = 100;

export const peopleMembersCreateBodyPlaceOfBirthMax = 100;

export const peopleMembersCreateBodyPhoneNumberMax = 17;


export const peopleMembersCreateBodyPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersCreateBodySecondaryPhoneNumberMax = 17;


export const peopleMembersCreateBodySecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersCreateBodyEmailMax = 254;

export const peopleMembersCreateBodyAddressMax = 255;

export const peopleMembersCreateBodyAddressLine2Max = 255;

export const peopleMembersCreateBodyCityMax = 255;

export const peopleMembersCreateBodyProvinceMax = 100;

export const peopleMembersCreateBodyCountryMax = 255;

export const peopleMembersCreateBodyPreviousChurchMax = 255;

export const peopleMembersCreateBodyBaptizedWhereMax = 255;

export const peopleMembersCreateBodyOccupationMax = 255;

export const peopleMembersCreateBodyEmployerMax = 255;

export const peopleMembersCreateBodySkillsMax = 255;

export const peopleMembersCreateBodyEmergencyContactNameMax = 255;

export const peopleMembersCreateBodyEmergencyContactRelationshipMax = 100;

export const peopleMembersCreateBodyEmergencyContactPhoneMax = 17;


export const peopleMembersCreateBodyEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersCreateBodyAvatarFallbackMax = 64;

export const peopleMembersCreateBodyAccessPinMax = 128;



export const PeopleMembersCreateBody = zod.object({
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersCreateBodyFirstNameMax),
  "middle_name": zod.string().max(peopleMembersCreateBodyMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersCreateBodyMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersCreateBodyLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleMembersCreateBodyPlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersCreateBodyPhoneNumberMax).regex(peopleMembersCreateBodyPhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleMembersCreateBodySecondaryPhoneNumberMax).regex(peopleMembersCreateBodySecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersCreateBodyEmailMax).optional(),
  "address": zod.string().max(peopleMembersCreateBodyAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersCreateBodyAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersCreateBodyCityMax).optional(),
  "province": zod.string().max(peopleMembersCreateBodyProvinceMax).optional(),
  "country": zod.string().max(peopleMembersCreateBodyCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersCreateBodyPreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersCreateBodyBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersCreateBodyOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersCreateBodyEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersCreateBodySkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersCreateBodyEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersCreateBodyEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersCreateBodyEmergencyContactPhoneMax).regex(peopleMembersCreateBodyEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersCreateBodyAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersCreateBodyAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})

export const PeopleMembersRetrieveParams = zod.object({
  "member_key": zod.string()
})

export const peopleMembersRetrieveResponseFirstNameMax = 100;

export const peopleMembersRetrieveResponseMiddleNameMax = 100;

export const peopleMembersRetrieveResponseMaidenNameMax = 100;

export const peopleMembersRetrieveResponseLastNameMax = 100;

export const peopleMembersRetrieveResponsePlaceOfBirthMax = 100;

export const peopleMembersRetrieveResponsePhoneNumberMax = 17;


export const peopleMembersRetrieveResponsePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersRetrieveResponseSecondaryPhoneNumberMax = 17;


export const peopleMembersRetrieveResponseSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersRetrieveResponseEmailMax = 254;

export const peopleMembersRetrieveResponseAddressMax = 255;

export const peopleMembersRetrieveResponseAddressLine2Max = 255;

export const peopleMembersRetrieveResponseCityMax = 255;

export const peopleMembersRetrieveResponseProvinceMax = 100;

export const peopleMembersRetrieveResponseCountryMax = 255;

export const peopleMembersRetrieveResponsePreviousChurchMax = 255;

export const peopleMembersRetrieveResponseBaptizedWhereMax = 255;

export const peopleMembersRetrieveResponseOccupationMax = 255;

export const peopleMembersRetrieveResponseEmployerMax = 255;

export const peopleMembersRetrieveResponseSkillsMax = 255;

export const peopleMembersRetrieveResponseEmergencyContactNameMax = 255;

export const peopleMembersRetrieveResponseEmergencyContactRelationshipMax = 100;

export const peopleMembersRetrieveResponseEmergencyContactPhoneMax = 17;


export const peopleMembersRetrieveResponseEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersRetrieveResponseAvatarFallbackMax = 64;

export const peopleMembersRetrieveResponseAccessPinMax = 128;



export const PeopleMembersRetrieveResponse = zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersRetrieveResponseFirstNameMax),
  "middle_name": zod.string().max(peopleMembersRetrieveResponseMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersRetrieveResponseMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersRetrieveResponseLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleMembersRetrieveResponsePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersRetrieveResponsePhoneNumberMax).regex(peopleMembersRetrieveResponsePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleMembersRetrieveResponseSecondaryPhoneNumberMax).regex(peopleMembersRetrieveResponseSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersRetrieveResponseEmailMax).optional(),
  "address": zod.string().max(peopleMembersRetrieveResponseAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersRetrieveResponseAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersRetrieveResponseCityMax).optional(),
  "province": zod.string().max(peopleMembersRetrieveResponseProvinceMax).optional(),
  "country": zod.string().max(peopleMembersRetrieveResponseCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersRetrieveResponsePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersRetrieveResponseBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersRetrieveResponseOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersRetrieveResponseEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersRetrieveResponseSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersRetrieveResponseEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersRetrieveResponseEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersRetrieveResponseEmergencyContactPhoneMax).regex(peopleMembersRetrieveResponseEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersRetrieveResponseAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersRetrieveResponseAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})

export const PeopleMembersUpdateParams = zod.object({
  "member_key": zod.string()
})

export const peopleMembersUpdateBodyFirstNameMax = 100;

export const peopleMembersUpdateBodyMiddleNameMax = 100;

export const peopleMembersUpdateBodyMaidenNameMax = 100;

export const peopleMembersUpdateBodyLastNameMax = 100;

export const peopleMembersUpdateBodyPlaceOfBirthMax = 100;

export const peopleMembersUpdateBodyPhoneNumberMax = 17;


export const peopleMembersUpdateBodyPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersUpdateBodySecondaryPhoneNumberMax = 17;


export const peopleMembersUpdateBodySecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersUpdateBodyEmailMax = 254;

export const peopleMembersUpdateBodyAddressMax = 255;

export const peopleMembersUpdateBodyAddressLine2Max = 255;

export const peopleMembersUpdateBodyCityMax = 255;

export const peopleMembersUpdateBodyProvinceMax = 100;

export const peopleMembersUpdateBodyCountryMax = 255;

export const peopleMembersUpdateBodyPreviousChurchMax = 255;

export const peopleMembersUpdateBodyBaptizedWhereMax = 255;

export const peopleMembersUpdateBodyOccupationMax = 255;

export const peopleMembersUpdateBodyEmployerMax = 255;

export const peopleMembersUpdateBodySkillsMax = 255;

export const peopleMembersUpdateBodyEmergencyContactNameMax = 255;

export const peopleMembersUpdateBodyEmergencyContactRelationshipMax = 100;

export const peopleMembersUpdateBodyEmergencyContactPhoneMax = 17;


export const peopleMembersUpdateBodyEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersUpdateBodyAvatarFallbackMax = 64;

export const peopleMembersUpdateBodyAccessPinMax = 128;



export const PeopleMembersUpdateBody = zod.object({
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersUpdateBodyFirstNameMax),
  "middle_name": zod.string().max(peopleMembersUpdateBodyMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersUpdateBodyMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersUpdateBodyLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleMembersUpdateBodyPlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersUpdateBodyPhoneNumberMax).regex(peopleMembersUpdateBodyPhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleMembersUpdateBodySecondaryPhoneNumberMax).regex(peopleMembersUpdateBodySecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersUpdateBodyEmailMax).optional(),
  "address": zod.string().max(peopleMembersUpdateBodyAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersUpdateBodyAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersUpdateBodyCityMax).optional(),
  "province": zod.string().max(peopleMembersUpdateBodyProvinceMax).optional(),
  "country": zod.string().max(peopleMembersUpdateBodyCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersUpdateBodyPreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersUpdateBodyBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersUpdateBodyOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersUpdateBodyEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersUpdateBodySkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersUpdateBodyEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersUpdateBodyEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersUpdateBodyEmergencyContactPhoneMax).regex(peopleMembersUpdateBodyEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersUpdateBodyAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersUpdateBodyAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})

export const peopleMembersUpdateResponseFirstNameMax = 100;

export const peopleMembersUpdateResponseMiddleNameMax = 100;

export const peopleMembersUpdateResponseMaidenNameMax = 100;

export const peopleMembersUpdateResponseLastNameMax = 100;

export const peopleMembersUpdateResponsePlaceOfBirthMax = 100;

export const peopleMembersUpdateResponsePhoneNumberMax = 17;


export const peopleMembersUpdateResponsePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersUpdateResponseSecondaryPhoneNumberMax = 17;


export const peopleMembersUpdateResponseSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersUpdateResponseEmailMax = 254;

export const peopleMembersUpdateResponseAddressMax = 255;

export const peopleMembersUpdateResponseAddressLine2Max = 255;

export const peopleMembersUpdateResponseCityMax = 255;

export const peopleMembersUpdateResponseProvinceMax = 100;

export const peopleMembersUpdateResponseCountryMax = 255;

export const peopleMembersUpdateResponsePreviousChurchMax = 255;

export const peopleMembersUpdateResponseBaptizedWhereMax = 255;

export const peopleMembersUpdateResponseOccupationMax = 255;

export const peopleMembersUpdateResponseEmployerMax = 255;

export const peopleMembersUpdateResponseSkillsMax = 255;

export const peopleMembersUpdateResponseEmergencyContactNameMax = 255;

export const peopleMembersUpdateResponseEmergencyContactRelationshipMax = 100;

export const peopleMembersUpdateResponseEmergencyContactPhoneMax = 17;


export const peopleMembersUpdateResponseEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersUpdateResponseAvatarFallbackMax = 64;

export const peopleMembersUpdateResponseAccessPinMax = 128;



export const PeopleMembersUpdateResponse = zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersUpdateResponseFirstNameMax),
  "middle_name": zod.string().max(peopleMembersUpdateResponseMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersUpdateResponseMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersUpdateResponseLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleMembersUpdateResponsePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersUpdateResponsePhoneNumberMax).regex(peopleMembersUpdateResponsePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleMembersUpdateResponseSecondaryPhoneNumberMax).regex(peopleMembersUpdateResponseSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersUpdateResponseEmailMax).optional(),
  "address": zod.string().max(peopleMembersUpdateResponseAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersUpdateResponseAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersUpdateResponseCityMax).optional(),
  "province": zod.string().max(peopleMembersUpdateResponseProvinceMax).optional(),
  "country": zod.string().max(peopleMembersUpdateResponseCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersUpdateResponsePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersUpdateResponseBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersUpdateResponseOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersUpdateResponseEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersUpdateResponseSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersUpdateResponseEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersUpdateResponseEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersUpdateResponseEmergencyContactPhoneMax).regex(peopleMembersUpdateResponseEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersUpdateResponseAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersUpdateResponseAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})

export const PeopleMembersPartialUpdateParams = zod.object({
  "member_key": zod.string()
})

export const peopleMembersPartialUpdateBodyFirstNameMax = 100;

export const peopleMembersPartialUpdateBodyMiddleNameMax = 100;

export const peopleMembersPartialUpdateBodyMaidenNameMax = 100;

export const peopleMembersPartialUpdateBodyLastNameMax = 100;

export const peopleMembersPartialUpdateBodyPlaceOfBirthMax = 100;

export const peopleMembersPartialUpdateBodyPhoneNumberMax = 17;


export const peopleMembersPartialUpdateBodyPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersPartialUpdateBodySecondaryPhoneNumberMax = 17;


export const peopleMembersPartialUpdateBodySecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersPartialUpdateBodyEmailMax = 254;

export const peopleMembersPartialUpdateBodyAddressMax = 255;

export const peopleMembersPartialUpdateBodyAddressLine2Max = 255;

export const peopleMembersPartialUpdateBodyCityMax = 255;

export const peopleMembersPartialUpdateBodyProvinceMax = 100;

export const peopleMembersPartialUpdateBodyCountryMax = 255;

export const peopleMembersPartialUpdateBodyPreviousChurchMax = 255;

export const peopleMembersPartialUpdateBodyBaptizedWhereMax = 255;

export const peopleMembersPartialUpdateBodyOccupationMax = 255;

export const peopleMembersPartialUpdateBodyEmployerMax = 255;

export const peopleMembersPartialUpdateBodySkillsMax = 255;

export const peopleMembersPartialUpdateBodyEmergencyContactNameMax = 255;

export const peopleMembersPartialUpdateBodyEmergencyContactRelationshipMax = 100;

export const peopleMembersPartialUpdateBodyEmergencyContactPhoneMax = 17;


export const peopleMembersPartialUpdateBodyEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersPartialUpdateBodyAvatarFallbackMax = 64;

export const peopleMembersPartialUpdateBodyAccessPinMax = 128;



export const PeopleMembersPartialUpdateBody = zod.object({
  "ministries": zod.array(zod.string()).optional(),
  "positions": zod.array(zod.string()).optional(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersPartialUpdateBodyFirstNameMax).optional(),
  "middle_name": zod.string().max(peopleMembersPartialUpdateBodyMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersPartialUpdateBodyMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersPartialUpdateBodyLastNameMax).optional(),
  "date_of_birth": zod.iso.date().optional(),
  "place_of_birth": zod.string().max(peopleMembersPartialUpdateBodyPlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).optional().describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersPartialUpdateBodyPhoneNumberMax).regex(peopleMembersPartialUpdateBodyPhoneNumberRegExp).optional(),
  "secondary_phone_number": zod.string().max(peopleMembersPartialUpdateBodySecondaryPhoneNumberMax).regex(peopleMembersPartialUpdateBodySecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersPartialUpdateBodyEmailMax).optional(),
  "address": zod.string().max(peopleMembersPartialUpdateBodyAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersPartialUpdateBodyAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersPartialUpdateBodyCityMax).optional(),
  "province": zod.string().max(peopleMembersPartialUpdateBodyProvinceMax).optional(),
  "country": zod.string().max(peopleMembersPartialUpdateBodyCountryMax).optional(),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersPartialUpdateBodyPreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersPartialUpdateBodyBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersPartialUpdateBodyOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersPartialUpdateBodyEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersPartialUpdateBodySkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersPartialUpdateBodyEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersPartialUpdateBodyEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersPartialUpdateBodyEmergencyContactPhoneMax).regex(peopleMembersPartialUpdateBodyEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersPartialUpdateBodyAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersPartialUpdateBodyAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "assembly": zod.number().optional(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})

export const peopleMembersPartialUpdateResponseFirstNameMax = 100;

export const peopleMembersPartialUpdateResponseMiddleNameMax = 100;

export const peopleMembersPartialUpdateResponseMaidenNameMax = 100;

export const peopleMembersPartialUpdateResponseLastNameMax = 100;

export const peopleMembersPartialUpdateResponsePlaceOfBirthMax = 100;

export const peopleMembersPartialUpdateResponsePhoneNumberMax = 17;


export const peopleMembersPartialUpdateResponsePhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersPartialUpdateResponseSecondaryPhoneNumberMax = 17;


export const peopleMembersPartialUpdateResponseSecondaryPhoneNumberRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersPartialUpdateResponseEmailMax = 254;

export const peopleMembersPartialUpdateResponseAddressMax = 255;

export const peopleMembersPartialUpdateResponseAddressLine2Max = 255;

export const peopleMembersPartialUpdateResponseCityMax = 255;

export const peopleMembersPartialUpdateResponseProvinceMax = 100;

export const peopleMembersPartialUpdateResponseCountryMax = 255;

export const peopleMembersPartialUpdateResponsePreviousChurchMax = 255;

export const peopleMembersPartialUpdateResponseBaptizedWhereMax = 255;

export const peopleMembersPartialUpdateResponseOccupationMax = 255;

export const peopleMembersPartialUpdateResponseEmployerMax = 255;

export const peopleMembersPartialUpdateResponseSkillsMax = 255;

export const peopleMembersPartialUpdateResponseEmergencyContactNameMax = 255;

export const peopleMembersPartialUpdateResponseEmergencyContactRelationshipMax = 100;

export const peopleMembersPartialUpdateResponseEmergencyContactPhoneMax = 17;


export const peopleMembersPartialUpdateResponseEmergencyContactPhoneRegExp = new RegExp('^\\+?1?\\d{9,15}$');
export const peopleMembersPartialUpdateResponseAvatarFallbackMax = 64;

export const peopleMembersPartialUpdateResponseAccessPinMax = 128;



export const PeopleMembersPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "full_name": zod.string(),
  "age": zod.string(),
  "spouse_full_name": zod.string(),
  "ministries": zod.array(zod.string()),
  "positions": zod.array(zod.string()),
  "member_key": zod.string(),
  "prefix": zod.union([zod.enum(['Advocate', 'Dr', 'Eng', 'Hon', 'Miss', 'Mr', 'Mrs', 'Ms', 'Prof', 'Rev']).describe('\* `Advocate` - Advocate\n\* `Dr` - Dr\n\* `Eng` - Eng\n\* `Hon` - Hon\n\* `Miss` - Miss\n\* `Mr` - Mr\n\* `Mrs` - Mrs\n\* `Ms` - Ms\n\* `Prof` - Prof\n\* `Rev` - Rev'),zod.enum([''])]).optional(),
  "first_name": zod.string().max(peopleMembersPartialUpdateResponseFirstNameMax),
  "middle_name": zod.string().max(peopleMembersPartialUpdateResponseMiddleNameMax).optional(),
  "maiden_name": zod.string().max(peopleMembersPartialUpdateResponseMaidenNameMax).optional(),
  "last_name": zod.string().max(peopleMembersPartialUpdateResponseLastNameMax),
  "date_of_birth": zod.iso.date(),
  "place_of_birth": zod.string().max(peopleMembersPartialUpdateResponsePlaceOfBirthMax).optional(),
  "gender": zod.enum(['Male', 'Female']).describe('\* `Male` - Male\n\* `Female` - Female'),
  "relationship": zod.union([zod.enum(['Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Engaged', 'In a Relationship', 'Domestic Partnership', 'Civil Union', 'Committed', 'Common-Law Marriage', 'Traditional Marriage', 'Co-parenting']).describe('\* `Single` - Single\n\* `Married` - Married\n\* `Divorced` - Divorced\n\* `Widowed` - Widowed\n\* `Separated` - Separated\n\* `Engaged` - Engaged\n\* `In a Relationship` - In a Relationship\n\* `Domestic Partnership` - Domestic Partnership\n\* `Civil Union` - Civil Union\n\* `Committed` - Committed\n\* `Common-Law Marriage` - Common-Law Marriage\n\* `Traditional Marriage` - Traditional Marriage\n\* `Co-parenting` - Co-parenting'),zod.enum([''])]).optional(),
  "marriage_date": zod.iso.date().nullish(),
  "phone_number": zod.string().max(peopleMembersPartialUpdateResponsePhoneNumberMax).regex(peopleMembersPartialUpdateResponsePhoneNumberRegExp),
  "secondary_phone_number": zod.string().max(peopleMembersPartialUpdateResponseSecondaryPhoneNumberMax).regex(peopleMembersPartialUpdateResponseSecondaryPhoneNumberRegExp).optional(),
  "email": zod.email().max(peopleMembersPartialUpdateResponseEmailMax).optional(),
  "address": zod.string().max(peopleMembersPartialUpdateResponseAddressMax).optional(),
  "address_line2": zod.string().max(peopleMembersPartialUpdateResponseAddressLine2Max).optional(),
  "city": zod.string().max(peopleMembersPartialUpdateResponseCityMax).optional(),
  "province": zod.string().max(peopleMembersPartialUpdateResponseProvinceMax).optional(),
  "country": zod.string().max(peopleMembersPartialUpdateResponseCountryMax),
  "membersince": zod.iso.date().nullish(),
  "membership_status": zod.union([zod.enum(['Visitor', 'Regular', 'Established', 'Relocated', 'Inactive', 'Transferred', 'Deceased']).describe('\* `Visitor` - Visitor\n\* `Regular` - Regular Attendee\n\* `Established` - Established\n\* `Relocated` - Relocated (Living Abroad)\n\* `Inactive` - Inactive\n\* `Transferred` - Transferred to Another Church\n\* `Deceased` - Deceased'),zod.enum([''])]).optional(),
  "previous_church": zod.string().max(peopleMembersPartialUpdateResponsePreviousChurchMax).optional(),
  "baptized": zod.boolean().optional(),
  "baptized_at": zod.iso.date().nullish(),
  "baptized_where": zod.string().max(peopleMembersPartialUpdateResponseBaptizedWhereMax).optional(),
  "confirmation_date": zod.iso.date().nullish(),
  "occupation": zod.string().max(peopleMembersPartialUpdateResponseOccupationMax).optional(),
  "employer": zod.string().max(peopleMembersPartialUpdateResponseEmployerMax).optional(),
  "education_level": zod.union([zod.enum(['Primary', 'Secondary', 'Diploma', 'Bachelor\'s Degree', 'Master\'s Degree', 'Doctorate', 'Other']).describe('\* `Primary` - Primary\n\* `Secondary` - Secondary\n\* `Diploma` - Diploma\n\* `Bachelor\'s Degree` - Bachelor\'s Degree\n\* `Master\'s Degree` - Master\'s Degree\n\* `Doctorate` - Doctorate\n\* `Other` - Other'),zod.enum([''])]).optional(),
  "skills": zod.string().max(peopleMembersPartialUpdateResponseSkillsMax).optional(),
  "emergency_contact_name": zod.string().max(peopleMembersPartialUpdateResponseEmergencyContactNameMax).optional(),
  "emergency_contact_relationship": zod.string().max(peopleMembersPartialUpdateResponseEmergencyContactRelationshipMax).optional(),
  "emergency_contact_phone": zod.string().max(peopleMembersPartialUpdateResponseEmergencyContactPhoneMax).regex(peopleMembersPartialUpdateResponseEmergencyContactPhoneRegExp).optional(),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(peopleMembersPartialUpdateResponseAvatarFallbackMax).optional(),
  "notes": zod.string().optional(),
  "pin_set": zod.boolean().optional(),
  "access_pin": zod.string().max(peopleMembersPartialUpdateResponseAccessPinMax).optional(),
  "is_trash": zod.boolean().optional(),
  "trash_date": zod.iso.datetime({}).nullish(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number(),
  "created_by": zod.number().nullish(),
  "updated_by": zod.number().nullish(),
  "spouse": zod.number().nullish()
})

export const PeopleMembersDestroyParams = zod.object({
  "member_key": zod.string()
})

