/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const PostsPostCommentCreateBody = zod.object({
  "body": zod.string(),
  "post": zod.number(),
  "author": zod.number()
})

export const PostsPostCommentDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this comment.')
})

export const postsPostCreateListResponseTitleMax = 255;

export const postsPostCreateListResponseSlugMax = 255;


export const postsPostCreateListResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreateListResponseViewsMin = 0;
export const postsPostCreateListResponseViewsMax = 9223372036854776000;

export const postsPostCreateListResponseImagesItemAltMax = 255;



export const PostsPostCreateListResponseItem = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostCreateListResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreateListResponseSlugMax).regex(postsPostCreateListResponseSlugRegExp).optional(),
  "views": zod.number().min(postsPostCreateListResponseViewsMin).max(postsPostCreateListResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostCreateListResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const PostsPostCreateListResponse = zod.array(PostsPostCreateListResponseItem)

export const postsPostCreateCreateBodyTitleMax = 255;

export const postsPostCreateCreateBodySlugMax = 255;


export const postsPostCreateCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreateCreateBodyViewsMin = 0;
export const postsPostCreateCreateBodyViewsMax = 9223372036854776000;



export const PostsPostCreateCreateBody = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostCreateCreateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreateCreateBodySlugMax).regex(postsPostCreateCreateBodySlugRegExp).optional(),
  "views": zod.number().min(postsPostCreateCreateBodyViewsMin).max(postsPostCreateCreateBodyViewsMax).optional(),
  "uploaded_images": zod.array(zod.string())
})

export const PostsPostCreateRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostCreateRetrieveResponseTitleMax = 255;

export const postsPostCreateRetrieveResponseSlugMax = 255;


export const postsPostCreateRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreateRetrieveResponseViewsMin = 0;
export const postsPostCreateRetrieveResponseViewsMax = 9223372036854776000;

export const postsPostCreateRetrieveResponseImagesItemAltMax = 255;



export const PostsPostCreateRetrieveResponse = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostCreateRetrieveResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreateRetrieveResponseSlugMax).regex(postsPostCreateRetrieveResponseSlugRegExp).optional(),
  "views": zod.number().min(postsPostCreateRetrieveResponseViewsMin).max(postsPostCreateRetrieveResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostCreateRetrieveResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostsPostCreateUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostCreateUpdateBodyTitleMax = 255;

export const postsPostCreateUpdateBodySlugMax = 255;


export const postsPostCreateUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreateUpdateBodyViewsMin = 0;
export const postsPostCreateUpdateBodyViewsMax = 9223372036854776000;



export const PostsPostCreateUpdateBody = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostCreateUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreateUpdateBodySlugMax).regex(postsPostCreateUpdateBodySlugRegExp).optional(),
  "views": zod.number().min(postsPostCreateUpdateBodyViewsMin).max(postsPostCreateUpdateBodyViewsMax).optional(),
  "uploaded_images": zod.array(zod.string())
})

export const postsPostCreateUpdateResponseTitleMax = 255;

export const postsPostCreateUpdateResponseSlugMax = 255;


export const postsPostCreateUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreateUpdateResponseViewsMin = 0;
export const postsPostCreateUpdateResponseViewsMax = 9223372036854776000;

export const postsPostCreateUpdateResponseImagesItemAltMax = 255;



export const PostsPostCreateUpdateResponse = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostCreateUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreateUpdateResponseSlugMax).regex(postsPostCreateUpdateResponseSlugRegExp).optional(),
  "views": zod.number().min(postsPostCreateUpdateResponseViewsMin).max(postsPostCreateUpdateResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostCreateUpdateResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostsPostCreatePartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostCreatePartialUpdateBodyTitleMax = 255;

export const postsPostCreatePartialUpdateBodySlugMax = 255;


export const postsPostCreatePartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreatePartialUpdateBodyViewsMin = 0;
export const postsPostCreatePartialUpdateBodyViewsMax = 9223372036854776000;



export const PostsPostCreatePartialUpdateBody = zod.object({
  "author": zod.number().optional(),
  "assembly": zod.number().optional(),
  "title": zod.string().max(postsPostCreatePartialUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreatePartialUpdateBodySlugMax).regex(postsPostCreatePartialUpdateBodySlugRegExp).optional(),
  "views": zod.number().min(postsPostCreatePartialUpdateBodyViewsMin).max(postsPostCreatePartialUpdateBodyViewsMax).optional(),
  "uploaded_images": zod.array(zod.string()).optional()
})

export const postsPostCreatePartialUpdateResponseTitleMax = 255;

export const postsPostCreatePartialUpdateResponseSlugMax = 255;


export const postsPostCreatePartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostCreatePartialUpdateResponseViewsMin = 0;
export const postsPostCreatePartialUpdateResponseViewsMax = 9223372036854776000;

export const postsPostCreatePartialUpdateResponseImagesItemAltMax = 255;



export const PostsPostCreatePartialUpdateResponse = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostCreatePartialUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostCreatePartialUpdateResponseSlugMax).regex(postsPostCreatePartialUpdateResponseSlugRegExp).optional(),
  "views": zod.number().min(postsPostCreatePartialUpdateResponseViewsMin).max(postsPostCreatePartialUpdateResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostCreatePartialUpdateResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostsPostCreateDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostUpdateListResponseTitleMax = 255;

export const postsPostUpdateListResponseViewsMin = 0;
export const postsPostUpdateListResponseViewsMax = 9223372036854776000;

export const postsPostUpdateListResponseSlugMax = 255;


export const postsPostUpdateListResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdateListResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string().max(postsPostUpdateListResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdateListResponseViewsMin).max(postsPostUpdateListResponseViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdateListResponseSlugMax).regex(postsPostUpdateListResponseSlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "author": zod.number(),
  "assembly": zod.number(),
  "likes": zod.array(zod.number()).optional()
})
export const PostsPostUpdateListResponse = zod.array(PostsPostUpdateListResponseItem)

export const postsPostUpdateCreateBodyTitleMax = 255;

export const postsPostUpdateCreateBodyViewsMin = 0;
export const postsPostUpdateCreateBodyViewsMax = 9223372036854776000;

export const postsPostUpdateCreateBodySlugMax = 255;


export const postsPostUpdateCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdateCreateBody = zod.object({
  "title": zod.string().max(postsPostUpdateCreateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdateCreateBodyViewsMin).max(postsPostUpdateCreateBodyViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdateCreateBodySlugMax).regex(postsPostUpdateCreateBodySlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "author": zod.number(),
  "assembly": zod.number(),
  "likes": zod.array(zod.number()).optional()
})

export const PostsPostUpdateRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostUpdateRetrieveResponseTitleMax = 255;

export const postsPostUpdateRetrieveResponseViewsMin = 0;
export const postsPostUpdateRetrieveResponseViewsMax = 9223372036854776000;

export const postsPostUpdateRetrieveResponseSlugMax = 255;


export const postsPostUpdateRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdateRetrieveResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(postsPostUpdateRetrieveResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdateRetrieveResponseViewsMin).max(postsPostUpdateRetrieveResponseViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdateRetrieveResponseSlugMax).regex(postsPostUpdateRetrieveResponseSlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "author": zod.number(),
  "assembly": zod.number(),
  "likes": zod.array(zod.number()).optional()
})

export const PostsPostUpdateUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostUpdateUpdateBodyTitleMax = 255;

export const postsPostUpdateUpdateBodyViewsMin = 0;
export const postsPostUpdateUpdateBodyViewsMax = 9223372036854776000;

export const postsPostUpdateUpdateBodySlugMax = 255;


export const postsPostUpdateUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdateUpdateBody = zod.object({
  "title": zod.string().max(postsPostUpdateUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdateUpdateBodyViewsMin).max(postsPostUpdateUpdateBodyViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdateUpdateBodySlugMax).regex(postsPostUpdateUpdateBodySlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "author": zod.number(),
  "assembly": zod.number(),
  "likes": zod.array(zod.number()).optional()
})

export const postsPostUpdateUpdateResponseTitleMax = 255;

export const postsPostUpdateUpdateResponseViewsMin = 0;
export const postsPostUpdateUpdateResponseViewsMax = 9223372036854776000;

export const postsPostUpdateUpdateResponseSlugMax = 255;


export const postsPostUpdateUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdateUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(postsPostUpdateUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdateUpdateResponseViewsMin).max(postsPostUpdateUpdateResponseViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdateUpdateResponseSlugMax).regex(postsPostUpdateUpdateResponseSlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "author": zod.number(),
  "assembly": zod.number(),
  "likes": zod.array(zod.number()).optional()
})

export const PostsPostUpdatePartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostUpdatePartialUpdateBodyTitleMax = 255;

export const postsPostUpdatePartialUpdateBodyViewsMin = 0;
export const postsPostUpdatePartialUpdateBodyViewsMax = 9223372036854776000;

export const postsPostUpdatePartialUpdateBodySlugMax = 255;


export const postsPostUpdatePartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdatePartialUpdateBody = zod.object({
  "title": zod.string().max(postsPostUpdatePartialUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdatePartialUpdateBodyViewsMin).max(postsPostUpdatePartialUpdateBodyViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdatePartialUpdateBodySlugMax).regex(postsPostUpdatePartialUpdateBodySlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "author": zod.number().optional(),
  "assembly": zod.number().optional(),
  "likes": zod.array(zod.number()).optional()
})

export const postsPostUpdatePartialUpdateResponseTitleMax = 255;

export const postsPostUpdatePartialUpdateResponseViewsMin = 0;
export const postsPostUpdatePartialUpdateResponseViewsMax = 9223372036854776000;

export const postsPostUpdatePartialUpdateResponseSlugMax = 255;


export const postsPostUpdatePartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostsPostUpdatePartialUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(postsPostUpdatePartialUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "image": zod.url().nullish(),
  "views": zod.number().min(postsPostUpdatePartialUpdateResponseViewsMin).max(postsPostUpdatePartialUpdateResponseViewsMax).optional(),
  "slug": zod.string().max(postsPostUpdatePartialUpdateResponseSlugMax).regex(postsPostUpdatePartialUpdateResponseSlugRegExp).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "author": zod.number(),
  "assembly": zod.number(),
  "likes": zod.array(zod.number()).optional()
})

export const PostsPostUpdateDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const PostsPostsListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const postsPostsListResponseResultsItemAuthorFirstNameMax = 255;

export const postsPostsListResponseResultsItemAuthorLastNameMax = 255;

export const postsPostsListResponseResultsItemAuthorChurchNameMax = 100;

export const postsPostsListResponseResultsItemAuthorChurchCountryMax = 100;

export const postsPostsListResponseResultsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsListResponseResultsItemAuthorAvatarFallbackMax = 26;

export const postsPostsListResponseResultsItemAssemblyNameMax = 100;

export const postsPostsListResponseResultsItemAssemblyCountryCodeMax = 3;

export const postsPostsListResponseResultsItemAssemblyLanguageMax = 12;

export const postsPostsListResponseResultsItemAssemblyCurrencyMax = 12;

export const postsPostsListResponseResultsItemAssemblyAvatarFallbackMax = 36;

export const postsPostsListResponseResultsItemTitleMax = 255;

export const postsPostsListResponseResultsItemSlugMax = 255;


export const postsPostsListResponseResultsItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsListResponseResultsItemLikesItemFirstNameMax = 255;

export const postsPostsListResponseResultsItemLikesItemLastNameMax = 255;

export const postsPostsListResponseResultsItemLikesItemChurchNameMax = 100;

export const postsPostsListResponseResultsItemLikesItemChurchCountryMax = 100;

export const postsPostsListResponseResultsItemLikesItemChurchAvatarFallbackMax = 36;

export const postsPostsListResponseResultsItemLikesItemAvatarFallbackMax = 26;

export const postsPostsListResponseResultsItemViewsMin = 0;
export const postsPostsListResponseResultsItemViewsMax = 9223372036854776000;

export const postsPostsListResponseResultsItemImagesItemAltMax = 255;

export const postsPostsListResponseResultsItemCommentsItemAuthorFirstNameMax = 255;

export const postsPostsListResponseResultsItemCommentsItemAuthorLastNameMax = 255;

export const postsPostsListResponseResultsItemCommentsItemAuthorChurchNameMax = 100;

export const postsPostsListResponseResultsItemCommentsItemAuthorChurchCountryMax = 100;

export const postsPostsListResponseResultsItemCommentsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsListResponseResultsItemCommentsItemAuthorAvatarFallbackMax = 26;



export const PostsPostsListResponse = zod.object({
  "count": zod.number(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsListResponseResultsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsListResponseResultsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsListResponseResultsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsListResponseResultsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemAuthorAvatarFallbackMax).optional()
}),
  "assembly": zod.object({
  "id": zod.number(),
  "name": zod.string().max(postsPostsListResponseResultsItemAssemblyNameMax),
  "zone": zod.number().nullish(),
  "country_code": zod.string().max(postsPostsListResponseResultsItemAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(postsPostsListResponseResultsItemAssemblyLanguageMax).optional(),
  "currency": zod.string().max(postsPostsListResponseResultsItemAssemblyCurrencyMax).optional(),
  "avatar": zod.url().optional(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemAssemblyAvatarFallbackMax).optional()
}),
  "title": zod.string().max(postsPostsListResponseResultsItemTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsListResponseResultsItemSlugMax).regex(postsPostsListResponseResultsItemSlugRegExp).optional(),
  "likes": zod.array(zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsListResponseResultsItemLikesItemFirstNameMax),
  "last_name": zod.string().max(postsPostsListResponseResultsItemLikesItemLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsListResponseResultsItemLikesItemChurchNameMax),
  "country": zod.string().max(postsPostsListResponseResultsItemLikesItemChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemLikesItemChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemLikesItemAvatarFallbackMax).optional()
})),
  "views": zod.number().min(postsPostsListResponseResultsItemViewsMin).max(postsPostsListResponseResultsItemViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostsListResponseResultsItemImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "comments": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsListResponseResultsItemCommentsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsListResponseResultsItemCommentsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsListResponseResultsItemCommentsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsListResponseResultsItemCommentsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemCommentsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsListResponseResultsItemCommentsItemAuthorAvatarFallbackMax).optional()
}),
  "body": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}))
})

export const postsPostsCreateBodyTitleMax = 255;

export const postsPostsCreateBodySlugMax = 255;


export const postsPostsCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsCreateBodyViewsMin = 0;
export const postsPostsCreateBodyViewsMax = 9223372036854776000;



export const PostsPostsCreateBody = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postsPostsCreateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsCreateBodySlugMax).regex(postsPostsCreateBodySlugRegExp).optional(),
  "views": zod.number().min(postsPostsCreateBodyViewsMin).max(postsPostsCreateBodyViewsMax).optional(),
  "uploaded_images": zod.array(zod.string())
})

export const PostsPostsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostsRetrieveResponseAuthorFirstNameMax = 255;

export const postsPostsRetrieveResponseAuthorLastNameMax = 255;

export const postsPostsRetrieveResponseAuthorChurchNameMax = 100;

export const postsPostsRetrieveResponseAuthorChurchCountryMax = 100;

export const postsPostsRetrieveResponseAuthorChurchAvatarFallbackMax = 36;

export const postsPostsRetrieveResponseAuthorAvatarFallbackMax = 26;

export const postsPostsRetrieveResponseAssemblyNameMax = 100;

export const postsPostsRetrieveResponseAssemblyCountryCodeMax = 3;

export const postsPostsRetrieveResponseAssemblyLanguageMax = 12;

export const postsPostsRetrieveResponseAssemblyCurrencyMax = 12;

export const postsPostsRetrieveResponseAssemblyAvatarFallbackMax = 36;

export const postsPostsRetrieveResponseTitleMax = 255;

export const postsPostsRetrieveResponseSlugMax = 255;


export const postsPostsRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsRetrieveResponseLikesItemFirstNameMax = 255;

export const postsPostsRetrieveResponseLikesItemLastNameMax = 255;

export const postsPostsRetrieveResponseLikesItemChurchNameMax = 100;

export const postsPostsRetrieveResponseLikesItemChurchCountryMax = 100;

export const postsPostsRetrieveResponseLikesItemChurchAvatarFallbackMax = 36;

export const postsPostsRetrieveResponseLikesItemAvatarFallbackMax = 26;

export const postsPostsRetrieveResponseViewsMin = 0;
export const postsPostsRetrieveResponseViewsMax = 9223372036854776000;

export const postsPostsRetrieveResponseImagesItemAltMax = 255;

export const postsPostsRetrieveResponseCommentsItemAuthorFirstNameMax = 255;

export const postsPostsRetrieveResponseCommentsItemAuthorLastNameMax = 255;

export const postsPostsRetrieveResponseCommentsItemAuthorChurchNameMax = 100;

export const postsPostsRetrieveResponseCommentsItemAuthorChurchCountryMax = 100;

export const postsPostsRetrieveResponseCommentsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsRetrieveResponseCommentsItemAuthorAvatarFallbackMax = 26;



export const PostsPostsRetrieveResponse = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsRetrieveResponseAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsRetrieveResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsRetrieveResponseAuthorChurchNameMax),
  "country": zod.string().max(postsPostsRetrieveResponseAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseAuthorAvatarFallbackMax).optional()
}),
  "assembly": zod.object({
  "id": zod.number(),
  "name": zod.string().max(postsPostsRetrieveResponseAssemblyNameMax),
  "zone": zod.number().nullish(),
  "country_code": zod.string().max(postsPostsRetrieveResponseAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(postsPostsRetrieveResponseAssemblyLanguageMax).optional(),
  "currency": zod.string().max(postsPostsRetrieveResponseAssemblyCurrencyMax).optional(),
  "avatar": zod.url().optional(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseAssemblyAvatarFallbackMax).optional()
}),
  "title": zod.string().max(postsPostsRetrieveResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsRetrieveResponseSlugMax).regex(postsPostsRetrieveResponseSlugRegExp).optional(),
  "likes": zod.array(zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsRetrieveResponseLikesItemFirstNameMax),
  "last_name": zod.string().max(postsPostsRetrieveResponseLikesItemLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsRetrieveResponseLikesItemChurchNameMax),
  "country": zod.string().max(postsPostsRetrieveResponseLikesItemChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseLikesItemChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseLikesItemAvatarFallbackMax).optional()
})),
  "views": zod.number().min(postsPostsRetrieveResponseViewsMin).max(postsPostsRetrieveResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostsRetrieveResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "comments": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsRetrieveResponseCommentsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsRetrieveResponseCommentsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsRetrieveResponseCommentsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsRetrieveResponseCommentsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseCommentsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsRetrieveResponseCommentsItemAuthorAvatarFallbackMax).optional()
}),
  "body": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostsPostsUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostsUpdateBodyAuthorFirstNameMax = 255;

export const postsPostsUpdateBodyAuthorLastNameMax = 255;

export const postsPostsUpdateBodyAuthorChurchNameMax = 100;

export const postsPostsUpdateBodyAuthorChurchCountryMax = 100;

export const postsPostsUpdateBodyAuthorChurchAvatarFallbackMax = 36;

export const postsPostsUpdateBodyAuthorAvatarFallbackMax = 26;

export const postsPostsUpdateBodyAssemblyNameMax = 100;

export const postsPostsUpdateBodyAssemblyCountryCodeMax = 3;

export const postsPostsUpdateBodyAssemblyLanguageMax = 12;

export const postsPostsUpdateBodyAssemblyCurrencyMax = 12;

export const postsPostsUpdateBodyAssemblyAvatarFallbackMax = 36;

export const postsPostsUpdateBodyTitleMax = 255;

export const postsPostsUpdateBodySlugMax = 255;


export const postsPostsUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsUpdateBodyLikesItemFirstNameMax = 255;

export const postsPostsUpdateBodyLikesItemLastNameMax = 255;

export const postsPostsUpdateBodyLikesItemChurchNameMax = 100;

export const postsPostsUpdateBodyLikesItemChurchCountryMax = 100;

export const postsPostsUpdateBodyLikesItemChurchAvatarFallbackMax = 36;

export const postsPostsUpdateBodyLikesItemAvatarFallbackMax = 26;

export const postsPostsUpdateBodyViewsMin = 0;
export const postsPostsUpdateBodyViewsMax = 9223372036854776000;

export const postsPostsUpdateBodyCommentsItemAuthorFirstNameMax = 255;

export const postsPostsUpdateBodyCommentsItemAuthorLastNameMax = 255;

export const postsPostsUpdateBodyCommentsItemAuthorChurchNameMax = 100;

export const postsPostsUpdateBodyCommentsItemAuthorChurchCountryMax = 100;

export const postsPostsUpdateBodyCommentsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsUpdateBodyCommentsItemAuthorAvatarFallbackMax = 26;



export const PostsPostsUpdateBody = zod.object({
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsUpdateBodyAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsUpdateBodyAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsUpdateBodyAuthorChurchNameMax),
  "country": zod.string().max(postsPostsUpdateBodyAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyAuthorAvatarFallbackMax).optional()
}),
  "assembly": zod.object({
  "id": zod.number(),
  "name": zod.string().max(postsPostsUpdateBodyAssemblyNameMax),
  "zone": zod.number().nullish(),
  "country_code": zod.string().max(postsPostsUpdateBodyAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(postsPostsUpdateBodyAssemblyLanguageMax).optional(),
  "currency": zod.string().max(postsPostsUpdateBodyAssemblyCurrencyMax).optional(),
  "avatar": zod.url().optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyAssemblyAvatarFallbackMax).optional()
}),
  "title": zod.string().max(postsPostsUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsUpdateBodySlugMax).regex(postsPostsUpdateBodySlugRegExp).optional(),
  "likes": zod.array(zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsUpdateBodyLikesItemFirstNameMax),
  "last_name": zod.string().max(postsPostsUpdateBodyLikesItemLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsUpdateBodyLikesItemChurchNameMax),
  "country": zod.string().max(postsPostsUpdateBodyLikesItemChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyLikesItemChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyLikesItemAvatarFallbackMax).optional()
})),
  "views": zod.number().min(postsPostsUpdateBodyViewsMin).max(postsPostsUpdateBodyViewsMax).optional(),
  "comments": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsUpdateBodyCommentsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsUpdateBodyCommentsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsUpdateBodyCommentsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsUpdateBodyCommentsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyCommentsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsUpdateBodyCommentsItemAuthorAvatarFallbackMax).optional()
}),
  "body": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft')
})

export const postsPostsUpdateResponseAuthorFirstNameMax = 255;

export const postsPostsUpdateResponseAuthorLastNameMax = 255;

export const postsPostsUpdateResponseAuthorChurchNameMax = 100;

export const postsPostsUpdateResponseAuthorChurchCountryMax = 100;

export const postsPostsUpdateResponseAuthorChurchAvatarFallbackMax = 36;

export const postsPostsUpdateResponseAuthorAvatarFallbackMax = 26;

export const postsPostsUpdateResponseAssemblyNameMax = 100;

export const postsPostsUpdateResponseAssemblyCountryCodeMax = 3;

export const postsPostsUpdateResponseAssemblyLanguageMax = 12;

export const postsPostsUpdateResponseAssemblyCurrencyMax = 12;

export const postsPostsUpdateResponseAssemblyAvatarFallbackMax = 36;

export const postsPostsUpdateResponseTitleMax = 255;

export const postsPostsUpdateResponseSlugMax = 255;


export const postsPostsUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsUpdateResponseLikesItemFirstNameMax = 255;

export const postsPostsUpdateResponseLikesItemLastNameMax = 255;

export const postsPostsUpdateResponseLikesItemChurchNameMax = 100;

export const postsPostsUpdateResponseLikesItemChurchCountryMax = 100;

export const postsPostsUpdateResponseLikesItemChurchAvatarFallbackMax = 36;

export const postsPostsUpdateResponseLikesItemAvatarFallbackMax = 26;

export const postsPostsUpdateResponseViewsMin = 0;
export const postsPostsUpdateResponseViewsMax = 9223372036854776000;

export const postsPostsUpdateResponseImagesItemAltMax = 255;

export const postsPostsUpdateResponseCommentsItemAuthorFirstNameMax = 255;

export const postsPostsUpdateResponseCommentsItemAuthorLastNameMax = 255;

export const postsPostsUpdateResponseCommentsItemAuthorChurchNameMax = 100;

export const postsPostsUpdateResponseCommentsItemAuthorChurchCountryMax = 100;

export const postsPostsUpdateResponseCommentsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsUpdateResponseCommentsItemAuthorAvatarFallbackMax = 26;



export const PostsPostsUpdateResponse = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsUpdateResponseAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsUpdateResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsUpdateResponseAuthorChurchNameMax),
  "country": zod.string().max(postsPostsUpdateResponseAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseAuthorAvatarFallbackMax).optional()
}),
  "assembly": zod.object({
  "id": zod.number(),
  "name": zod.string().max(postsPostsUpdateResponseAssemblyNameMax),
  "zone": zod.number().nullish(),
  "country_code": zod.string().max(postsPostsUpdateResponseAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(postsPostsUpdateResponseAssemblyLanguageMax).optional(),
  "currency": zod.string().max(postsPostsUpdateResponseAssemblyCurrencyMax).optional(),
  "avatar": zod.url().optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseAssemblyAvatarFallbackMax).optional()
}),
  "title": zod.string().max(postsPostsUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsUpdateResponseSlugMax).regex(postsPostsUpdateResponseSlugRegExp).optional(),
  "likes": zod.array(zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsUpdateResponseLikesItemFirstNameMax),
  "last_name": zod.string().max(postsPostsUpdateResponseLikesItemLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsUpdateResponseLikesItemChurchNameMax),
  "country": zod.string().max(postsPostsUpdateResponseLikesItemChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseLikesItemChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseLikesItemAvatarFallbackMax).optional()
})),
  "views": zod.number().min(postsPostsUpdateResponseViewsMin).max(postsPostsUpdateResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostsUpdateResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "comments": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsUpdateResponseCommentsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsUpdateResponseCommentsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsUpdateResponseCommentsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsUpdateResponseCommentsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseCommentsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsUpdateResponseCommentsItemAuthorAvatarFallbackMax).optional()
}),
  "body": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostsPostsPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postsPostsPartialUpdateBodyAuthorFirstNameMax = 255;

export const postsPostsPartialUpdateBodyAuthorLastNameMax = 255;

export const postsPostsPartialUpdateBodyAuthorChurchNameMax = 100;

export const postsPostsPartialUpdateBodyAuthorChurchCountryMax = 100;

export const postsPostsPartialUpdateBodyAuthorChurchAvatarFallbackMax = 36;

export const postsPostsPartialUpdateBodyAuthorAvatarFallbackMax = 26;

export const postsPostsPartialUpdateBodyAssemblyNameMax = 100;

export const postsPostsPartialUpdateBodyAssemblyCountryCodeMax = 3;

export const postsPostsPartialUpdateBodyAssemblyLanguageMax = 12;

export const postsPostsPartialUpdateBodyAssemblyCurrencyMax = 12;

export const postsPostsPartialUpdateBodyAssemblyAvatarFallbackMax = 36;

export const postsPostsPartialUpdateBodyTitleMax = 255;

export const postsPostsPartialUpdateBodySlugMax = 255;


export const postsPostsPartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsPartialUpdateBodyLikesItemFirstNameMax = 255;

export const postsPostsPartialUpdateBodyLikesItemLastNameMax = 255;

export const postsPostsPartialUpdateBodyLikesItemChurchNameMax = 100;

export const postsPostsPartialUpdateBodyLikesItemChurchCountryMax = 100;

export const postsPostsPartialUpdateBodyLikesItemChurchAvatarFallbackMax = 36;

export const postsPostsPartialUpdateBodyLikesItemAvatarFallbackMax = 26;

export const postsPostsPartialUpdateBodyViewsMin = 0;
export const postsPostsPartialUpdateBodyViewsMax = 9223372036854776000;

export const postsPostsPartialUpdateBodyCommentsItemAuthorFirstNameMax = 255;

export const postsPostsPartialUpdateBodyCommentsItemAuthorLastNameMax = 255;

export const postsPostsPartialUpdateBodyCommentsItemAuthorChurchNameMax = 100;

export const postsPostsPartialUpdateBodyCommentsItemAuthorChurchCountryMax = 100;

export const postsPostsPartialUpdateBodyCommentsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsPartialUpdateBodyCommentsItemAuthorAvatarFallbackMax = 26;



export const PostsPostsPartialUpdateBody = zod.object({
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsPartialUpdateBodyAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsPartialUpdateBodyAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsPartialUpdateBodyAuthorChurchNameMax),
  "country": zod.string().max(postsPostsPartialUpdateBodyAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyAuthorAvatarFallbackMax).optional()
}).optional(),
  "assembly": zod.object({
  "id": zod.number(),
  "name": zod.string().max(postsPostsPartialUpdateBodyAssemblyNameMax),
  "zone": zod.number().nullish(),
  "country_code": zod.string().max(postsPostsPartialUpdateBodyAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(postsPostsPartialUpdateBodyAssemblyLanguageMax).optional(),
  "currency": zod.string().max(postsPostsPartialUpdateBodyAssemblyCurrencyMax).optional(),
  "avatar": zod.url().optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyAssemblyAvatarFallbackMax).optional()
}).optional(),
  "title": zod.string().max(postsPostsPartialUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsPartialUpdateBodySlugMax).regex(postsPostsPartialUpdateBodySlugRegExp).optional(),
  "likes": zod.array(zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsPartialUpdateBodyLikesItemFirstNameMax),
  "last_name": zod.string().max(postsPostsPartialUpdateBodyLikesItemLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsPartialUpdateBodyLikesItemChurchNameMax),
  "country": zod.string().max(postsPostsPartialUpdateBodyLikesItemChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyLikesItemChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyLikesItemAvatarFallbackMax).optional()
})).optional(),
  "views": zod.number().min(postsPostsPartialUpdateBodyViewsMin).max(postsPostsPartialUpdateBodyViewsMax).optional(),
  "comments": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsPartialUpdateBodyCommentsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsPartialUpdateBodyCommentsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsPartialUpdateBodyCommentsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsPartialUpdateBodyCommentsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyCommentsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateBodyCommentsItemAuthorAvatarFallbackMax).optional()
}),
  "body": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})).optional(),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft')
})

export const postsPostsPartialUpdateResponseAuthorFirstNameMax = 255;

export const postsPostsPartialUpdateResponseAuthorLastNameMax = 255;

export const postsPostsPartialUpdateResponseAuthorChurchNameMax = 100;

export const postsPostsPartialUpdateResponseAuthorChurchCountryMax = 100;

export const postsPostsPartialUpdateResponseAuthorChurchAvatarFallbackMax = 36;

export const postsPostsPartialUpdateResponseAuthorAvatarFallbackMax = 26;

export const postsPostsPartialUpdateResponseAssemblyNameMax = 100;

export const postsPostsPartialUpdateResponseAssemblyCountryCodeMax = 3;

export const postsPostsPartialUpdateResponseAssemblyLanguageMax = 12;

export const postsPostsPartialUpdateResponseAssemblyCurrencyMax = 12;

export const postsPostsPartialUpdateResponseAssemblyAvatarFallbackMax = 36;

export const postsPostsPartialUpdateResponseTitleMax = 255;

export const postsPostsPartialUpdateResponseSlugMax = 255;


export const postsPostsPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postsPostsPartialUpdateResponseLikesItemFirstNameMax = 255;

export const postsPostsPartialUpdateResponseLikesItemLastNameMax = 255;

export const postsPostsPartialUpdateResponseLikesItemChurchNameMax = 100;

export const postsPostsPartialUpdateResponseLikesItemChurchCountryMax = 100;

export const postsPostsPartialUpdateResponseLikesItemChurchAvatarFallbackMax = 36;

export const postsPostsPartialUpdateResponseLikesItemAvatarFallbackMax = 26;

export const postsPostsPartialUpdateResponseViewsMin = 0;
export const postsPostsPartialUpdateResponseViewsMax = 9223372036854776000;

export const postsPostsPartialUpdateResponseImagesItemAltMax = 255;

export const postsPostsPartialUpdateResponseCommentsItemAuthorFirstNameMax = 255;

export const postsPostsPartialUpdateResponseCommentsItemAuthorLastNameMax = 255;

export const postsPostsPartialUpdateResponseCommentsItemAuthorChurchNameMax = 100;

export const postsPostsPartialUpdateResponseCommentsItemAuthorChurchCountryMax = 100;

export const postsPostsPartialUpdateResponseCommentsItemAuthorChurchAvatarFallbackMax = 36;

export const postsPostsPartialUpdateResponseCommentsItemAuthorAvatarFallbackMax = 26;



export const PostsPostsPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsPartialUpdateResponseAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsPartialUpdateResponseAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsPartialUpdateResponseAuthorChurchNameMax),
  "country": zod.string().max(postsPostsPartialUpdateResponseAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseAuthorAvatarFallbackMax).optional()
}),
  "assembly": zod.object({
  "id": zod.number(),
  "name": zod.string().max(postsPostsPartialUpdateResponseAssemblyNameMax),
  "zone": zod.number().nullish(),
  "country_code": zod.string().max(postsPostsPartialUpdateResponseAssemblyCountryCodeMax).optional(),
  "language": zod.string().max(postsPostsPartialUpdateResponseAssemblyLanguageMax).optional(),
  "currency": zod.string().max(postsPostsPartialUpdateResponseAssemblyCurrencyMax).optional(),
  "avatar": zod.url().optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseAssemblyAvatarFallbackMax).optional()
}),
  "title": zod.string().max(postsPostsPartialUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postsPostsPartialUpdateResponseSlugMax).regex(postsPostsPartialUpdateResponseSlugRegExp).optional(),
  "likes": zod.array(zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsPartialUpdateResponseLikesItemFirstNameMax),
  "last_name": zod.string().max(postsPostsPartialUpdateResponseLikesItemLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsPartialUpdateResponseLikesItemChurchNameMax),
  "country": zod.string().max(postsPostsPartialUpdateResponseLikesItemChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseLikesItemChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseLikesItemAvatarFallbackMax).optional()
})),
  "views": zod.number().min(postsPostsPartialUpdateResponseViewsMin).max(postsPostsPartialUpdateResponseViewsMax).optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postsPostsPartialUpdateResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "comments": zod.array(zod.object({
  "id": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "first_name": zod.string().max(postsPostsPartialUpdateResponseCommentsItemAuthorFirstNameMax),
  "last_name": zod.string().max(postsPostsPartialUpdateResponseCommentsItemAuthorLastNameMax),
  "roles": zod.array(zod.number()).optional(),
  "church": zod.object({
  "name": zod.string().max(postsPostsPartialUpdateResponseCommentsItemAuthorChurchNameMax),
  "country": zod.string().max(postsPostsPartialUpdateResponseCommentsItemAuthorChurchCountryMax).optional(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseCommentsItemAuthorChurchAvatarFallbackMax).optional()
}),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(postsPostsPartialUpdateResponseCommentsItemAuthorAvatarFallbackMax).optional()
}),
  "body": zod.string(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})),
  "status": zod.enum(['public', 'private', 'draft']).optional().describe('\* `public` - Public\n\* `private` - Private\n\* `draft` - Draft'),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostsPostsDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

