/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const PostCommentCreateBody = zod.object({
  "body": zod.string(),
  "post": zod.number(),
  "author": zod.number()
})

export const PostCommentDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this comment.')
})

export const postCreateListResponseTitleMax = 255;

export const postCreateListResponseSlugMax = 255;


export const postCreateListResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postCreateListResponseImagesItemAltMax = 255;



export const PostCreateListResponseItem = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postCreateListResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreateListResponseSlugMax).regex(postCreateListResponseSlugRegExp).optional(),
  "views": zod.number().optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postCreateListResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const PostCreateListResponse = zod.array(PostCreateListResponseItem)

export const postCreateCreateBodyTitleMax = 255;

export const postCreateCreateBodySlugMax = 255;


export const postCreateCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostCreateCreateBody = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postCreateCreateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreateCreateBodySlugMax).regex(postCreateCreateBodySlugRegExp).optional(),
  "views": zod.number().optional(),
  "uploaded_images": zod.array(zod.string())
})

export const PostCreateRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postCreateRetrieveResponseTitleMax = 255;

export const postCreateRetrieveResponseSlugMax = 255;


export const postCreateRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postCreateRetrieveResponseImagesItemAltMax = 255;



export const PostCreateRetrieveResponse = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postCreateRetrieveResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreateRetrieveResponseSlugMax).regex(postCreateRetrieveResponseSlugRegExp).optional(),
  "views": zod.number().optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postCreateRetrieveResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostCreateUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postCreateUpdateBodyTitleMax = 255;

export const postCreateUpdateBodySlugMax = 255;


export const postCreateUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostCreateUpdateBody = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postCreateUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreateUpdateBodySlugMax).regex(postCreateUpdateBodySlugRegExp).optional(),
  "views": zod.number().optional(),
  "uploaded_images": zod.array(zod.string())
})

export const postCreateUpdateResponseTitleMax = 255;

export const postCreateUpdateResponseSlugMax = 255;


export const postCreateUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postCreateUpdateResponseImagesItemAltMax = 255;



export const PostCreateUpdateResponse = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postCreateUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreateUpdateResponseSlugMax).regex(postCreateUpdateResponseSlugRegExp).optional(),
  "views": zod.number().optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postCreateUpdateResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostCreatePartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

export const postCreatePartialUpdateBodyTitleMax = 255;

export const postCreatePartialUpdateBodySlugMax = 255;


export const postCreatePartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const PostCreatePartialUpdateBody = zod.object({
  "author": zod.number().optional(),
  "assembly": zod.number().optional(),
  "title": zod.string().max(postCreatePartialUpdateBodyTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreatePartialUpdateBodySlugMax).regex(postCreatePartialUpdateBodySlugRegExp).optional(),
  "views": zod.number().optional(),
  "uploaded_images": zod.array(zod.string()).optional()
})

export const postCreatePartialUpdateResponseTitleMax = 255;

export const postCreatePartialUpdateResponseSlugMax = 255;


export const postCreatePartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const postCreatePartialUpdateResponseImagesItemAltMax = 255;



export const PostCreatePartialUpdateResponse = zod.object({
  "author": zod.number(),
  "assembly": zod.number(),
  "title": zod.string().max(postCreatePartialUpdateResponseTitleMax).optional(),
  "content": zod.string().optional(),
  "slug": zod.string().max(postCreatePartialUpdateResponseSlugMax).regex(postCreatePartialUpdateResponseSlugRegExp).optional(),
  "views": zod.number().optional(),
  "images": zod.array(zod.object({
  "id": zod.number(),
  "image": zod.url(),
  "alt": zod.string().max(postCreatePartialUpdateResponseImagesItemAltMax).optional().describe('Alternative text for accessibility and SEO.'),
  "caption": zod.string().optional().describe('Optional caption for the image.'),
  "post": zod.number()
})),
  "uploaded_images": zod.array(zod.string()),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const PostCreateDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this post.')
})

