/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const resourcesListResponseTitleMax = 100;

export const resourcesListResponseSlugMax = 255;


export const resourcesListResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesListResponseResourceImageFallbackMax = 12;



export const ResourcesListResponseItem = zod.object({
  "id": zod.number(),
  "ruid": zod.uuid(),
  "title": zod.string().max(resourcesListResponseTitleMax),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesListResponseSlugMax).regex(resourcesListResponseSlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesListResponseResourceImageFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const ResourcesListResponse = zod.array(ResourcesListResponseItem)

export const resourcesCreateBodyTitleMax = 100;

export const resourcesCreateBodySlugMax = 255;


export const resourcesCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesCreateBodyResourceImageFallbackMax = 12;



export const ResourcesCreateBody = zod.object({
  "title": zod.string().max(resourcesCreateBodyTitleMax),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesCreateBodySlugMax).regex(resourcesCreateBodySlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesCreateBodyResourceImageFallbackMax).optional()
})

export const ResourcesRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Resource.')
})

export const resourcesRetrieveResponseTitleMax = 100;

export const resourcesRetrieveResponseSlugMax = 255;


export const resourcesRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesRetrieveResponseResourceImageFallbackMax = 12;



export const ResourcesRetrieveResponse = zod.object({
  "id": zod.number(),
  "ruid": zod.uuid(),
  "title": zod.string().max(resourcesRetrieveResponseTitleMax),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesRetrieveResponseSlugMax).regex(resourcesRetrieveResponseSlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesRetrieveResponseResourceImageFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const ResourcesUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Resource.')
})

export const resourcesUpdateBodyTitleMax = 100;

export const resourcesUpdateBodySlugMax = 255;


export const resourcesUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesUpdateBodyResourceImageFallbackMax = 12;



export const ResourcesUpdateBody = zod.object({
  "title": zod.string().max(resourcesUpdateBodyTitleMax),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesUpdateBodySlugMax).regex(resourcesUpdateBodySlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesUpdateBodyResourceImageFallbackMax).optional()
})

export const resourcesUpdateResponseTitleMax = 100;

export const resourcesUpdateResponseSlugMax = 255;


export const resourcesUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesUpdateResponseResourceImageFallbackMax = 12;



export const ResourcesUpdateResponse = zod.object({
  "id": zod.number(),
  "ruid": zod.uuid(),
  "title": zod.string().max(resourcesUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesUpdateResponseSlugMax).regex(resourcesUpdateResponseSlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesUpdateResponseResourceImageFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const ResourcesPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Resource.')
})

export const resourcesPartialUpdateBodyTitleMax = 100;

export const resourcesPartialUpdateBodySlugMax = 255;


export const resourcesPartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesPartialUpdateBodyResourceImageFallbackMax = 12;



export const ResourcesPartialUpdateBody = zod.object({
  "title": zod.string().max(resourcesPartialUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesPartialUpdateBodySlugMax).regex(resourcesPartialUpdateBodySlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesPartialUpdateBodyResourceImageFallbackMax).optional()
})

export const resourcesPartialUpdateResponseTitleMax = 100;

export const resourcesPartialUpdateResponseSlugMax = 255;


export const resourcesPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const resourcesPartialUpdateResponseResourceImageFallbackMax = 12;



export const ResourcesPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "ruid": zod.uuid(),
  "title": zod.string().max(resourcesPartialUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "file": zod.url().nullish(),
  "slug": zod.string().max(resourcesPartialUpdateResponseSlugMax).regex(resourcesPartialUpdateResponseSlugRegExp).optional(),
  "resource_image_fallback": zod.string().max(resourcesPartialUpdateResponseResourceImageFallbackMax).optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

export const ResourcesDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Resource.')
})

