/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const StrategyLegacyListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const strategyLegacyListResponseResultsItemCoordinatorMax = 255;

export const strategyLegacyListResponseResultsItemTitleMax = 255;

export const strategyLegacyListResponseResultsItemSlugMax = 255;


export const strategyLegacyListResponseResultsItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyListResponseResultsItemColorMax = 12;



export const StrategyLegacyListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "coordinator": zod.string().max(strategyLegacyListResponseResultsItemCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyListResponseResultsItemTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyListResponseResultsItemSlugMax).regex(strategyLegacyListResponseResultsItemSlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyListResponseResultsItemColorMax).optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "branch": zod.number()
})).optional()
})

export const strategyLegacyCreateBodyCoordinatorMax = 255;

export const strategyLegacyCreateBodyTitleMax = 255;

export const strategyLegacyCreateBodySlugMax = 255;


export const strategyLegacyCreateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyCreateBodyColorMax = 12;



export const StrategyLegacyCreateBody = zod.object({
  "coordinator": zod.string().max(strategyLegacyCreateBodyCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyCreateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyCreateBodySlugMax).regex(strategyLegacyCreateBodySlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyCreateBodyColorMax).optional(),
  "timestamp": zod.iso.date(),
  "branch": zod.number()
})

export const StrategyLegacyRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Strategy Legacy.')
})

export const strategyLegacyRetrieveResponseCoordinatorMax = 255;

export const strategyLegacyRetrieveResponseTitleMax = 255;

export const strategyLegacyRetrieveResponseSlugMax = 255;


export const strategyLegacyRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyRetrieveResponseColorMax = 12;



export const StrategyLegacyRetrieveResponse = zod.object({
  "id": zod.number(),
  "coordinator": zod.string().max(strategyLegacyRetrieveResponseCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyRetrieveResponseTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyRetrieveResponseSlugMax).regex(strategyLegacyRetrieveResponseSlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyRetrieveResponseColorMax).optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "branch": zod.number()
})

export const StrategyLegacyUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Strategy Legacy.')
})

export const strategyLegacyUpdateBodyCoordinatorMax = 255;

export const strategyLegacyUpdateBodyTitleMax = 255;

export const strategyLegacyUpdateBodySlugMax = 255;


export const strategyLegacyUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyUpdateBodyColorMax = 12;



export const StrategyLegacyUpdateBody = zod.object({
  "coordinator": zod.string().max(strategyLegacyUpdateBodyCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyUpdateBodySlugMax).regex(strategyLegacyUpdateBodySlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyUpdateBodyColorMax).optional(),
  "timestamp": zod.iso.date(),
  "branch": zod.number()
})

export const strategyLegacyUpdateResponseCoordinatorMax = 255;

export const strategyLegacyUpdateResponseTitleMax = 255;

export const strategyLegacyUpdateResponseSlugMax = 255;


export const strategyLegacyUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyUpdateResponseColorMax = 12;



export const StrategyLegacyUpdateResponse = zod.object({
  "id": zod.number(),
  "coordinator": zod.string().max(strategyLegacyUpdateResponseCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyUpdateResponseTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyUpdateResponseSlugMax).regex(strategyLegacyUpdateResponseSlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyUpdateResponseColorMax).optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "branch": zod.number()
})

export const StrategyLegacyPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Strategy Legacy.')
})

export const strategyLegacyPartialUpdateBodyCoordinatorMax = 255;

export const strategyLegacyPartialUpdateBodyTitleMax = 255;

export const strategyLegacyPartialUpdateBodySlugMax = 255;


export const strategyLegacyPartialUpdateBodySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyPartialUpdateBodyColorMax = 12;



export const StrategyLegacyPartialUpdateBody = zod.object({
  "coordinator": zod.string().max(strategyLegacyPartialUpdateBodyCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyPartialUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyPartialUpdateBodySlugMax).regex(strategyLegacyPartialUpdateBodySlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyPartialUpdateBodyColorMax).optional(),
  "timestamp": zod.iso.date().optional(),
  "branch": zod.number().optional()
})

export const strategyLegacyPartialUpdateResponseCoordinatorMax = 255;

export const strategyLegacyPartialUpdateResponseTitleMax = 255;

export const strategyLegacyPartialUpdateResponseSlugMax = 255;


export const strategyLegacyPartialUpdateResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const strategyLegacyPartialUpdateResponseColorMax = 12;



export const StrategyLegacyPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "coordinator": zod.string().max(strategyLegacyPartialUpdateResponseCoordinatorMax).optional(),
  "title": zod.string().max(strategyLegacyPartialUpdateResponseTitleMax).optional(),
  "description": zod.string().optional(),
  "attachment": zod.url().nullish(),
  "slug": zod.string().max(strategyLegacyPartialUpdateResponseSlugMax).regex(strategyLegacyPartialUpdateResponseSlugRegExp).optional(),
  "color": zod.string().max(strategyLegacyPartialUpdateResponseColorMax).optional(),
  "timestamp": zod.iso.date(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "branch": zod.number()
})

export const StrategyLegacyDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this Strategy Legacy.')
})

