/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const StrategiesListQueryParams = zod.object({
  "page": zod.number().optional().describe('A page number within the paginated result set.'),
  "page_size": zod.number().optional().describe('Number of results to return per page.')
})

export const strategiesListResponseResultsItemTitleMax = 255;

export const strategiesListResponseResultsItemVenueMax = 255;

export const strategiesListResponseResultsItemMeetingThumbnailFallbackMax = 255;



export const StrategiesListResponse = zod.object({
  "count": zod.number().optional(),
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string().max(strategiesListResponseResultsItemTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesListResponseResultsItemVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesListResponseResultsItemMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})).optional()
})

export const strategiesCreateBodyTitleMax = 255;

export const strategiesCreateBodyVenueMax = 255;

export const strategiesCreateBodyMeetingThumbnailFallbackMax = 255;



export const StrategiesCreateBody = zod.object({
  "title": zod.string().max(strategiesCreateBodyTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesCreateBodyVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesCreateBodyMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const StrategiesRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

export const strategiesRetrieveResponseTitleMax = 255;

export const strategiesRetrieveResponseVenueMax = 255;

export const strategiesRetrieveResponseMeetingThumbnailFallbackMax = 255;



export const StrategiesRetrieveResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(strategiesRetrieveResponseTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesRetrieveResponseVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesRetrieveResponseMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const StrategiesUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

export const strategiesUpdateBodyTitleMax = 255;

export const strategiesUpdateBodyVenueMax = 255;

export const strategiesUpdateBodyMeetingThumbnailFallbackMax = 255;



export const StrategiesUpdateBody = zod.object({
  "title": zod.string().max(strategiesUpdateBodyTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesUpdateBodyVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesUpdateBodyMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const strategiesUpdateResponseTitleMax = 255;

export const strategiesUpdateResponseVenueMax = 255;

export const strategiesUpdateResponseMeetingThumbnailFallbackMax = 255;



export const StrategiesUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(strategiesUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesUpdateResponseVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesUpdateResponseMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const StrategiesPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

export const strategiesPartialUpdateBodyTitleMax = 255;

export const strategiesPartialUpdateBodyVenueMax = 255;

export const strategiesPartialUpdateBodyMeetingThumbnailFallbackMax = 255;



export const StrategiesPartialUpdateBody = zod.object({
  "title": zod.string().max(strategiesPartialUpdateBodyTitleMax).optional(),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesPartialUpdateBodyVenueMax).optional(),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesPartialUpdateBodyMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}).optional(),
  "meeting_end_time": zod.iso.datetime({}).optional(),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const strategiesPartialUpdateResponseTitleMax = 255;

export const strategiesPartialUpdateResponseVenueMax = 255;

export const strategiesPartialUpdateResponseMeetingThumbnailFallbackMax = 255;



export const StrategiesPartialUpdateResponse = zod.object({
  "id": zod.number(),
  "title": zod.string().max(strategiesPartialUpdateResponseTitleMax),
  "description": zod.string().optional(),
  "venue": zod.string().max(strategiesPartialUpdateResponseVenueMax),
  "mode": zod.union([zod.enum(['in-person', 'virtual']).describe('\* `in-person` - In Person\n\* `virtual` - Virtual'),zod.enum([''])]).optional(),
  "platform": zod.union([zod.enum(['facebook', 'meet', 'slack', 'teams', 'telegram', 'whatsapp', 'zoom']).describe('\* `facebook` - Facebook\n\* `meet` - Google Meet\n\* `slack` - Slack\n\* `teams` - Microsoft Teams\n\* `telegram` - Telegram\n\* `whatsapp` - WhatsApp\n\* `zoom` - Zoom'),zod.enum([''])]).optional(),
  "category": zod.union([zod.enum(['board', 'deacons', 'elders', 'pastors', 'workers', 'youth']).describe('\* `board` - Board\n\* `deacons` - Deacons\n\* `elders` - Elders\n\* `pastors` - Pastors\n\* `workers` - Workers\n\* `youth` - Youth'),zod.enum([''])]).optional(),
  "meeting_thumbnail_fallback": zod.string().max(strategiesPartialUpdateResponseMeetingThumbnailFallbackMax).optional(),
  "meeting_start_time": zod.iso.datetime({}),
  "meeting_end_time": zod.iso.datetime({}),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "assembly": zod.number().nullish(),
  "created_by": zod.number().nullish()
})

export const StrategiesDestroyParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this meeting.')
})

