/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const usersListResponsePasswordMax = 128;

export const usersListResponseFirstNameMax = 255;

export const usersListResponseLastNameMax = 255;

export const usersListResponseUsernameMax = 255;

export const usersListResponseEmailMax = 255;

export const usersListResponseRecoveryEmailMax = 254;

export const usersListResponseAvatarFallbackMax = 26;



export const UsersListResponseItem = zod.object({
  "id": zod.number(),
  "password": zod.string().max(usersListResponsePasswordMax),
  "last_login": zod.iso.datetime({}).nullish(),
  "is_superuser": zod.boolean().optional().describe('Designates that this user has all permissions without explicitly assigning them.'),
  "user_id": zod.string(),
  "first_name": zod.string().max(usersListResponseFirstNameMax),
  "last_name": zod.string().max(usersListResponseLastNameMax),
  "username": zod.string().max(usersListResponseUsernameMax).optional(),
  "email": zod.email().max(usersListResponseEmailMax),
  "recovery_email": zod.email().max(usersListResponseRecoveryEmailMax).nullish().describe('Used for account recovery or alternative communication.'),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(usersListResponseAvatarFallbackMax).optional(),
  "is_active": zod.boolean().optional(),
  "is_admin": zod.boolean().optional(),
  "is_onboarded": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "church": zod.number().nullish(),
  "groups": zod.array(zod.number()).optional().describe('The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
  "user_permissions": zod.array(zod.number()).optional().describe('Specific permissions for this user.'),
  "assemblies": zod.array(zod.number()).optional(),
  "roles": zod.array(zod.number()).optional()
})
export const UsersListResponse = zod.array(UsersListResponseItem)

export const UsersRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this user.')
})

export const usersRetrieveResponsePasswordMax = 128;

export const usersRetrieveResponseFirstNameMax = 255;

export const usersRetrieveResponseLastNameMax = 255;

export const usersRetrieveResponseUsernameMax = 255;

export const usersRetrieveResponseEmailMax = 255;

export const usersRetrieveResponseRecoveryEmailMax = 254;

export const usersRetrieveResponseAvatarFallbackMax = 26;



export const UsersRetrieveResponse = zod.object({
  "id": zod.number(),
  "password": zod.string().max(usersRetrieveResponsePasswordMax),
  "last_login": zod.iso.datetime({}).nullish(),
  "is_superuser": zod.boolean().optional().describe('Designates that this user has all permissions without explicitly assigning them.'),
  "user_id": zod.string(),
  "first_name": zod.string().max(usersRetrieveResponseFirstNameMax),
  "last_name": zod.string().max(usersRetrieveResponseLastNameMax),
  "username": zod.string().max(usersRetrieveResponseUsernameMax).optional(),
  "email": zod.email().max(usersRetrieveResponseEmailMax),
  "recovery_email": zod.email().max(usersRetrieveResponseRecoveryEmailMax).nullish().describe('Used for account recovery or alternative communication.'),
  "avatar": zod.url().nullish(),
  "avatar_fallback": zod.string().max(usersRetrieveResponseAvatarFallbackMax).optional(),
  "is_active": zod.boolean().optional(),
  "is_admin": zod.boolean().optional(),
  "is_onboarded": zod.boolean().optional(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({}),
  "church": zod.number().nullish(),
  "groups": zod.array(zod.number()).optional().describe('The groups this user belongs to. A user will get all permissions granted to each of their groups.'),
  "user_permissions": zod.array(zod.number()).optional().describe('Specific permissions for this user.'),
  "assemblies": zod.array(zod.number()).optional(),
  "roles": zod.array(zod.number()).optional()
})

