/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const ZoneReportsRetrieveParams = zod.object({
  "zone_id": zod.number()
})

