export const attendanceMetrics = [
    { key: "men", label: "Men" },
    { key: "women", label: "Women" },
    { key: "visitor_men", label: "Visitor Men" },
    { key: "visitor_women", label: "Visitor Women" },
    { key: "new_convert_men", label: "Convert Men" },
    { key: "new_convert_women", label: "Convert Women" },
    { key: "baptism_men", label: "Baptism Men" },
    { key: "baptism_women", label: "Baptism Women" },
    { key: "altar_call_men", label: "Altar Call Men" },
    { key: "altar_call_women", label: "Altar Call Women" },
    { key: "online_viewers", label: "Online" },
    { key: "volunteers_on_duty", label: "Volunteers" },
    { key: "total_leaders_present", label: "Leaders" },
] as const
