/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * CFI Workspace API
 * Backend API for managing church assemblies, members, attendance, finances, and reports for the CFI Workspace platform.
 * OpenAPI spec version: 1.0.0
 */
/**
 * * `CREATE` - Create
* `UPDATE` - Update
* `DELETE` - Delete
* `RESTORE` - Restore
 */
export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];


export const ActionEnum = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  RESTORE: 'RESTORE',
} as const;

export interface Activation {
  uid: string;
  token: string;
}

export interface Assembly {
  id: number | undefined;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  country?: string;
  /** @maxLength 36 */
  avatar_fallback?: string;
}

/**
 * * `COMPLIANT` - Compliant
* `LATE` - Late
* `NOT_SUBMITTED` - Not Submitted
* `NOT_FINALIZED` - Not Finalized
* `MISSING_FROM_ZONE` - Missing From Zone
 */
export type AssemblyComplianceStatusEnum = typeof AssemblyComplianceStatusEnum[keyof typeof AssemblyComplianceStatusEnum];


export const AssemblyComplianceStatusEnum = {
  COMPLIANT: 'COMPLIANT',
  LATE: 'LATE',
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  NOT_FINALIZED: 'NOT_FINALIZED',
  MISSING_FROM_ZONE: 'MISSING_FROM_ZONE',
} as const;

export interface AssemblyCompliance {
  readonly id: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  year: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  month: number;
  status: AssemblyComplianceStatusEnum;
  readonly evaluated_at: string;
  assembly: number;
  zone: number;
  /** @nullable */
  report?: number | null;
}

export interface AssemblyISO {
  readonly id: number;
  /** @maxLength 3 */
  country_code?: string;
  /** @maxLength 12 */
  language?: string;
  /** @maxLength 12 */
  currency?: string;
}

/**
 * * `draft` - Draft
* `finalized` - Finalized
* `reviewed` - Reviewed
* `approved` - Approved
* `archived` - Archived
 */
export type AssemblyReportStatusEnum = typeof AssemblyReportStatusEnum[keyof typeof AssemblyReportStatusEnum];


export const AssemblyReportStatusEnum = {
  draft: 'draft',
  finalized: 'finalized',
  reviewed: 'reviewed',
  approved: 'approved',
  archived: 'archived',
} as const;

/**
 * Base serializer that generates:
- url: self-detail URL
- links: related object URLs
- actions: edit/delete/bulk-delete URLs
- collection_actions: bulk delete/restore URLs
Permissions are omitted since authenticated users have full access.
 */
export interface AssemblyReport {
  readonly id: number;
  assembly: number;
  period_start: string;
  period_end: string;
  status?: AssemblyReportStatusEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  attendance_total?: number;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  income_total?: string;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  expense_total?: string;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  tithe_total?: string;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  balance?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  members_total?: number;
  /** @nullable */
  finalized_at?: string | null;
  readonly url: string;
}

export interface AssemblySummary {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  /** @nullable */
  zone?: number | null;
  /** @maxLength 3 */
  country_code?: string;
  /** @maxLength 12 */
  language?: string;
  /** @maxLength 12 */
  currency?: string;
  avatar?: string;
  /** @maxLength 36 */
  avatar_fallback?: string;
}

/**
 * * `New` - New
* `Good` - Good
* `Fair` - Fair
* `Old` - Old
* `Not Working` - Not Working
 */
export type ConditionEnum = typeof ConditionEnum[keyof typeof ConditionEnum];


export const ConditionEnum = {
  New: 'New',
  Good: 'Good',
  Fair: 'Fair',
  Old: 'Old',
  Not_Working: 'Not Working',
} as const;

/**
 * * `Building` - Building
* `Instrument` - Instrument
* `Vehicle` - Vehicle
* `Furniture` - Furniture
* `Electronics` - Electronics
* `Machinery` - Machinery
* `Software` - Software
* `Land` - Land
* `Other` - Other
 */
export type AssetTypeEnum = typeof AssetTypeEnum[keyof typeof AssetTypeEnum];


export const AssetTypeEnum = {
  Building: 'Building',
  Instrument: 'Instrument',
  Vehicle: 'Vehicle',
  Furniture: 'Furniture',
  Electronics: 'Electronics',
  Machinery: 'Machinery',
  Software: 'Software',
  Land: 'Land',
  Other: 'Other',
} as const;

export interface AssetImage {
  readonly id: number;
  image: string;
  asset: number;
}

export interface Asset {
  readonly id: number;
  assembly: AssemblyISO;
  /** @maxLength 255 */
  item_code?: string;
  /** @maxLength 255 */
  item_name: string;
  /** @maxLength 2000 */
  description?: string;
  condition: ConditionEnum;
  asset_type: AssetTypeEnum;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  units: number;
  acquisition_date: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  acquisition_cost?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  residual?: string;
  /** @maxLength 255 */
  vendor?: string;
  readonly asset_images: readonly AssetImage[];
  /** @nullable */
  created_by?: number | null;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface AuditLog {
  readonly id: number;
  /** @nullable */
  readonly user: number | null;
  readonly user_name: string;
  readonly user_email: string;
  readonly model: string;
  readonly object_id: number;
  readonly action: ActionEnum;
  readonly old_data: unknown | null;
  readonly new_data: unknown | null;
  readonly timestamp: string;
}

export interface AuthHistory {
  readonly id: number;
  last_login: string;
  last_logout: string;
  readonly created_at: string;
  readonly updated_at: string;
  user: number;
}

export interface Author {
  readonly id: number;
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
  roles?: number[];
  church: Assembly;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 26 */
  avatar_fallback?: string;
}

export type BlankEnum = typeof BlankEnum[keyof typeof BlankEnum];


export const BlankEnum = {
  '': '',
} as const;

/**
 * * `Admin` - Admin
* `Dean` - Dean
* `Moderator` - Moderator
* `Overseer` - Overseer
* `Pastor` - Pastor
* `President` - President
* `Secretary` - Secretary
* `Secretary General` - Secretary General
* `Senior Pastor` - Senior Pastor
* `Student` - Student
* `Student Representative` - Student Representative
* `Teacher` - Teacher
* `Zone Admin` - Zone Admin
 */
export type NameEnum = typeof NameEnum[keyof typeof NameEnum];


export const NameEnum = {
  Admin: 'Admin',
  Dean: 'Dean',
  Moderator: 'Moderator',
  Overseer: 'Overseer',
  Pastor: 'Pastor',
  President: 'President',
  Secretary: 'Secretary',
  Secretary_General: 'Secretary General',
  Senior_Pastor: 'Senior Pastor',
  Student: 'Student',
  Student_Representative: 'Student Representative',
  Teacher: 'Teacher',
  Zone_Admin: 'Zone Admin',
} as const;

export interface Role {
  readonly id: number;
  name: NameEnum;
}

export interface MinimalUser {
  readonly full_name: string;
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
  /** @maxLength 255 */
  email: string;
  roles: Role[];
  readonly avatar: string;
  /** @maxLength 26 */
  avatar_fallback?: string;
}

/**
 * * `Attendance` - Attendance
* `Authentication` - Authentication
* `Changelog` - Changelog
* `Demographics` - Demographics
* `Finance` - Finance
* `General` - General
* `Strategy` - Strategy
* `Templates` - Templates
* `Updates` - Updates
 */
export type BlogCategoryEnum = typeof BlogCategoryEnum[keyof typeof BlogCategoryEnum];


export const BlogCategoryEnum = {
  Attendance: 'Attendance',
  Authentication: 'Authentication',
  Changelog: 'Changelog',
  Demographics: 'Demographics',
  Finance: 'Finance',
  General: 'General',
  Strategy: 'Strategy',
  Templates: 'Templates',
  Updates: 'Updates',
} as const;

/**
 * * `draft` - Draft
* `published` - Published
* `archived` - Archived
 */
export type StatusDaeEnum = typeof StatusDaeEnum[keyof typeof StatusDaeEnum];


export const StatusDaeEnum = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
} as const;

export interface Blog {
  readonly id: number;
  author: MinimalUser;
  /** @maxLength 255 */
  title: string;
  subtitle?: string;
  body: string;
  category?: BlogCategoryEnum;
  /** @nullable */
  image?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
  status?: StatusDaeEnum;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
}

/**
 * * `Open` - Open
* `Closed` - Closed
 */
export type ChurchStatusEnum = typeof ChurchStatusEnum[keyof typeof ChurchStatusEnum];


export const ChurchStatusEnum = {
  Open: 'Open',
  Closed: 'Closed',
} as const;

export const ChurchStatus = {...ChurchStatusEnum,...BlankEnum,} as const
export interface Church {
  readonly id: number;
  readonly uuid: string;
  /** @maxLength 100 */
  name: string;
  description?: string;
  /** @maxLength 255 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 100 */
  province?: string;
  /** @maxLength 100 */
  country?: string;
  /** @maxLength 3 */
  country_code?: string;
  /** @maxLength 12 */
  language?: string;
  /** @maxLength 12 */
  currency?: string;
  /** @maxLength 20 */
  phone_number?: string;
  /** @maxLength 20 */
  email?: string;
  avatar?: string;
  /** @maxLength 36 */
  avatar_fallback?: string;
  status?: typeof ChurchStatus[keyof typeof ChurchStatus];
  cover_image?: string;
  readonly created_at: string;
  readonly updated_at: string;
  is_active?: boolean;
  /** @nullable */
  zone?: number | null;
  assigned_pastors?: number[];
}

export interface Comment {
  readonly id: number;
  author: Author;
  body: string;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface CountryInfo {
  readonly id: number;
  /** @maxLength 3 */
  country_code?: string;
  /** @maxLength 12 */
  language?: string;
  /** @maxLength 12 */
  currency?: string;
}

export interface CreateAsset {
  assembly: number;
  /** @maxLength 255 */
  item_code?: string;
  /** @maxLength 255 */
  item_name: string;
  /** @maxLength 2000 */
  description?: string;
  condition: ConditionEnum;
  asset_type: AssetTypeEnum;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  units: number;
  acquisition_date: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  acquisition_cost?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  residual?: string;
  /** @maxLength 255 */
  vendor?: string;
  readonly images: readonly AssetImage[];
  asset_images: string[];
  /** @nullable */
  created_by?: number | null;
}

export interface CreateComment {
  readonly id: number;
  body: string;
  readonly created_at: string;
  readonly updated_at: string;
  post: number;
  author: number;
}

export interface CreateFixedExpenditure {
  readonly id: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  bank_charges?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  car_maintenance?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  electricity?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fuel?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  humanitarian?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  insurance?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  internet?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  investment?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  rent?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  remittance?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  security?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  telephone?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  wages?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  water?: string;
  remarks?: string;
  /** @nullable */
  remittance_receipt?: string | null;
  is_remittance_verified?: boolean;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total?: string;
  timestamp: string;
  readonly created_at: string;
  readonly updated_at: string;
  assembly: number;
  /** @nullable */
  created_by?: number | null;
  /** @nullable */
  report?: number | null;
  /** @nullable */
  remittance_moderator?: number | null;
}

export interface CreateIncome {
  readonly id: number;
  /** @nullable */
  timestamp?: string | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  offering?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fundraising?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  thanksgiving?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  donations?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_income?: string;
  notes?: string;
  /** @nullable */
  statement?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
  church: number;
  /** @nullable */
  report?: number | null;
}

export interface PostImage {
  readonly id: number;
  image: string;
  /**
   * Alternative text for accessibility and SEO.
   * @maxLength 255
   */
  alt?: string;
  /** Optional caption for the image. */
  caption?: string;
  post: number;
}

export interface CreatePost {
  author: number;
  assembly: number;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  views?: number;
  readonly images: readonly PostImage[];
  uploaded_images: string[];
  readonly created_at: string;
  readonly updated_at: string;
}

export interface CreateUser {
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
  /** @maxLength 255 */
  email: string;
  roles?: number[];
  /** @nullable */
  church?: number | null;
  assemblies?: number[];
  password: string;
  re_password: string;
}

export interface CurrentUser {
  readonly id: number;
  readonly user_id: string;
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
  /** @maxLength 255 */
  username?: string;
  /** @maxLength 255 */
  email: string;
  /**
   * Used for account recovery or alternative communication.
   * @maxLength 254
   * @nullable
   */
  recovery_email?: string | null;
  /** @nullable */
  church?: number | null;
  readonly assembly: AssemblySummary;
  readonly assemblies: readonly Church[];
  readonly roles: readonly Role[];
  readonly full_name: string;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 26 */
  avatar_fallback?: string;
  is_active?: boolean;
  is_admin?: boolean;
  is_onboarded?: boolean;
  readonly is_db_staff: string;
  readonly is_db_zone_staff: string;
  readonly is_academy_staff: string;
  readonly is_student: string;
  readonly is_staff: string;
  readonly created_at: string;
  readonly updated_at: string;
}

/**
 * * `General` - General
* `API` - API
* `User Guide` - User Guide
* `Technical` - Technical
 */
export type DocumentationCategoryEnum = typeof DocumentationCategoryEnum[keyof typeof DocumentationCategoryEnum];


export const DocumentationCategoryEnum = {
  General: 'General',
  API: 'API',
  User_Guide: 'User Guide',
  Technical: 'Technical',
} as const;

export interface Documentation {
  readonly id: number;
  /** @maxLength 255 */
  title: string;
  body: string;
  category?: DocumentationCategoryEnum;
  status?: StatusDaeEnum;
  readonly author: number;
  readonly author_name: string;
  readonly created_at: string;
  readonly updated_at: string;
}

/**
 * * `Primary` - Primary
* `Secondary` - Secondary
* `Diploma` - Diploma
* `Bachelor's Degree` - Bachelor's Degree
* `Master's Degree` - Master's Degree
* `Doctorate` - Doctorate
* `Other` - Other
 */
export type EducationLevelEnum = typeof EducationLevelEnum[keyof typeof EducationLevelEnum];


export const EducationLevelEnum = {
  Primary: 'Primary',
  Secondary: 'Secondary',
  Diploma: 'Diploma',
  'Bachelor\'s_Degree': 'Bachelor\'s Degree',
  'Master\'s_Degree': 'Master\'s Degree',
  Doctorate: 'Doctorate',
  Other: 'Other',
} as const;

/**
 * * `amenities` - Amenities
* `conference` - Conference
* `decor` - Decor
* `fellowship` - Fellowship
* `hotel bookings` - Hotel Bookings
* `humanitarian` - Humanitarian
* `office` - Office
* `other` - Other
* `outreach` - Outreach
* `repair` - Repair
* `travel` - Travel
* `wages` - Wages
 */
export type ExpenditureCategoryEnum = typeof ExpenditureCategoryEnum[keyof typeof ExpenditureCategoryEnum];


export const ExpenditureCategoryEnum = {
  amenities: 'amenities',
  conference: 'conference',
  decor: 'decor',
  fellowship: 'fellowship',
  hotel_bookings: 'hotel bookings',
  humanitarian: 'humanitarian',
  office: 'office',
  other: 'other',
  outreach: 'outreach',
  repair: 'repair',
  travel: 'travel',
  wages: 'wages',
} as const;

export interface Expenditure {
  readonly id: number;
  /** @maxLength 255 */
  invoice_number?: string;
  invoice_date: string;
  /** @maxLength 255 */
  name: string;
  description?: string;
  category: ExpenditureCategoryEnum;
  /** @maxLength 255 */
  supplier?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  quantity: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  readonly total: string;
  /** @nullable */
  receipt?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
  assembly: number;
  /** @nullable */
  report?: number | null;
  /** @nullable */
  created_by?: number | null;
}

export interface FixedExpenditure {
  readonly id: number;
  assembly: AssemblyISO;
  /** @nullable */
  created_by?: number | null;
  timestamp: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  rent?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  wages?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  water?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  electricity?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  telephone?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  internet?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  security?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fuel?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  car_maintenance?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  humanitarian?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  investment?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  bank_charges?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  insurance?: string;
  remarks?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  remittance?: string;
  /** @nullable */
  remittance_receipt?: string | null;
  /** @nullable */
  remittance_moderator?: number | null;
  is_remittance_verified?: boolean;
}

/**
 * * `Male` - Male
* `Female` - Female
 */
export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];


export const GenderEnum = {
  Male: 'Male',
  Female: 'Female',
} as const;

/**
 * * `Advocate` - Advocate
* `Dr` - Dr
* `Eng` - Eng
* `Hon` - Hon
* `Miss` - Miss
* `Mr` - Mr
* `Mrs` - Mrs
* `Ms` - Ms
* `Prof` - Prof
* `Rev` - Rev
 */
export type PrefixEnum = typeof PrefixEnum[keyof typeof PrefixEnum];


export const PrefixEnum = {
  Advocate: 'Advocate',
  Dr: 'Dr',
  Eng: 'Eng',
  Hon: 'Hon',
  Miss: 'Miss',
  Mr: 'Mr',
  Mrs: 'Mrs',
  Ms: 'Ms',
  Prof: 'Prof',
  Rev: 'Rev',
} as const;

/**
 * * `Single` - Single
* `Married` - Married
* `Divorced` - Divorced
* `Widowed` - Widowed
* `Separated` - Separated
* `Engaged` - Engaged
* `In a Relationship` - In a Relationship
* `Domestic Partnership` - Domestic Partnership
* `Civil Union` - Civil Union
* `Committed` - Committed
* `Common-Law Marriage` - Common-Law Marriage
* `Traditional Marriage` - Traditional Marriage
* `Co-parenting` - Co-parenting
 */
export type RelationshipEnum = typeof RelationshipEnum[keyof typeof RelationshipEnum];


export const RelationshipEnum = {
  Single: 'Single',
  Married: 'Married',
  Divorced: 'Divorced',
  Widowed: 'Widowed',
  Separated: 'Separated',
  Engaged: 'Engaged',
  In_a_Relationship: 'In a Relationship',
  Domestic_Partnership: 'Domestic Partnership',
  Civil_Union: 'Civil Union',
  Committed: 'Committed',
  'Common-Law_Marriage': 'Common-Law Marriage',
  Traditional_Marriage: 'Traditional Marriage',
  'Co-parenting': 'Co-parenting',
} as const;

/**
 * * `Visitor` - Visitor
* `Regular` - Regular Attendee
* `Established` - Established
* `Relocated` - Relocated (Living Abroad)
* `Inactive` - Inactive
* `Transferred` - Transferred to Another Church
* `Deceased` - Deceased
 */
export type MembershipStatusEnum = typeof MembershipStatusEnum[keyof typeof MembershipStatusEnum];


export const MembershipStatusEnum = {
  Visitor: 'Visitor',
  Regular: 'Regular',
  Established: 'Established',
  Relocated: 'Relocated',
  Inactive: 'Inactive',
  Transferred: 'Transferred',
  Deceased: 'Deceased',
} as const;

export const MemberPrefix = {...PrefixEnum,...BlankEnum,} as const
export const MemberRelationship = {...RelationshipEnum,...BlankEnum,} as const
export const MemberMembershipStatus = {...MembershipStatusEnum,...BlankEnum,} as const
export const MemberEducationLevel = {...EducationLevelEnum,...BlankEnum,} as const
export interface Member {
  readonly id: number;
  readonly full_name: string;
  readonly age: string;
  readonly spouse_full_name: string;
  ministries: string[];
  positions: string[];
  readonly member_key: string;
  prefix?: typeof MemberPrefix[keyof typeof MemberPrefix];
  /** @maxLength 100 */
  first_name: string;
  /** @maxLength 100 */
  middle_name?: string;
  /** @maxLength 100 */
  maiden_name?: string;
  /** @maxLength 100 */
  last_name: string;
  date_of_birth: string;
  /** @maxLength 100 */
  place_of_birth?: string;
  gender: GenderEnum;
  relationship?: typeof MemberRelationship[keyof typeof MemberRelationship];
  /** @nullable */
  marriage_date?: string | null;
  /**
   * @maxLength 17
   * @pattern ^\+?1?\d{9,15}$
   */
  phone_number: string;
  /**
   * @maxLength 17
   * @pattern ^\+?1?\d{9,15}$
   */
  secondary_phone_number?: string;
  /** @maxLength 254 */
  email?: string;
  /** @maxLength 255 */
  address?: string;
  /** @maxLength 255 */
  address_line2?: string;
  /** @maxLength 255 */
  city?: string;
  /** @maxLength 100 */
  province?: string;
  /** @maxLength 255 */
  country: string;
  /** @nullable */
  membersince?: string | null;
  membership_status?: typeof MemberMembershipStatus[keyof typeof MemberMembershipStatus];
  /** @maxLength 255 */
  previous_church?: string;
  baptized?: boolean;
  /** @nullable */
  baptized_at?: string | null;
  /** @maxLength 255 */
  baptized_where?: string;
  /** @nullable */
  confirmation_date?: string | null;
  /** @maxLength 255 */
  occupation?: string;
  /** @maxLength 255 */
  employer?: string;
  education_level?: typeof MemberEducationLevel[keyof typeof MemberEducationLevel];
  /** @maxLength 255 */
  skills?: string;
  /** @maxLength 255 */
  emergency_contact_name?: string;
  /** @maxLength 100 */
  emergency_contact_relationship?: string;
  /**
   * @maxLength 17
   * @pattern ^\+?1?\d{9,15}$
   */
  emergency_contact_phone?: string;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 64 */
  avatar_fallback?: string;
  notes?: string;
  pin_set?: boolean;
  /** @maxLength 128 */
  access_pin?: string;
  is_trash?: boolean;
  /** @nullable */
  trash_date?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
  assembly: number;
  /** @nullable */
  created_by?: number | null;
  /** @nullable */
  updated_by?: number | null;
  /** @nullable */
  spouse?: number | null;
}

export interface Homecell {
  readonly id: number;
  /** @maxLength 255 */
  group_name: string;
  description?: string;
  readonly leader: Member;
  leader_id?: number;
  readonly members: readonly Member[];
  member_ids?: number[];
  non_church_members?: string;
  is_archived?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface HomecellSummary {
  readonly id: number;
  /** @maxLength 255 */
  group_name: string;
}

export interface Income {
  readonly id: number;
  church: CountryInfo;
  /** @nullable */
  timestamp?: string | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  offering?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fundraising?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  thanksgiving?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  donations?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_income?: string;
  /** @nullable */
  statement?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface Overhead {
  readonly id: number;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  amount?: string;
  notes?: string;
  timestamp: string;
  readonly assembly: number;
  /** @nullable */
  readonly report: number | null;
  readonly overhead_type: string;
  overhead_type_name: string;
}

export interface PaginatedAssetList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Asset[];
}

export interface PaginatedExpenditureList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Expenditure[];
}

export interface PaginatedFixedExpenditureList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: FixedExpenditure[];
}

export interface PaginatedIncomeList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Income[];
}

/**
 * * `public` - Public
* `private` - Private
* `draft` - Draft
 */
export type Status67aEnum = typeof Status67aEnum[keyof typeof Status67aEnum];


export const Status67aEnum = {
  public: 'public',
  private: 'private',
  draft: 'draft',
} as const;

export interface Post {
  readonly id: number;
  author: Author;
  assembly: AssemblySummary;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  likes: Author[];
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  views?: number;
  readonly images: readonly PostImage[];
  comments: Comment[];
  status?: Status67aEnum;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface PaginatedPostList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Post[];
}

export interface PasswordResetConfirmRetype {
  uid: string;
  token: string;
  new_password: string;
  re_new_password: string;
}

/**
 * Base serializer that generates:
- url: self-detail URL
- links: related object URLs
- actions: edit/delete/bulk-delete URLs
- collection_actions: bulk delete/restore URLs
Permissions are omitted since authenticated users have full access.
 */
export interface PatchedAssemblyReport {
  readonly id?: number;
  assembly?: number;
  period_start?: string;
  period_end?: string;
  status?: AssemblyReportStatusEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  attendance_total?: number;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  income_total?: string;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  expense_total?: string;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  tithe_total?: string;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  balance?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  members_total?: number;
  /** @nullable */
  finalized_at?: string | null;
  readonly url?: string;
}

export interface PatchedAsset {
  readonly id?: number;
  assembly?: AssemblyISO;
  /** @maxLength 255 */
  item_code?: string;
  /** @maxLength 255 */
  item_name?: string;
  /** @maxLength 2000 */
  description?: string;
  condition?: ConditionEnum;
  asset_type?: AssetTypeEnum;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  units?: number;
  acquisition_date?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  acquisition_cost?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  residual?: string;
  /** @maxLength 255 */
  vendor?: string;
  readonly asset_images?: readonly AssetImage[];
  /** @nullable */
  created_by?: number | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedAuthHistory {
  readonly id?: number;
  last_login?: string;
  last_logout?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  user?: number;
}

export interface PatchedBlog {
  readonly id?: number;
  author?: MinimalUser;
  /** @maxLength 255 */
  title?: string;
  subtitle?: string;
  body?: string;
  category?: BlogCategoryEnum;
  /** @nullable */
  image?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  status?: StatusDaeEnum;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
}

export const PatchedChurchStatus = {...ChurchStatusEnum,...BlankEnum,} as const
/**
 * * `admin` - Admin
* `overseer` - Overseer
* `assistant` - Assistant
* `coordinator` - Coordinator
 */
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];


export const RoleEnum = {
  admin: 'admin',
  overseer: 'overseer',
  assistant: 'assistant',
  coordinator: 'coordinator',
} as const;

export interface ZoneLeadership {
  readonly id: number;
  role: RoleEnum;
  appointed_at: string;
  /** @nullable */
  ended_at?: string | null;
  is_active?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  zone: number;
  user: number;
}

export interface Zone {
  /** @maxLength 100 */
  name: string;
  /** @maxLength 20 */
  code: string;
  description?: string;
  /** @maxLength 255 */
  office_location?: string;
  office_address?: string;
  /** @maxLength 30 */
  office_phone?: string;
  /** @maxLength 254 */
  office_email?: string;
  /** @nullable */
  established_date?: string | null;
  is_active?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  readonly leadership: readonly ZoneLeadership[];
}

export interface PatchedChurch {
  readonly id?: number;
  readonly uuid?: string;
  /** @maxLength 100 */
  name?: string;
  zone?: Zone;
  description?: string;
  assigned_pastors?: number[];
  /** @maxLength 255 */
  address?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 100 */
  province?: string;
  /** @maxLength 100 */
  country?: string;
  /** @maxLength 3 */
  country_code?: string;
  /** @maxLength 12 */
  language?: string;
  /** @maxLength 12 */
  currency?: string;
  /** @maxLength 20 */
  phone_number?: string;
  /** @maxLength 20 */
  email?: string;
  avatar?: string;
  cover_image?: string;
  /** @maxLength 36 */
  avatar_fallback?: string;
  status?: typeof PatchedChurchStatus[keyof typeof PatchedChurchStatus];
  readonly total_members?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedCreatePost {
  author?: number;
  assembly?: number;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  views?: number;
  readonly images?: readonly PostImage[];
  uploaded_images?: string[];
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedCreateUser {
  /** @maxLength 255 */
  first_name?: string;
  /** @maxLength 255 */
  last_name?: string;
  /** @maxLength 255 */
  email?: string;
  roles?: number[];
  /** @nullable */
  church?: number | null;
  assemblies?: number[];
  password?: string;
  re_password?: string;
}

export interface PatchedCurrentUser {
  readonly id?: number;
  readonly user_id?: string;
  /** @maxLength 255 */
  first_name?: string;
  /** @maxLength 255 */
  last_name?: string;
  /** @maxLength 255 */
  username?: string;
  /** @maxLength 255 */
  email?: string;
  /**
   * Used for account recovery or alternative communication.
   * @maxLength 254
   * @nullable
   */
  recovery_email?: string | null;
  /** @nullable */
  church?: number | null;
  readonly assembly?: AssemblySummary;
  readonly assemblies?: readonly Church[];
  readonly roles?: readonly Role[];
  readonly full_name?: string;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 26 */
  avatar_fallback?: string;
  is_active?: boolean;
  is_admin?: boolean;
  is_onboarded?: boolean;
  readonly is_db_staff?: string;
  readonly is_db_zone_staff?: string;
  readonly is_academy_staff?: string;
  readonly is_student?: string;
  readonly is_staff?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedDocumentation {
  readonly id?: number;
  /** @maxLength 255 */
  title?: string;
  body?: string;
  category?: DocumentationCategoryEnum;
  status?: StatusDaeEnum;
  readonly author?: number;
  readonly author_name?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedExpenditure {
  readonly id?: number;
  /** @maxLength 255 */
  invoice_number?: string;
  invoice_date?: string;
  /** @maxLength 255 */
  name?: string;
  description?: string;
  category?: ExpenditureCategoryEnum;
  /** @maxLength 255 */
  supplier?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  quantity?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  readonly total?: string;
  /** @nullable */
  receipt?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  assembly?: number;
  /** @nullable */
  report?: number | null;
  /** @nullable */
  created_by?: number | null;
}

export interface PatchedFixedExpenditure {
  readonly id?: number;
  assembly?: AssemblyISO;
  /** @nullable */
  created_by?: number | null;
  timestamp?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  rent?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  wages?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  water?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  electricity?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  telephone?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  internet?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  security?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fuel?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  car_maintenance?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  humanitarian?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  investment?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  bank_charges?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  insurance?: string;
  remarks?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  remittance?: string;
  /** @nullable */
  remittance_receipt?: string | null;
  /** @nullable */
  remittance_moderator?: number | null;
  is_remittance_verified?: boolean;
}

export interface PatchedHomecell {
  readonly id?: number;
  /** @maxLength 255 */
  group_name?: string;
  description?: string;
  readonly leader?: Member;
  leader_id?: number;
  readonly members?: readonly Member[];
  member_ids?: number[];
  non_church_members?: string;
  is_archived?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedIncome {
  readonly id?: number;
  church?: CountryInfo;
  /** @nullable */
  timestamp?: string | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  offering?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fundraising?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  thanksgiving?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  donations?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_income?: string;
  /** @nullable */
  statement?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export const PatchedMemberPrefix = {...PrefixEnum,...BlankEnum,} as const
export const PatchedMemberRelationship = {...RelationshipEnum,...BlankEnum,} as const
export const PatchedMemberMembershipStatus = {...MembershipStatusEnum,...BlankEnum,} as const
export const PatchedMemberEducationLevel = {...EducationLevelEnum,...BlankEnum,} as const
export interface PatchedMember {
  readonly id?: number;
  readonly full_name?: string;
  readonly age?: string;
  readonly spouse_full_name?: string;
  ministries?: string[];
  positions?: string[];
  readonly member_key?: string;
  prefix?: typeof PatchedMemberPrefix[keyof typeof PatchedMemberPrefix];
  /** @maxLength 100 */
  first_name?: string;
  /** @maxLength 100 */
  middle_name?: string;
  /** @maxLength 100 */
  maiden_name?: string;
  /** @maxLength 100 */
  last_name?: string;
  date_of_birth?: string;
  /** @maxLength 100 */
  place_of_birth?: string;
  gender?: GenderEnum;
  relationship?: typeof PatchedMemberRelationship[keyof typeof PatchedMemberRelationship];
  /** @nullable */
  marriage_date?: string | null;
  /**
   * @maxLength 17
   * @pattern ^\+?1?\d{9,15}$
   */
  phone_number?: string;
  /**
   * @maxLength 17
   * @pattern ^\+?1?\d{9,15}$
   */
  secondary_phone_number?: string;
  /** @maxLength 254 */
  email?: string;
  /** @maxLength 255 */
  address?: string;
  /** @maxLength 255 */
  address_line2?: string;
  /** @maxLength 255 */
  city?: string;
  /** @maxLength 100 */
  province?: string;
  /** @maxLength 255 */
  country?: string;
  /** @nullable */
  membersince?: string | null;
  membership_status?: typeof PatchedMemberMembershipStatus[keyof typeof PatchedMemberMembershipStatus];
  /** @maxLength 255 */
  previous_church?: string;
  baptized?: boolean;
  /** @nullable */
  baptized_at?: string | null;
  /** @maxLength 255 */
  baptized_where?: string;
  /** @nullable */
  confirmation_date?: string | null;
  /** @maxLength 255 */
  occupation?: string;
  /** @maxLength 255 */
  employer?: string;
  education_level?: typeof PatchedMemberEducationLevel[keyof typeof PatchedMemberEducationLevel];
  /** @maxLength 255 */
  skills?: string;
  /** @maxLength 255 */
  emergency_contact_name?: string;
  /** @maxLength 100 */
  emergency_contact_relationship?: string;
  /**
   * @maxLength 17
   * @pattern ^\+?1?\d{9,15}$
   */
  emergency_contact_phone?: string;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 64 */
  avatar_fallback?: string;
  notes?: string;
  pin_set?: boolean;
  /** @maxLength 128 */
  access_pin?: string;
  is_trash?: boolean;
  /** @nullable */
  trash_date?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  assembly?: number;
  /** @nullable */
  created_by?: number | null;
  /** @nullable */
  updated_by?: number | null;
  /** @nullable */
  spouse?: number | null;
}

export interface PatchedOverhead {
  readonly id?: number;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  amount?: string;
  notes?: string;
  timestamp?: string;
  readonly assembly?: number;
  /** @nullable */
  readonly report?: number | null;
  readonly overhead_type?: string;
  overhead_type_name?: string;
}

export interface PatchedPost {
  readonly id?: number;
  author?: Author;
  assembly?: AssemblySummary;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  likes?: Author[];
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  views?: number;
  readonly images?: readonly PostImage[];
  comments?: Comment[];
  status?: Status67aEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
}

export interface PatchedRevenue {
  readonly id?: number;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  amount?: string;
  notes?: string;
  timestamp?: string;
  readonly assembly?: number;
  /** @nullable */
  readonly report?: number | null;
  readonly category?: string;
  category_name?: string;
  /** @nullable */
  statement?: string | null;
}

export interface PatchedTOS {
  readonly id?: number;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /** @maxLength 10 */
  version?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}

/**
 * * `Bank` - Bank
* `Cash` - Cash
* `Cheque` - Cheque
* `Payment By Phone` - Payment By Phone
* `Other` - Other
 */
export type PaymentMethodEnum = typeof PaymentMethodEnum[keyof typeof PaymentMethodEnum];


export const PaymentMethodEnum = {
  Bank: 'Bank',
  Cash: 'Cash',
  Cheque: 'Cheque',
  Payment_By_Phone: 'Payment By Phone',
  Other: 'Other',
} as const;

export interface PatchedTithe {
  readonly id?: number;
  timestamp?: string;
  notes?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount?: string;
  payment_method?: PaymentMethodEnum;
  /** @nullable */
  receipt?: string | null;
  /** @maxLength 100 */
  reference_code?: string;
  is_trash?: boolean;
  /** @nullable */
  trash_date?: string | null;
  readonly assembly?: number;
  /** @nullable */
  readonly report?: number | null;
  /** @nullable */
  member?: number | null;
}

export interface PatchedUniqueUserCheck {
  readonly id?: number;
  /** @maxLength 255 */
  username?: string;
  /** @maxLength 255 */
  email?: string;
}

export interface PatchedUpdatePost {
  readonly id?: number;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /** @nullable */
  image?: string | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  views?: number;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status67aEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
  author?: number;
  assembly?: number;
  likes?: number[];
}

export interface PatchedUser {
  readonly id?: number;
  /** @maxLength 128 */
  password?: string;
  /** @nullable */
  last_login?: string | null;
  /** Designates that this user has all permissions without explicitly assigning them. */
  is_superuser?: boolean;
  readonly user_id?: string;
  /** @maxLength 255 */
  first_name?: string;
  /** @maxLength 255 */
  last_name?: string;
  /** @maxLength 255 */
  username?: string;
  /** @maxLength 255 */
  email?: string;
  /**
   * Used for account recovery or alternative communication.
   * @maxLength 254
   * @nullable
   */
  recovery_email?: string | null;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 26 */
  avatar_fallback?: string;
  is_active?: boolean;
  is_admin?: boolean;
  is_onboarded?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @nullable */
  church?: number | null;
  /** The groups this user belongs to. A user will get all permissions granted to each of their groups. */
  groups?: number[];
  /** Specific permissions for this user. */
  user_permissions?: number[];
  assemblies?: number[];
  roles?: number[];
}

export interface Revenue {
  readonly id: number;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,2})?$ */
  amount?: string;
  notes?: string;
  timestamp: string;
  readonly assembly: number;
  /** @nullable */
  readonly report: number | null;
  readonly category: string;
  category_name: string;
  /** @nullable */
  statement?: string | null;
}

export interface SendEmailReset {
  email: string;
}

export interface SetPasswordRetype {
  new_password: string;
  re_new_password: string;
  current_password: string;
}

export interface SetUsername {
  current_password: string;
  /** @maxLength 255 */
  new_email: string;
}

export interface Tos {
  readonly id: number;
  /** @maxLength 255 */
  title?: string;
  content: string;
  /** @maxLength 10 */
  version?: string;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface Tithe {
  readonly id: number;
  timestamp: string;
  notes?: string;
  readonly created_at: string;
  readonly updated_at: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount?: string;
  payment_method?: PaymentMethodEnum;
  /** @nullable */
  receipt?: string | null;
  /** @maxLength 100 */
  reference_code?: string;
  is_trash?: boolean;
  /** @nullable */
  trash_date?: string | null;
  readonly assembly: number;
  /** @nullable */
  readonly report: number | null;
  /** @nullable */
  member?: number | null;
}

export interface TokenObtainPair {
  email: string;
  password: string;
  readonly access: string;
  readonly refresh: string;
}

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

export interface TokenVerify {
  token: string;
}

export interface UniqueUserCheck {
  readonly id: number;
  /** @maxLength 255 */
  username?: string;
  /** @maxLength 255 */
  email: string;
}

export interface UpdatePost {
  readonly id: number;
  /** @maxLength 255 */
  title?: string;
  content?: string;
  /** @nullable */
  image?: string | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  views?: number;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status67aEnum;
  readonly created_at: string;
  readonly updated_at: string;
  author: number;
  assembly: number;
  likes?: number[];
}

export interface User {
  readonly id: number;
  /** @maxLength 128 */
  password: string;
  /** @nullable */
  last_login?: string | null;
  /** Designates that this user has all permissions without explicitly assigning them. */
  is_superuser?: boolean;
  readonly user_id: string;
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
  /** @maxLength 255 */
  username?: string;
  /** @maxLength 255 */
  email: string;
  /**
   * Used for account recovery or alternative communication.
   * @maxLength 254
   * @nullable
   */
  recovery_email?: string | null;
  /** @nullable */
  avatar?: string | null;
  /** @maxLength 26 */
  avatar_fallback?: string;
  is_active?: boolean;
  is_admin?: boolean;
  is_onboarded?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  /** @nullable */
  church?: number | null;
  /** The groups this user belongs to. A user will get all permissions granted to each of their groups. */
  groups?: number[];
  /** Specific permissions for this user. */
  user_permissions?: number[];
  assemblies?: number[];
  roles?: number[];
}

export interface UserCreatePasswordRetype {
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
  /** @nullable */
  church?: number | null;
  /** @maxLength 255 */
  email: string;
  readonly id: number;
  password: string;
  re_password: string;
}

export interface UsernameResetConfirm {
  /** @maxLength 255 */
  new_email: string;
}

export interface ZoneCompliance {
  readonly id: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  year: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  month: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  total_assemblies?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  compliant_assemblies?: number;
  compliance_rate?: number;
  readonly evaluated_at: string;
  zone: number;
}

export type BookkeeperAssetsListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type BookkeeperExpenditureListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type BookkeeperIncomeListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type BookkeeperRegularExpenditureListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type PeopleMembersListParams = {
first_name?: string;
fullname?: string;
last_name?: string;
member_key?: string;
};

export type PostsPostsListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ReportsAuditLogsListParams = {
/**
 * * `CREATE` - Create
* `UPDATE` - Update
* `DELETE` - Delete
* `RESTORE` - Restore
 */
action?: ReportsAuditLogsListAction;
content_type?: number;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A search term.
 */
search?: string;
user?: number;
};

export type ReportsAuditLogsListAction = typeof ReportsAuditLogsListAction[keyof typeof ReportsAuditLogsListAction];


export const ReportsAuditLogsListAction = {
  CREATE: 'CREATE',
  DELETE: 'DELETE',
  RESTORE: 'RESTORE',
  UPDATE: 'UPDATE',
} as const;

